### ISSUE TITLE
Create a meetup kit for folks

### ISSUE THREAD

**Issue by caniszczyk** [cncf/communitygroups#10]
something similar to this: https://github.com/grpc-ecosystem/meetup-kit

we could just have a section in the README here that gives people advice

**Comment by s-mahesh-kumar** [comment]
hello @caniszczyk 

iam interested in contributing to this issue , 
but i dint get what you meant by "we could just have a section in the README here that gives people advice"
 where  is it  present in https://github.com/grpc-ecosystem/meetup-kit

**Comment by AudMonte01** [comment]
Closing this issue, as it was closed in May and we have been adding to the README since Ihor was running this program.
https://github.com/cncf/communitygroups/blob/main/README.md
