### ISSUE TITLE
[Organizer Request] Remove Ravi Soni

### ISSUE THREAD

**Issue by rvsoni** [cncf/communitygroups#101]
### Name of chapter inquiring about

Cloud Native Vadodara

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Ravi Soni 
Email: my.ravisoni@gmail.com

### Tell us why you want to be added or removed from the chapter

Lake of communication and clarity within the Organizer of CNCG Vadodara, a situation caused that the other organizer to leave the CNCG Vadodara Chapter. 

I would keep supporting CNCG Vadodara. but has to level as the Chapter Organizer.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [ ] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [ ] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [ ] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [ ] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [ ] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [ ] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [ ] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Hi @rvsoni - this GitHub issue is identical to the other GitHub issue your co-organizer submitted to resign. So I am curious if the situation that caused "the other organizer to leave" was with you or her since her GitHub issue read the same.

In the meantime, I have removed you from the chapter, but I would like to learn more.

Kind regards,
Audra

**Comment by rvsoni** [comment]
Hello @AudMonte01 

Yes, the Co-organizer did not communicate with the group and started making all decisions independently. 

We wanted to get more members on board to grow the community and conduct more knowledge-sharing sessions on CNCF Technology.

At one point, the co-organizer discussed our desire to leave a community with you (@AudMonte01) without our consent and kept us in the dark. One day, we were informed that a discussion was held for our ouster, and we were asked to fill out the form as a process to request to leave the group. 

We wanted to continue working with CNCG Vadodara, but a situation was created that made it pointless to remain in a group. We were kept out of all communication and discussion related to the community. 

So, we decided to request you remove us from CNCG Vadodara.
