### ISSUE TITLE
[Organizer Request] Remove Abhilasha Vyas from Vadodara chapter

### ISSUE THREAD

**Issue by abhilasha1978** [cncf/communitygroups#102]
### Name of chapter inquiring about

CNCG Vadodara 

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Dr. Abhilasha Vyas, CNCG Vadodara 

### Tell us why you want to be added or removed from the chapter

Lake of communication and clarity within the Organizer of CNCG Vadodara, a situation caused that the other organizer to leave the CNCG Vadodara Chapter.

I would keep supporting CNCG Vadodara. but has to level as the Chapter Organizer.

### Code of Conduct

- [ ] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [ ] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [ ] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [ ] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [ ] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [ ] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [ ] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [ ] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you for writing your resignation. I am sorry you feel there is a lack of communication.

Please do support the chapter as best as you can if you find a way to contribute to the ecosystem through projects, the glossary, writing blogs, or other community efforts. Or at least attend upcoming meetups to learn more about the ecosystem.

I have removed you as an organizer, and this ticket is now closed.
