### ISSUE TITLE
[Group Request] Kubernetes Pune

### ISSUE THREAD

**Issue by bhavin192** [cncf/communitygroups#104]
### City or location name for your CNCG

~~Kubernetes and Cloud Native Pune~~ Decided to use "Kubernetes Pune"

### What country do you want to start your community group in?

India

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Name: Bhavin Gandhi
Company: InfraCloud Technologies
GitHub: https://github.com/bhavin192/
LinkedIn: https://www.linkedin.com/in/bhavin192/
Website: https://geeksocket.in/tags/cloud-native/
Slack: Bhavin Gandhi in CNCF Slack. Display name: bhavin192
Bevy: https://community.cncf.io/u/mm58wd/

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Name: Sajeesh Nair
Company: Druva Inc
GitHub: https://github.com/sajeesh84/
LinkedIn: https://www.linkedin.com/in/sajeesh-nair/
Slack: Sajeesh Nair in CNCF Slack.
Bevy: https://community.cncf.io/u/m4e8n8/

### If you already run a meetup, please link it here

https://www.meetup.com/Kubernetes-Pune/

### What is your mission statement or objective for this new chapter?

Kubernetes Pune is a group for all Kubernauts who want to learn and share experiences about Kubernetes. This meetup group is for all skill levels right from beginners to experienced professionals. We will discuss various aspects of Kubernetes and the ecosystem around Kubernetes such as networking, storage, MLOps, AI Inference etc.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Hello @bhavin192 - thank you for submitting this ticket. Please copy in the GitHub handles of your co-organizers in which you would like to be also be added to this chapter. They will also need to response in agreement to the above terms, and have taken the open source inclusion free, online exam mentioned above.

As the the naming convention of your chapter, we will keep it Kubernetes Pune to keep consistent with your long-standing meetup.com group, and also to alleviate confusion between the current Pune chapter, which will now become "Cloud Native Pune".

Please let me know if you and the team have any questions about the above.

**Comment by AudMonte01** [comment]
Excellent - thank you.

@sajeesh84 - please comment here agreeing to the above terms and confirm you have taken the above-mentioned inclusive course (free online course).

**Comment by AudMonte01** [comment]
@sajeesh84 - following up here so we can proceed with getting this chapter started.

**Comment by sajeesh84** [comment]
@AudMonte01 @bhavin192 I have completed course and agree to the terms mentioned above.

**Comment by AudMonte01** [comment]
Thank you, @sajeesh84 - it looks like both you an @bhavin192 just need to complete your profiles with pictures of yourselves, since your profiles will be forward-facing on the chapter page. Thank you.

**Comment by AudMonte01** [comment]
Thank you for updating your profiles. You both have been added to the K8s Pune chapter. You should have received automated welcome emails from me with further instruction. I have also added you both in the global organizer channel in the CNCF Slack workspace.

* Please start by creating a description for the chapter, even if it's a copy and paste from meetup.com
* Then add your next meetup under the meetup event type so we can see the next LIVE event
* And finally and most importantly, is you can still use meetup.com as marketing tool, but registration must happen via community.cncf.io, so please point folks there in your meetup events pages. You can set the cap for those meetup.com events to 1 so it triggers a waitlist, and people will be more apt to follow the link to your new community chapter.

This ticket/issue is now closed.

**Comment by vishalanarase** [comment]
Hello @bhavin192 

I Vishal Anarase, would like to join as co-organizer for Kubernetes Pune Chapter to actively participate in its initiatives and contribute to the community's growth. With eight years of software development experience and contributions to projects like Kubernetes cluster autoscaler and Percona operators, I bring valuable insights and a passion for collaborative work. I look forward to engaging with like-minded professionals and contributing to the advancement of cloud-native computing in Pune.

**Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io**

Name: Vishal Anarase
Email: iamvishalanarase@gmail.com
Company: Civo
GitHub: https://github.com/vishalanarase
LinkedIn: https://www.linkedin.com/in/vishal-anarase-623707104/
Website: https://vishalanarase.github.io/
Slack: Vishal Anarase in CNCF Slack.
Bevy: https://community.cncf.io/u/mjfqfx

**Comment by AudMonte01** [comment]
Thank you, @vishalanarase - [please create an organizer request here](https://github.com/cncf/communitygroups/issues/new/choose), if you do not already work directly with the current organizers.

Here is a link to this chapter: https://community.cncf.io/kubernetes-pune/

**Comment by vishalanarase** [comment]
Hello @AudMonte01 

I have created new [issue](https://github.com/cncf/communitygroups/issues/151) for the same. I have already member of  Kubernetes Pune group.
