### ISSUE TITLE
[Organizer Request] Add Organizers to San Juan Chapter

### ISSUE THREAD

**Issue by LizzGarleb** [cncf/communitygroups#105]
### Name of chapter inquiring about

Cloud Native San Juan

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Carlos Santana
- GitHub: https://github.com/csantanapr
- LinkedIn: https://www.linkedin.com/in/csantanapr/
- Slack Workspace Name: csantanapr

Jose Roche
- GitHub: https://github.com/jmroche
- LinkedIn: https://www.linkedin.com/in/joseroche/
- Slack Workspace Name: Jose Roche

### Tell us why you want to be added or removed from the chapter

Carlos Santanas & Jose Roche would like to join as co-organizer to the Cloud Native San Juan Chapter. They will provide a more define assistant for event coordination as well as chapter organization.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [ ] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [ ] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [ ] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [ ] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [ ] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by jmroche** [comment]
Hi - I'd appreciate if you add me as an organizer to the CNCF San Juan chapter. 

Thanks!

**Comment by csantanapr** [comment]
Hi - I'd appreciate if you add me as an organizer to the CNCF San Juan chapter.

**Comment by AudMonte01** [comment]
Hello @csantanapr and @jmroche - please confirm you agree to the above terms and you have taken the free, inclusive open source exam mentioned above?

**Comment by jmroche** [comment]
Hi @AudMonte01 - I confirm that I both agree to the above terms and that I have taken the Linux Foundation Inclusive Open Source Community Orientation (LFC102) course and exam. 

Thanks,

Jose

**Comment by AudMonte01** [comment]
Thank you, @jmroche - now just awaiting @csantanapr. Even though he part of other chapters, we did not previously have these terms when he joined.

**Comment by csantanapr** [comment]
Hi @AudMonte01  - I confirm that I both agree to the above terms and that I have taken the Linux Foundation Inclusive Open Source Community Orientation (LFC102) course and exam.

**Comment by AudMonte01** [comment]
Excellent - thank you, @csantanapr. I have added you as an organizer to the San Juan chapter. You should have just received an automated welcome email from me. Some of the directions for next steps, you can bypass due to your existing inclusion in some of the communication channels.

@jmroche - it looks like I just need you to point me to your community.cncf.io profile so I may add you as a co-organizer as well. Thanks in advance.

**Comment by jmroche** [comment]
Hi @AudMonte01 here's my profile: https://community.cncf.io/u/mztpqu/#/about

**Comment by AudMonte01** [comment]
Thank you, @jmroche - I have added you as an organizer to the San Juan chapter. You should have received an automated welcome email from me. Please follow next steps there.

This issue/ticket is now closed.
