### ISSUE TITLE
[Group Request] Create a new chapter Dublin

### ISSUE THREAD

**Issue by henriquesantanati** [cncf/communitygroups#106]
### City or location name for your CNCG

Cloud Native Dublin

### What country do you want to start your community group in?

Ireland

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Henrqiue Santana, rick002@gmail.com, AWS, https://github.com/henriquesantanati, https://www.linkedin.com/in/henriquessantana/, I need to be invited to CNCF Slack workspace, https://community.cncf.io/u/mm3fqf/#/about

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Bruno Gabriel da Silva, bgsilvait@gmail.com, Sysdig, https://github.com/bgsilvait, https://www.linkedin.com/in/bgsilvait/, Bruno Gabriel da Silva, https://community.cncf.io/u/mzvypa/#/about

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Michael Walsh, walshmichael310@gmail.com, Workday, https://github.com/walsm232, https://www.linkedin.com/in/michael-walsh-dev/, MichaelW, https://community.cncf.io/u/mzv25j/#/about

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Pauline Lallinec, pauline.lallinec@gmail.com, Workday, https://github.com/plallin, https://ie.linkedin.com/in/plallinec, Pauline, https://community.cncf.io/u/mbgfa3/#/about

### If you already run a meetup, please link it here

https://www.meetup.com/dublin-kubernetes-meetup/

### What is your mission statement or objective for this new chapter?

As tech enthusiasts passionate about open source, our mission is to champion cloud-native technologies and foster a vibrant community in Dublin. We strive to create a platform for networking, idea exchange, and promoting the CNCF's values of diversity and open solutions. Through meetups and collaborations, we aim to empower the local community and tech companies to innovate and excel in the cloud-native landscape.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Hi @henriquesantanati - this is a good group of people. I just added you to a legacy chapter that has been dormant on community.cncf.io since 2019. You should have just received an automated welcome email from me.

In order for me to add @bgsilvait, @walsm232, and @plallin - each one needs to comment here that they agree to the above terms.

Thanks in advance,
Audra

**Comment by bgsilvait** [comment]
lgtm

**Comment by walsm232** [comment]
Thanks Audra! I agree with the above terms

**Comment by plallin** [comment]
agreed! SOrry for the delay, kubelet :baby_bottle:  was keeping me busy

**Comment by AudMonte01** [comment]
Thank you, everyone! I have added each of you as organizers. You should have just received automated welcome emails from me with further instructions.

Pauline - please add a headshot for your community.cncf.io profile and since your profile will be forward-facing on the chapter and meetup/event pages.

Thank you - this issue/ticket is now closed.
