### ISSUE TITLE
[Organizer Request] Add Hemanth to Dallas, TX chapter

### ISSUE THREAD

**Issue by hemanth-avs** [cncf/communitygroups#107]
### Name of chapter inquiring about

Cloud Native Dallas

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Hemanth AVS
- Github - https://github.com/hemanth-avs/
- Linkedin - https://www.linkedin.com/in/hemanth-avs/
- My CNCF Profile link - https://community.cncf.io/u/mcwj5a/#/about
- Slack Workspace Name - hemanth.avs

### Tell us why you want to be added or removed from the chapter

I'd like to join as a co-organizer for the Cloud Native Dallas Chapter. I've been actively attending the chapter for the past year, spoken at the event multiple times, and already work closely with the co-hosts Mars Toktonaliev, Damian Igbe, Aly Ibrahim. I would like take on a larger role and contribute to the chapter's success.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by hemanth-avs** [comment]
I agree to the Inclusive but didn't complete the course yet

fyi @tokt

**Comment by tokt** [comment]
/lgtm
Thank you and strong +1!

**Comment by hemanth-avs** [comment]
My CNCF Profile link - https://community.cncf.io/u/mcwj5a/#/about

team, please let me know if any additional information needed from my end, thanks

**Comment by hemanth-avs** [comment]
team, please let me know if any additional information needed from my end, thanks

**Comment by AudMonte01** [comment]
Hello @tokt - can you please tag the other Dallas organizers so they can add their vote or questions here? Thanks in advance.

**Comment by Cloudtechexperts** [comment]
It's a yes vote, we would be glad to have Hemanth join us  +1

**Comment by igbedo** [comment]
It's me voting from my account +1

**Comment by AudMonte01** [comment]
Hello @hemanth-avs - you have been added as an organizer to the chapter and should have just received an automated welcome email from me.

This issue/ticket is now closed.
