### ISSUE TITLE
[Organizer Request] Add Cishahayo Songa Achille to Rwanda chapter

### ISSUE THREAD

**Issue by songa1** [cncf/communitygroups#108]
### Name of chapter inquiring about

Cloud Native Rwanda

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Cishahayo Songa Achille, achille@techinika.com, Techinika, https://github.com/songa1, https://linkedin.com/in/achillesonga, Cishahayo Songa Achille in CNCF Slack, https://community.cncf.io/u/mgtb3f/

### Tell us why you want to be added or removed from the chapter

I, Cishahayo Songa Achille would like to start the Cloud Native Rwanda community because I found that it is not there, and I believe this is a technology that people need to know about. I have been building another community that has a component of cloud computing, artificial intelligence, web3 and software development, and our main goal was to help Rwandan technologists learn and build on top of these new technologies. Starting this chapter will allow us to introduce cloud native and build a community that will allow people to work together, share knowledge and use cloud native in their deployment needs.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Hello @songa1 - sorry for the delay here. Thank you for your interest in hosting a chapter in Rwanda, as we do not have an active chapter there yet.

First - please tell me which CNCF projects or part of the ecosystem you currently partake in or use on a weekly or monthly basis. Thanks in advance.

**Comment by songa1** [comment]
Thank you @AudMonte01 for the response. 

I have worked with a team that used Microservices and Kubernetes. I have taken some lessons on Kubernetes, but haven't used it in my projects. I thought it was an interesting technology that many would benefit from understanding how it works.

**Comment by AudMonte01** [comment]
Thank you for your reply, @songa1 ~

Another question:
* What is your strategy/plan for speakers/content, space (in-person or virtual), and sponsors?

**Comment by songa1** [comment]
For speakers, my plan is to build a dedicated community of speakers who are always ready to participate in our events. I intend to collaborate with other tech communities that already have professionals working with CNCF technologies. Once we’re confirmed, we’ll start networking with these communities, as well as with government entities, to build connections and make an active online presence to continually attract new participants.

Regarding space, we’ll primarily use virtual meetings for our regular events. However, we also have established partnerships with organizations like GIZ, Hanga Hubs, and UNIPOD, who have accessible event spaces suitable for technology communities. These venues will be ideal for in-person events and help us reach a wider audience.

For sponsors, we’ll first identify potential sponsors from the education sector and those who are already using CNCF technologies or could benefit from them. We’ll create tailored sponsorship packages that cater to different types of sponsors and engage them through various activities to ensure their involvement and support.

**Comment by AudMonte01** [comment]
This sounds like a great plan, @songa1!

Next step would be to name this at a city or state level instead of a country level. Can you tell me which city (or state) would be best?

**Comment by songa1** [comment]
Hello Audra,

We can call it Cloud Native Kigali. Since I am based in Kigali, it would be the easiest.

**Comment by AudMonte01** [comment]
Excellent - the chapter has been created and you have been added as an organizer. You should have received an automated welcome email from me with next steps.

Please add a profile picture to [your CNCF Slack profile](https://cloud-native.slack.com/team/U07M9K9MTML) and I will then introduce you into the global organizer community group chapter.
