### ISSUE TITLE
[Group Request] Create a new chapter in Bahia, Brazil

### ISSUE THREAD

**Issue by miltlima** [cncf/communitygroups#109]
### City or location name for your CNCG

Cloud Native Bahia

### What country do you want to start your community group in?

Brazil

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Milton Lima de Jesus, Milton.lima@outlook.com, Digibee, https://community.cncf.io/u/m5de4s/#/about, https://www.linkedin.com/in/miltonlimaj, GitHub.com/miltlima, I need invite to ingress to slack 

### What is your mission statement or objective for this new chapter?

Share about cloud native applications inside a inclusive community , speak and share knowledge about kubernetes and ecosystem 

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Hello @miltlima - thank you for your interest in hosting a chapter in Bahia, Brazil. You seem like a great fit for running good content in your state. Please be advised that we typically name chapters on a city basis. Is there a well-known city in Bahia that you would suggest naming your chapter after?

**Comment by miltlima** [comment]
Hello @AudMonte01, the name of community is Salvador

**Comment by AudMonte01** [comment]
Excellent - thank you! We have created a "Cloud Native Salvador, Bahia" for you, and added you as an organizer. You should have just received an automated welcome email from me with further steps.

This ticket/issue is now closed.
