### ISSUE TITLE
[Organizer Request] Add Harsh Manvar

### ISSUE THREAD

**Issue by harsh4870** [cncf/communitygroups#110]
### Name of chapter inquiring about

Cloud Native Gandhinagar

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Name : Harsh Manvar
Company : Man
Email : harsh.manvar111@gmail.com
Github : https://github.com/harsh4870
Linkedin : https://www.linkedin.com/in/harsh-manvar-64a30aa3/
CNCF_slack : harsh_manvar
Profile link : https://community.cncf.io/u/m45yta/#/about

### Tell us why you want to be added or removed from the chapter

I, Harsh Manvar, a CNCF Ambassador, would like to join CNCF Gandhinagar as a co-organizer. I have experience in managing community planning and selecting speakers, and I am eager to contribute more to the community.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by neelshah2409** [comment]
We (CNCG Gandhinagar team) would warmly welcome @harsh4870 to the team !

**Comment by AudMonte01** [comment]
Thank you for confirming, @neelshah2409. @harsh4870 - I have added you as an organizer to the chapter. You should have just received an automated welcome email from me. Please take next steps there and join the team for their next sync.

This issue/ticket is now closed.
