### ISSUE TITLE
[Group Request] Create a new chapter in Curitiba, Brazil

### ISSUE THREAD

**Issue by pedroalvesbatista** [cncf/communitygroups#112]
### City or location name for your CNCG

Cloud Native Curitiba

### What country do you want to start your community group in?

Brazil

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Pedro Henrique Alves Batista, [pedro.expb@gmail.com](mailto:pedro.expb@gmail.com), Madya Labs, https://github.com/pedroalvesbatista, https://www.linkedin.com/in/pedro-alves-batistahq3, Pedro Alves Batista, https://community.cncf.io/u/mwskq8

### What is your mission statement or objective for this new chapter?

Unite and explore the world of cloud native applications, deployments, along with tools from CNCF projects, best practices, open-source collaboration as well methodologies which unlocks all the potentials of cloud native applications.

IoT, 5G, Edge Computing and Big Data are themes to also be explored by our community.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Oi @pedroalvesbatista! Thank you for applying to host a chapter in Curitiba. You seem like a good fit as a chapter organizer based on your connections and open source experience. Can you shed some light on what part of the CNCF ecosystem have you participated in, and over how many years?

Also, I noticed Curitiba is about a 4-hour drive from Floripa and 6 hours from Sao Paulo, in which we have active chapters there. That said, I don't see any issues with opening a chapter in this location, but I will connect you to CNCF ambassadors for guidance and collaboration, that also co-organizer run the two-mentioned chapters.

Cc @krol3 and @knabben

**Comment by pedroalvesbatista** [comment]
Hi @AudMonte01, thankyou very much for the reply and considering our Chapter !

I've been involved in "shadow mode", only participating on meetings in CNCF Tinkerbell project for about 1 year, but the last 3-4 months I have put my hands into work and start to scratch contributions to Tinkerbell's documentation. 

I also plan to help Kubernetes documentation translation to Portuguese. 

Last but not least, I'm integrating the CNCF Kubernetes WG on Edge and IoT applications for about 1 month, but only participating on meetings, and in the future start to make Proofs of Concept using Kubernetes on Edge appliances and applications.

**Comment by krol3** [comment]
Thanks @AudMonte01  and @pedroalvesbatista , I'm available for any help or support that you need with the new chapter

**Comment by AudMonte01** [comment]
These are awesome starts, and the fact there are three (going on 4 with a CNCG) places within the ecosystem you want to contribute to, sounds like a good path to Ambassadorship one day.

 Before I confirm you as an organizer, please tell me which city you reside/live in, or how often you are in Curitiba? Your LinkedIn says "Campo Limpo Paulista, São Paulo, Brazil".

**Comment by pedroalvesbatista** [comment]
Awesome @AudMonte01 ! 

I'm based right now in Campo Limpo Paulista, but half of a month I'm in Curitiba for meetups and personal arrangements. Sometimes I keep based the whole month for taking care of community subjects.

**Comment by AudMonte01** [comment]
Excellent - this will work out just fine in terms of our standards for activity and locality.

I just created the chapter and and add you as an organizer. You should have just received an automated welcome email from me for next steps. I have also added you to the organizer Slack channel in the CNCF workspace.

This issue/ticket is now closed.
