### ISSUE TITLE
[Organizer Request] Add Choah Jung

### ISSUE THREAD

**Issue by whoisxx** [cncf/communitygroups#113]
### Name of chapter inquiring about

Cloud Native Vancouver

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Choah Jung, whoisxx1@gmail.com, Okta, https://github.com/whoisxx, https://www.linkedin.com/in/choah-jung-37826b14a, https://community.cncf.io/u/mcr4eh/#/about

### Tell us why you want to be added or removed from the chapter

I, Choah Jung, would like to join CNCF Vancouver as a co-organizer. I have experience in managing community planning and selecting speakers, and I am eager to contribute more to the community.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by ShankyJS** [comment]
Hey @AudMonte01 we would love to have Choah as a member of our organizing team @ Vancouver ❤️🇨🇦

**Comment by AudMonte01** [comment]
Thank you for confirming, @ShankyJS - I just added @whoisxx as an organizer. Choa, you should have just received an automated welcome email from me, please follow direction there and join the team's next sync.

This issue is now closed.

**Comment by ShankyJS** [comment]
Thanks Audra!
