### ISSUE TITLE
[Organizer Request] Add Michelle Dhanani to Atlanta chapter

### ISSUE THREAD

**Issue by michelleN** [cncf/communitygroups#114]
### City or location name for your CNCG

North Atlanta Cloud Native Meetup

### What country do you want to start your community group in?

United States

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Name: Michelle Dhanani (formerly Michelle Noorali). 
Email: michelle@fermyon.com
GitHub: michelleN
LinkedIn: https://www.linkedin.com/in/michelle-noorali/
CNCF Slack: Michelle Dhanani

### What is your mission statement or objective for this new chapter?

This community is about exploring cloud native tools, patterns and best practices together in an open and welcoming environment. All skill levels are welcome. We use this space to connect with each other and learn from one another. Come hang out, share what you are working on or learning, or learn something new!

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Hi @michelleN - I'm so happy to see you're interest in running a CNCF chapter. Looking at your LinkedIn profile, this seems like a no-brainer to me.

We do however already have an [Atlanta chapter](https://community.cncf.io/atlanta/) with 2 organizers. While you are requesting to do North Atlanta, I would recommend you collaborate with these folks and become a co-organizer. Then if you want to be the one to organize the meetups in North Atlanta, you could take the lead there to...
* help maintain the activity level of the chapter
* and spread the cloud native love to the North

Looping in @phenixblue and @AlexB138 to comment with their thoughts.

**Comment by michelleN** [comment]
I think that's a great plan @AudMonte01. I spoke to @phenixblue at the Kubernetes atlanta meetup last night. I'll help where I can here and maybe do a north atlanta meetup later down the road.

**Comment by AudMonte01** [comment]
Amazing! I see @phenixblue emoji reaction to your last message. 🎉

@AlexB138 - please affirm we can add Michell here as a chapter organizer.

**Comment by michelleN** [comment]
I should have clarified! We didn't discuss a formal organizer role. The current organizers are doing a great job. I just recently re-joined the group and am happy to help in an informal capacity.

**Comment by AudMonte01** [comment]
Ah okay - thank you for clarifying, @michelleN.  I will then close this issue/ticket.
