### ISSUE TITLE
[Organizer Request] Add or Remove Organizers to Istanbul chapter

### ISSUE THREAD

**Issue by halil-bugol** [cncf/communitygroups#115]
### Name of chapter inquiring about

Cloud Native Istanbul

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Halil Bugol, Co-Founder at Kubezy, CNCF Ambassador and CNCG Organizer, https://www.linkedin.com/in/halilbugol/, CNCF Slack: Halil

### Tell us why you want to be added or removed from the chapter

We would like to add Aysegul as an organizer to balance the group in terms of gender and to defend all values ​​equally

Aysegul Akbas, Devops Engineer at Hepapi, CNCF Slack: aysegulakbas, https://community.cncf.io/u/mjv9w2/

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you, @halil-bugol - please have Aysegul respond here in GitHub with their affirmation of the above organizer terms.

**Comment by aysegulakbas** [comment]
@AudMonte01  Hi! I accept the organizer's conditions mentioned above. Thank you.

**Comment by AudMonte01** [comment]
Excellent - I have added you to the chapter @aysegulakbas. You should have just received and automated welcome email from me. Please follow next steps from there.

This ticket is now closed.
