### ISSUE TITLE
[Organizer Request] Add Organizer Name - Timisoara Cloud Native Chapter

### ISSUE THREAD

**Issue by romina2001** [cncf/communitygroups#116]
### Name of chapter inquiring about

Timisoara - Romania

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

OSS enthusiast with a focus on Linux/Windows virtualization/containerization and love for knowledge sharing.
Name: Nashwan Azhari
E-mail: [nazhari@cloudbasesolutions.com](mailto:nazhari@cloudbasesolutions.com)
GitHub: https://github.com/aznashwan
LinkedIn: http://linkedin.com/in/aznashwan

Name: Nashwan Azhari
E-mail: [nazhari@cloudbasesolutions.com](mailto:nazhari@cloudbasesolutions.com)
GitHub: https://github.com/aznashwan
LinkedIn: http://linkedin.com/in/aznashwan

### Tell us why you want to be added or removed from the chapter

Nashwan wants to join as a co-organizer. He knows very well the cloud native ecosystem and he is a cloud native contributor.
He is one of our best local presenters and I believe he will be a valuable addition to our organizers group.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [ ] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [ ] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by romina2001** [comment]
Hello @AudMonte01 we do have one more organizer to add to our local Cloud Native Group

**Comment by AudMonte01** [comment]
Thank you, @romina2001 

@aznashwan - please comment here that you agree to the above terms, and confirm you have created an account on community.cncf.io.

**Comment by aznashwan** [comment]
>  please comment here that you agree to the above terms

Yes, and can also confirm I've already gone through the course.

> confirm you have created an account on community.cncf.io

Yep, you can find my [CNCF account here](https://community.cncf.io/u/mb5tt4/#/about).

Really Looking forward to joining the branch.
Please let me know if you need anything else!

**Comment by AudMonte01** [comment]
Excellent! You have been added to the chapter, @aznashwan . You should have just received an automated email from me with next steps. 

This ticket is now closed.

**Comment by aznashwan** [comment]
Yep, many thanks to you and @romina2001 for the help! 😄
