### ISSUE TITLE
[Organizer Request] Add Organizer Gina Guevara

### ISSUE THREAD

**Issue by carlosaq** [cncf/communitygroups#117]
### Name of chapter inquiring about

Cloud Native Quito

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Gina Guevara.
https://www.linkedin.com/in/gina-guevara-9560a0269/
gina.y.guevara@gmail.com

### Tell us why you want to be added or removed from the chapter

Gina will help of moving the community in Quito, plan a meetup soon in about a month, for that we need to include Gina as organizer.
https://www.linkedin.com/in/gina-guevara-9560a0269/
gina.y.guevara@gmail.com

Carlos Arturo Quiroga current organizer, will continue being an organizer of the chapter, 
https://www.linkedin.com/in/carlosarturoq/
carlosarturoq@gmail.com

The community continues to grow on that side with this team support.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by GinaGuevara** [comment]
thank you for considering our request. I accept all the terms

**Comment by AudMonte01** [comment]
Hi Gina - thank you for confirming the organizer terms. I have added you to the chapter. You should have just received an automated welcome email from me. Please follow next steps there.

I am now closing this issue/ticket.

**Comment by GinaGuevara** [comment]
hi Audra, I will follow the process and update the chapter information.
Thanks

Gina Guevara
