### ISSUE TITLE
[Organizer Request] Add Organizer to Abu Dhabi

### ISSUE THREAD

**Issue by sharathvutpala** [cncf/communitygroups#118]
### Name of chapter inquiring about

Abu Dhabi

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Sharath Chandra Vutpala, Technology Innovation Institute, https://github.com/sharathvutpala, https://www.linkedin.com/in/sharathvutpala/, https://community.cncf.io/u/m6988g. 

### Tell us why you want to be added or removed from the chapter

I, Sharath Chandra Vutpala, would like to join as a co-organizer. Being part of a technical community is a great way to share and learn knowledge, stay up-to-date with the latest advancements which enables to grow as a team. I feel my skills and experience would be a an asset to the chapter. 

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [ ] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by sharathvutpala** [comment]
Hi @AudMonte01 , just wanted to follow up on this, I haven't received any welcome email or any other information regarding the next steps. 

Can you please take a look once? Thanks.

**Comment by AudMonte01** [comment]
Hello @sharathvutpala - thank you for the ping. There is already a team of [2 new organizers](https://community.cncf.io/abu-dhabi/) that are in the process of being enabled, so I recommend participating first by attending, and then re-opening this issue once those organizers are established with a cadence of consistent meetups.

Cc @akashkaveti and @hernandezj84
