### ISSUE TITLE
Come up with social media + meetup guidelines

### ISSUE THREAD

**Issue by caniszczyk** [cncf/communitygroups#12]
There have been some cases where people have felt meetups weren't vendor neutral and that is definitely against the spirit of CNCF supported meetups.

We have CNCF social media guidelines for our projects that are very specific on what is allowed and not, we should do something similar for meetups:

https://docs.google.com/document/d/1FfOUiW1djoecBjy9XJFWApLRjhjX6s5Tnl8zmnUCLxM/edit?usp=sharing

**Comment by jbeda** [comment]
Also making sure that these events adhere to the CNCF CoC too.

**Comment by AudMonte01** [comment]
This has been added here: https://github.com/cncf/communitygroups/blob/main/README.md#social-media-best-practices-and-resources
