### ISSUE TITLE
[Organizer Request] Add Mohamed Ibrahim Ahmad to Riyadh chapter

### ISSUE THREAD

**Issue by RafMo20D** [cncf/communitygroups#120]
### Name of chapter inquiring about

Cloud Native Riyadh

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

https://github.com/RafMo20D
https://www.linkedin.com/in/mohamed-ibrahim-a-441258199/

### Tell us why you want to be added or removed from the chapter

Confident, enthusiastic, and professional DevOps Engineer with leadership experience. Proficient in multiple technology stacks, with a focus on cloud technologies, automation, CI/CD, and network design and security. Experienced in cross-functional team structures in agile and fast-paced environments. Riyadh, Saudi Arabia

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Hello @RafMo20D - thank you for your interest in co-organizing this chapter.

As of now there are already 4 organizers: https://community.cncf.io/cloud-native-riyadh/.
I am copying in the original organizers, @rajrahul03 so he can tell you in what ways are best to participate.

**Comment by rajrahul03** [comment]
I completely agree with you, @AudMonte01 .We already have 4 active organizers, and our community has grown to nearly 500 members. This team is currently well-equipped to manage our programs. 
However, we have a dedicated operations team within our community and have recently welcomed some active members, including @RafMo20D . 
We’ll ask @RafMo20D  to resubmit the request when our follower count increases. 
In the meantime, @RafMo20D can contribute as part of our operations team, and we truly value their efforts.

**Comment by AudMonte01** [comment]
Thank you for the speedy response and solution, @rajrahul03.

@RafMo20D - please let Rahul here know if you are interested in partaking on the operations team, and he can further let you know next steps.

**Comment by rajrahul03** [comment]
Hi @AudMonte01 ,

I will take this up with @RafMo20D further steps in adding in operations team. For the time being we can close this request.

Regards
Rahul Raj

**Comment by AudMonte01** [comment]
Excellent - thank you, @rajrahul03 . This issue/ticket is now closed.
