### ISSUE TITLE
[Organizer Request] Add Thiago as the co-organizer for CNCG Melbourne

### ISSUE THREAD

**Issue by thiago4go** [cncf/communitygroups#123]
### Name of chapter inquiring about

Cloud Native Melbourne

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

# Thiago S Shimada Ramos

I've been navigating the tech world for over a decade. My journey has taken me from Brazil to Japan and now Australia, exposing me to diverse perspectives and approaches to promoting inclusivity. I'm fascinated by the intersection of cloud computing and people. When I'm not immersed in Kubernetes (I'm a Certified Kubernetes Application Developer! ), you'll often find me playing Go.

- **Blog**: [https://thiago4go.github.io/](https://thiago4go.github.io/)
- **GitHub**: [https://github.com/thiago4go](https://github.com/thiago4go)
- **LinkedIn**: [https://www.linkedin.com/in/thiago4go/](https://www.linkedin.com/in/thiago4go/)

### Tell us why you want to be added or removed from the chapter

I, **Thiago S Shimada Ramos**, want to be added as Co-organiser of the CNCG Cloud Native Melbourne because I love open-source, sharing knowledge, and experiences on using Kubernetes. I have been helping to organize K8SUG in Melbourne for the past year, leading and growing the volunteer group. I have already spoken twice to the community with the talks: 

- "Navigating the Kubernetes Space: My Journey from WebDev to CKAD"
- "MLOps on Kubernetes: An Introduction to Kubeflow"

Additionally, I plan to conduct more hands-on workshops for the community, similar to what I have done with:

**"K8SUG CTL (Connect, Train, and Learn Kubernetes),"** a series of workshops where we'll dive deep into Kubernetes. This hands-on workshop will teach you how to deploy Large Language Models (LLMs) using Kubernetes. It is designed for anyone eager to gain practical experience and master the tools and techniques used by industry leaders.

I believe I can bring more people to this community.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by yongkanghe** [comment]
Thanks @thiago4go for your support! We are very lucky to have you join us. @AudMonte01 @k8tgreenley

**Comment by AudMonte01** [comment]
Thank you @thiago4go - it's great to see you have your CKAD, and are involved in Kubernetes trainings.

Please point me to your community.cncf.io profile so I may add you to this chapter.

**Comment by thiago4go** [comment]
Thanks @AudMonte01, here is the link https://community.cncf.io/cloud-native-melbourne/
I'm looking forward to this.

**Comment by thiago4go** [comment]
Thanks @AudMonte01, here is the link 
https://community.cncf.io/u/mnk9q8/
I'm looking forward to this.

**Comment by AudMonte01** [comment]
Thank you, @thiago4go - I have added you as an organizer to the chapter. You should have just received an automated welcome email from me with next steps.

This ticket is now closed.
