### ISSUE TITLE
[Organizer Request] Add Muuhh IKEDA as an Organizer

### ISSUE THREAD

**Issue by Muuhh-CTJ** [cncf/communitygroups#124]
### Name of chapter inquiring about

Cloud Native Security Japan

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Muuhh IKEDA
Cybertrust Japan Co. Ltd.
<munehiro.ikeda@cybertrust.co.jp>

### Tell us why you want to be added or removed from the chapter

Muuhh is a LF Japan Evangelists, whose speciality is security and main activity has been on OpenSSF.  Cloud Native Security Japan is another active community in Japan for sucurity topic.  I would like to bridge them so that OSS and OSS supplychain security can be improved much more.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by y-tabata** [comment]
@AudMonte01 
I'm an organizer of [Cloud Native Security Japan](https://community.cncf.io/cloud-native-security-japan/), and I accept this request.

**Comment by AudMonte01** [comment]
Thank you, @Muuhh-CTJ - please create an account on community.cncf.io and send me the email address associated with the account so I can properly add you to the chapter as an organizer.

**Comment by Muuhh-CTJ** [comment]
Thanks AudMonte01.
The associated address with community.cncf.io (CNCF) is munehiro.ikeda@miraclelinux.com
Appreciated it if you could deal with it.

**Comment by y-tabata** [comment]
@AudMonte01 
@Muuhh-CTJ  sent you his email address in the above comment.
I just mentioned you.

**Comment by AudMonte01** [comment]
Thank you, @Muuhh-CTJ - I have added you as an organizer to the chapter. You should have just received an automated welcome email from me.

Please also add a photo of yourself in your profile so I can make you as an organizer forward-facing on the chapter page.

I am closing this issue/ticket, but you can still comment here.

**Comment by Muuhh-CTJ** [comment]
Thank you @AudMonte01 !
I uploaded  a (weird) photo on CNCJ page for my profile.

**Comment by AudMonte01** [comment]
Thank you! I have now made you visible on the chapter page as an organizer, @Muuhh-CTJ.
