### ISSUE TITLE
[Organizer Request] Add Organizer Mathew Joseph

### ISSUE THREAD

**Issue by MathewJoseph1993** [cncf/communitygroups#125]
### Name of chapter inquiring about

Cloud Native London

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Name: Mathew Joseph
Mail: mathewjoseph1993@gmail.com
LinkedIn: https://www.linkedin.com/in/business-development-mathewjoseph/
GitHub: https://github.com/MathewJoseph1993
CNCF slack: U079AD3ENAK
Profile: https://community.cncf.io/u/mzs4vc/#/about

### Tell us why you want to be added or removed from the chapter

I am writing to express my interest in becoming an organizer for the Cloud Native London chapter. I have a strong background in cloud technologies and am deeply involved in the local London cloud communities. Here are the key reasons why I believe I would be a valuable addition to your team:

1. Experience and Expertise in Cloud Technologies
2. Active Participation in Local Cloud Communities
3. Commitment to Sharing CNCF Knowledge
4. Addressing the Current Gap in Event Organization
5. Vision for the Future

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Hi @MathewJoseph1993 - I am closing this ticket, since the intention is to open a new chapter here.
https://github.com/cncf/communitygroups/issues/128
