### ISSUE TITLE
[Organizer Request] Add Organizer Wojciech Kocjan

### ISSUE THREAD

**Issue by wojciechka** [cncf/communitygroups#127]
### Name of chapter inquiring about

Cloud Native Krakow

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Name: Wojciech Kocjan
Email: wojciech@kocjan.org
LinkedIn: https://www.linkedin.com/in/wkocjan/
GitHub: https://github.com/wojciechka
CNCF slack: Wojciech Kocjan
Profile: https://community.cncf.io/u/m938uq/

### Tell us why you want to be added or removed from the chapter

Help with co-organizing the Cloud Native Krakow chapter. I have over a decade of experience with cloud native technologies and am already involved with local communities and Cloud Native Krakow events.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by maci3jka** [comment]
:+1: Wojciech is long-running contributor to Kraków chapter.

**Comment by pawelpiwosz** [comment]
I confirm.

**Comment by maci3jka** [comment]
@AudMonte01 could you add Wojciech to our chapter?

**Comment by AudMonte01** [comment]
Thank you @maci3jka and @pawelpiwosz for confirming Wojciech's addition to the chapter. @wojciechka - you should have just received an automated welcome email from me with further steps.

This issue/ticket now closed.
