### ISSUE TITLE
[Group Request] Create a new chapter in Westminster, London

### ISSUE THREAD

**Issue by MathewJoseph1993** [cncf/communitygroups#128]
### City or location name for your CNCG

Cloud Native London

### What country do you want to start your community group in?

United Kingdom

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Name: Mathew Joseph
Mail: mathewjoseph1993@gmail.com
LinkedIn: https://www.linkedin.com/in/business-development-mathewjoseph/
GitHub: https://github.com/MathewJoseph1993
CNCF slack: U079AD3ENAK
Profile: https://community.cncf.io/u/mzs4vc/#/about 

### What is your mission statement or objective for this new chapter?

The mission of the CNCF London Chapter is to advance the adoption and development of cloud-native computing practices within the London tech community. We aim to create a vendor-neutral environment that fosters collaboration, innovation, and education among developers, end users, and vendors. By leveraging the collective expertise of our members, we strive to make cloud-native technologies ubiquitous, enabling organizations to build and run scalable, resilient, and manageable applications in modern, dynamic environments.

Objectives:
1. Promote Cloud-Native Technologies: Advocate for the use of cloud-native technologies such as Kubernetes, Prometheus, and Envoy to help organizations in London build and deploy applications more efficiently and effectively.
2. Foster Collaboration: Create a collaborative ecosystem where developers, IT professionals, and organizations can share knowledge, best practices, and innovations in cloud-native computing.
3. Educational Initiatives: Provide access to training, certification programs, and events like KubeCon + CloudNativeCon to help professionals stay up-to-date with the latest trends and advance their careers.
4. Community Building: Build a strong, inclusive community of cloud-native practitioners in London, encouraging contributions to open-source projects and participation in CNCF working groups and committees.
5. Support and Guidance: Offer resources and support to help organizations navigate their cloud-native journey, ensuring they can leverage the full potential of cloud-native technologies.

By achieving these objectives, the CNCF London Chapter will contribute to the broader mission of the Cloud Native Computing Foundation: to make cloud-native computing ubiquitous and accessible to all.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Thank you, @MathewJoseph1993 for your chapter inquiry.

Our team will review the request and be in touch. Please note, we do have a London chapter that we are working with in several ways:
- Reactivate their activity
- Renaming their chapter to more focused location since London has nearly 9 million people in it.

With this, do you have a specific borough/district in mind for your inquiring chapter?

**Comment by MathewJoseph1993** [comment]
Thank you for getting back to me so quickly @AudMonte01 and for the information provided about the existing London chapter.

I understand the importance of reactivating and renaming the current chapter to better serve the vast community within London.

Given the size and diversity of London, I believe focusing on a specific borough could indeed help in creating a more engaged and localized community. I would like to propose establishing the new CNCF chapter in the "City of Westminster". 

This borough is not only centrally located but also hosts a significant number of tech companies, startups, and educational institutions, making it an ideal hub for cloud-native enthusiasts and professionals.

The City of Westminster offers a vibrant and dynamic environment that can greatly benefit from dedicated cloud-native initiatives, fostering collaboration and innovation within this specific locale.

I look forward to your feedback and further guidance on how we can proceed with this proposal.

Best regards,

Mathew Joseph

**Comment by AudMonte01** [comment]
Thank you for the prompt response. We will deliberate and get back to you next week.

**Comment by MathewJoseph1993** [comment]
Thank you @AudMonte01  I look forward to it.

**Comment by AudMonte01** [comment]
Outside of sales and marketing, what is your cloud native experience @MathewJoseph1993?

**Comment by MathewJoseph1993** [comment]
Thank you for your message @AudMonte01 

While I don't have technical experience, I am actively involved in the CNCF community and passionate about cloud-native technologies.

I regularly participate in community events and have built a strong network of professionals in the field.

As an aspiring cloud-native advocate, I am eager to leverage my community connections to foster a vibrant CNCF chapter in the City of Westminster. 

I look forward to contributing to the community and promoting cloud-native adoption.

Best regards,
Mathew Joseph

**Comment by AudMonte01** [comment]
Please respond with this message in the GitHub issue for transparency .

Thank you,

Audra Montenegro
CNCF Community Program Manager
About Kubernetes Community Days <https://www.cncf.io/kcds/>
Host or join a local community group <https://community.cncf.io/>
US Time zone: Pacific Standard Time

**Comment by MathewJoseph1993** [comment]
Yes @AudMonte01 , I have done the same from the start. Not sure what did I miss.

**Comment by AudMonte01** [comment]
That is great! What events have you participated in, and in what capacity?

**Comment by AudMonte01** [comment]
That is great, @rohitg00 !

@MathewJoseph1993 - Rohit is a [CNCF Ambassador](https://www.cncf.io/people/ambassadors/?p=rohit-ghumare) who has a good track record of producing meetups and KCD Mumbai previously. We would highly encourage he be a co-organizer with you to get this chapter started.

**Comment by MathewJoseph1993** [comment]
Hi @AudMonte01 

I'm sorry for not getting back to you sooner, but I had some issues with notification settings.

As you asked about the event's participation, I have attended KCD events held in Kochi and Trivandrum (India). I have attended them as a participant.

Hi @rohitg00  that sounds exciting and I am looking forward to the colabration.

@AudMonte01  I would be really happy to work with @rohitg00 as a co-organizer for the Cloud Native London, Westminster Chapter.

I am excited and looking forward to make it happen.

**Comment by AudMonte01** [comment]
That is excellent news! I have created the chapter and added you both as co-organizers. You should have just received automated welcome emails from me with further instructions.

Please proceed @rohitg00 in creating that Sustainability week event. But first, there will need to be a description for the chapter, and then click the "hide" toggle so it is off, and can be found on the front-end of community.cncf.io.

This ticket/issue is now closed.
