### ISSUE TITLE
[Organizer Request] Add Organizer Rishabh Beniwal to Delhi chapter

### ISSUE THREAD

**Issue by rishabhbeni** [cncf/communitygroups#129]
### Name of chapter inquiring about

CNCF Delhi

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

I am a CKAD certified professional with 7 years of experience ranging from Web Development, Graphic Design, Technical Support, Training & Consulting, Cloud & DevOps. I am currently working as a Senior Systems Engineer at EPAM for a Data DevOps project. Here is the link to my GitHub & Linkedin URL:
github.com/rishabhbeni
linkedin.com/in/rishabhbeniwal

I am not registered on CNCF community & need to be invited

### Tell us why you want to be added or removed from the chapter

I have experience in delivering workshops & organizing events. I would like to contribute to the CNCF community & my expertise in Kubernetes & DevOps could be really valuable to the young professionals

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you for your interest in co-organizing the New Delhi chapter. It does have many organizers already, but some have gone and new of joined through proof of commitment and volunteering. Let me add one of the organizers to comment here on the best way you can participate if you are not already a member?

https://community.cncf.io/new-delhi/

Cc @satyampsoni

**Comment by satyampsoni** [comment]
Hi @rishabhbeni 

Thank you for your interest in becoming an organizer! We truly appreciate your enthusiasm. Our chapter has been active for a year now, and we have established some guidelines for those looking to take on an organizing role.

To be considered for this position, we kindly ask that you volunteer with us for at least six months. This timeframe will help demonstrate your commitment and consistency within our community. For reference, one of our current organizers, @KrishAryan ,  started this way as well.

If you're interested in volunteering, please fill out our volunteer application form. We would be delighted to have you on board as a volunteer!
 https://forms.gle/K48LQp5LwRGpEph96

**Comment by AudMonte01** [comment]
Thank you, @satyampsoni !

I will now close this ticket/issue.

**Comment by rishabhbeni** [comment]
Thank you @AudMonte01 @satyampsoni for giving me the opportunity. Would love to start contributing as a volunteer 👍
