### ISSUE TITLE
KubeScale Summit

### ISSUE THREAD

**Issue by adi13jain** [cncf/communitygroups#130]
### City or location name for your CNCG

Gurgaon

### What country do you want to start your community group in?

India

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Aditya Jain, https://www.linkedin.com/in/aditya-jain-818104129/, CNCF :https://community.cncf.io/u/m4vu9e/#/about, https://github.com/adi13jain, Company: Expedia Group, Email id: adi.13.jain@gmail.com

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Shivani Mehrotra, https://www.linkedin.com/in/shivanimehrotra/, CNCF: https://community.cncf.io/u/m9pgzm/#/about, Company: Expedia Group, Email Id: shivanimehrotra.sm@gmail.com

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Shreya Kansal, https://www.linkedin.com/in/shreyakansal12, CNCF: https://community.cncf.io/u/mg8t2v/#/about, Company: Expedia Group, Email Id: shreya.kansal13@gmai.com

### What is your mission statement or objective for this new chapter?

Our mission is to explore, share, and innovate on the frontiers of Kubernetes scalability. We aim to bring together a vibrant community of cloud-native enthusiasts and thought leaders to emphasize scalable solutions, support diversity, and empower the next generation through mentorship and training.
Our goal is to foster a network where members harness the full potential of Kubernetes in large-scale production environments, creating an ecosystem of collaboration, learning, and continuous improvement.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by adi13jain** [comment]
@AudMonte01 thank you for reverting. The plan of action is to cover topics which are related to kubernetes and since Expedia has a high scale of infrastructure which we have leveraged and want to share the journey around it, hjow we have managed, deployed and scaled the infrastructure successfully.

New Name could be 
CloudNative NewDelhi - KubeScale Summit

Please let us know if we can move forward with it and what should be our next plan of action.

**Comment by AudMonte01** [comment]
Thank you for your reply, @adi13jain 

Please note, this repository and these issues/tickets, are to either create a community group chapter in a city, with a cadence of meetups at least once every 90 days.

Seeing that you mentioned New Delhi, we do already have a [New Delhi chapter](https://community.cncf.io/new-delhi/), if you would like to attend their next meetup and propose helping them one meetup where you can help curate content?

**Comment by satyampsoni** [comment]
Hi @adi13jain

Thank you for your interest in becoming an organizer! We truly appreciate your enthusiasm. Our chapter has been active for a year now, and we have established some guidelines for those looking to take on an organizing role.

To be considered for this position, we kindly ask that you volunteer with us for at least six months. This timeframe will help demonstrate your commitment and consistency within our community. For reference, one of our current organizers, @KrishAryan , started this way as well.

If you're interested in volunteering, please fill out our volunteer application form. We would be delighted to have you on board as a volunteer!
https://forms.gle/K48LQp5LwRGpEph96

However, if you wish to discuss more, please feel free to DM me at Linkedin https://www.linkedin.com/in/satyampsoni

**Comment by AudMonte01** [comment]
Thank you, @satyampsoni for this communication. I will now close this issue.
