### ISSUE TITLE
[Organizer Request] Add Anish Bista to KATHMANDU chapter

### ISSUE THREAD

**Issue by anishbista60** [cncf/communitygroups#132]
### Name of chapter inquiring about
`
CNCF KATHMANDU
`
### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

An passionate student about Cloudnative, Devops and opensource particularly in k8s ☸. I’m dedicated to applying my skills to innovate and streamline software development processes. With hands-on experience in container orchestration and cloud-native technologies, I’m eager to contribute to projects that embrace modern DevOps practices. Currently contributing to kubevirt which is incubating CNCF project . My expertise lies in k8s and Go.

Name: Anish Bista 
Email: anishbista053@gmail.com
Github: https://github.com/anishbista60
Linkedln: https://www.linkedin.com/in/anish-bista-666a6628a/

### Tell us why you want to be added or removed from the chapter

I would like to join as the Co-organizer of CNCF Kathmandu on the recommendation of ` CNCF Kathmandu Lead `  because of following reasons : 

- **Passionate about Cloud Native Technologies:** Aligns perfectly with my interests and expertise.
- **Knowledge Sharing:** Aims to help others learn and grow in cloud-native technologies.
- **Networking Opportunities:** Allows networking with professionals and experts in the industry.
- **Support Local Community:** Dedicated to growing the local cloud-native community in Kathmandu.
- **Encouraging Open Source Contributions:** Inspires others to contribute to open source projects.
- **Leadership Role:** Enables planning and executing community events effectively.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Hello @anishbista60 - thank you for submitting this request.

it looks like you have already been a speaker for this chapter, and are labeling yourself as a co-organizer on LinkedIn. That said, let me copy  the current organizer, @RashikaKarkito to have her confirm you should join as a co-organizer, or if there are other steps she wishes you take ahead.

**Comment by anishbista60** [comment]
yeah , Sure . You can cross verify that. Current organizer @Rashika Karki
told us to request for Co-organizer.

**Comment by anishbista60** [comment]
@AudMonte01 Does cncf kathmandu organizer `Rashika karki` need to comment here for confirmation ?

**Comment by AudMonte01** [comment]
Yes, @anishbista60

**Comment by RashikaKarki** [comment]
Hey @AudMonte01 ,
I can confirm and excited to have him onboard as co-organizer.

**Comment by AudMonte01** [comment]
Thank you for confirming, @RashikaKarki .

@anishbista60 - I have added you as a co-organizer in the meantime, but you will not yet be visible on the front-end of the chapter until you update your forward-facing profile.
* You should have received an automated welcome email from me with next steps. One being to please add a profile image to your community.cncf.io account.

**Comment by anishbista60** [comment]
@AudMonte01 Updated could you please take a look ?  Thank you.

**Comment by AudMonte01** [comment]
I see both updated for each of you - thanks so much! I have made you visible on [the chapter page](https://community.cncf.io/cloud-native-kathmandu/) as organizers.

Next Step: Please follow the instruction regarding the CNCF Slack workspace, in my welcome email.

This issue/ticket is now closed.
