### ISSUE TITLE
[Organizer Request] Add Ryu Ishimoto to Cloud Native Community Japan to organize Wasm Meetups in Japan

### ISSUE THREAD

**Issue by ryu25ish** [cncf/communitygroups#133]
### Name of chapter inquiring about

Cloud Native Community Japan

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Ryu Ishimoto

CNCF: https://community.cncf.io/u/mwzmn2/#/about
LinkedIn: https://www.linkedin.com/in/ryu25/
Slack: _Ryu Ishimoto_ in CNCF workspace

### Tell us why you want to be added or removed from the chapter

I would like to be the organizer for Wasm Meetups in Japan in order to raise awareness of, increase interest in, and create opportunities for everyone to learn more about Wasm.   I have been working to build the ecosystem of Wasm for several years, and my company has been one of the early adopters of the technology that actually uses it in production.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by yuichi-nakamura** [comment]
He is is an organizer of Cloud Native Community Japan who leads WASM meetups, please add.

**Comment by AudMonte01** [comment]
Thank you, @ryu25ish for this submission. And thank you @yuichi-nakamura for confirming his addition. I have added Ryu to the chapter as an organizer, so he should have received an automated welcome email from me. Please let me know if he needs an invitation to the CNCF Slack workspace.

This issue/ticket is now closed.
