### ISSUE TITLE
[Organizer Request] Add Pradnyan Thakare as Co-Organizer to Jalgaon Chapter

### ISSUE THREAD

**Issue by Thakarepradnyan** [cncf/communitygroups#136]
### Name of chapter inquiring about

Cloud Native Jalgaon

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Pradnyan Thakare, 

Student at Shri. Sant Gadgebaba College of Engineering and Technology, Bhusawal, Maharashtra, India.

email - pradnyanthakare1943@gmail.com
github - [github.com/Thakarepradnyan](url)
linkedin - [linkedin.com/in/pradnyanthakare](url)
x(twitter) - [x.com/PradnyanThakare](url)
lfx - [openprofile.dev/profile/pradnyanthakare19](url)
CNCF Community - [community.cncf.io/u/m5u67u/#/about](url)

### Tell us why you want to be added or removed from the chapter

I, 
Pradnyan Thakare, 
Wants to join as a co-organizer for the CNCF Jalgaon community group. Jalgaon has potential for growth in the cloud domains, and this group aims to nurture that potential by providing a supportive platform for contributions to CNCF and other open-source initiatives.

As a co-organizer, I am committed to organizing events, workshops, and meetups to raise awareness and engagement. My goal is to build a strong community that actively participates in and contributes to the cloud-native ecosystem. By leveraging my passion and experience, I hope to create a hub for innovation and collaboration in the region, providing guidance and support to students as they explore and develop their skills in this exciting field.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you, @Thakarepradnyan for your inquiry, as it seems Utkarsh could use some help getting started.

I am copying him here for further approval or review of you being an additional co-organizer.
Cc @UtkarshUmre

**Comment by UtkarshUmre** [comment]
Pradnyan has been really helpful with the community group, so could you please add him as a co-organizer for CNCF Jalgaon? 
Thank you!

**Comment by AudMonte01** [comment]
Can you elaborate in what ways? From what I can tell, you have not yet hosted one meetup. [The chapter](https://community.cncf.io/accounts/dashboard/#/chapter-667/settings/general/) still lacks a description so it can be un-hidden and found on community.cncf.io.

**Comment by UtkarshUmre** [comment]
Absolutely! He’s a university student in my area, which gives him great access to people who want to learn more about CNCF. He’s helping bring them into the community by encouraging them to join the Discord server and coordinating with management for in-person talks. We’re also organizing our first virtual meetup, expecting a few attendees since this is a new community group. He’s been really helpful in that, and we’re working together to make it happen.
