### ISSUE TITLE
[Organizer Request] Add Javier Martínez

### ISSUE THREAD

**Issue by exorcito** [cncf/communitygroups#137]
### Name of chapter inquiring about

Cloud Native Galicia

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Name: Javier Martínez
Email: [javidevigo@gmail.com](mailto:javidevigo@gmail.com)
CNCF Profile: https://community.cncf.io/u/mbakt8/
Website: https://sites.google.com/site/jmtorresvigo/
LinkedIn: https://www.linkedin.com/in/javier-mart%C3%ADnez-torres-80a26834/

### Tell us why you want to be added or removed from the chapter

I would like to add Javier as the Co-organizer of CNCF Cloud Native Galicia for the following reasons:

Passionate About Cloud Native Technologies: This aligns perfectly with the interests and expertise of the group, particularly in the field of AI. As a professor and former Director of AI at a multinational company, he uses cloud-native technologies in his daily work.

Knowledge Sharing: He aims to help others learn and grow in cloud-native technologies.

Networking Opportunities: This role will allow him to network with professionals and experts in the industry.

Support Local Community: He is dedicated to growing the local cloud-native community in Kathmandu.

Encouraging Open Source Contributions: He wishes to inspire others to contribute to open-source projects.

Leadership Role: He is excited about planning and executing community events effectively.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you, @exorcito - please have Javier comment here with agreement to the above terms.

**Comment by skippyvigo** [comment]
I agree

**Comment by AudMonte01** [comment]
Thank you, @skippyvigo - you should be receiving an atuomated welcome email from me shortly. Please follow next steps there. This issue/ticket is now closed.
