### ISSUE TITLE
[Group Request] Create a new chapter in Belgium

### ISSUE THREAD

**Issue by mauromorales** [cncf/communitygroups#138]
### City or location name for your CNCG

Belgium

### What country do you want to start your community group in?

Belgium

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Mauro Morales, contact@mauromorales.com, Spectro Cloud, https://github.com/mauromorales, https://www.linkedin.com/in/mauromorales/, Mauro Morales on Slack, https://community.cncf.io/u/mnpcn4/#/about

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Christopher Peeters, cp@linux.com, Lecroq, https://github.com/cpeetersburg/, https://www.linkedin.com/in/christopherpeeters/, Christopher Peeters

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Jean-Philippe Evrard, open-source@a.spamming.party, TLaaS, https://github.com/evrardjp, https://www.linkedin.com/in/evrardjp, Jean-Philippe Evrard, https://community.cncf.io/u/mgzk7k/#/about

### If you already run a meetup, please link it here

not yet, we have scheduled our first meetup for September 6th 2024. In the meantime you can join us in the #belgium channel of the cncf slack https://cloud-native.slack.com/archives/C016M1MM5AS

### What is your mission statement or objective for this new chapter?

Our mission is to foster a vibrant community in Belgium passionate about cloud-native technologies, including microservices, containers, and the ecosystems that support them. We welcome enthusiasts of all skill levels to join us in exploring, learning, and advancing Kubernetes and other CNCF projects. Together, we aim to create an open and inclusive environment where everyone can share knowledge, collaborate on innovative solutions, and grow as cloud-native practitioners.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Thank you, @mauromorales for your interest in hosting a chapter in Belgium!

We run community groups on a city basis. Sometimes state-level, if the cities are not well known, but in this case, we ask the organizers to be willing to change their chapter name in the case of more people becoming interested in hosting a chapter in their own city.

That said, what city (or area) would this team be interested in hosting a chapter in?

**Comment by mauromorales** [comment]
Hi @AudMonte01 thanks for getting back to me. Hmm good question, ideally we are planning to rotate cities, this is a common practice here in Belgium for small groups. Same reason why we would do it in English, since different regions have different languages 😅 

If that is not a possible, let's put Brussels, since that's the city where we will have our first meeting (and it's officially bilingual 🤣) and if necessary, we can change it in the future.

**Comment by AudMonte01** [comment]
Excellent - that Brussels makes the most sense.

We have a dormant group that has not hosted anything with us since 2020, but they are active on meetup.com. Are you by chance connected with this group? https://www.meetup.com/kubernetes-belgium/

**Comment by mauromorales** [comment]
@AudMonte01 I saw this group but assumed it was not CNCF associated since they don't seem to be meeting at least once every three months. But let me reach out to them and get more info from them

**Comment by AudMonte01** [comment]
Any luck @mauromorales. If not, we can proceed with this chapter creation, as we have not seen activity on either meetup.com or community.cncf.io.

With that, we just need @cpeetersburg and @evrardjp to comment in this issue agreeing to the above terms, and confirming they have completed the above-listed open and inclusive free online course.

Thank you,
Audra Montenegro

**Comment by mauromorales** [comment]
@AudMonte01 no, I tried to reach via LinkedIn but unfortunately no response. Thanks!

**Comment by cpeetersburg** [comment]
I've completed the course and I agree with the terms above.

**Comment by evrardjp** [comment]
I confirm what's said above. I contacted the previous meetup group too.

**Comment by AudMonte01** [comment]
Thank you for contacting the previous organizers - I appreciate you trying, which sometimes is all that can be done. We will move forward with you three as the new organizers.

But first, please send me a link to your earned badges of completion for the above open and inclusive course.

**Comment by AudMonte01** [comment]
EXCELLENT - THANK YOU! You each have been added as chapter organizers to the Cloud Native Brussels. You should have just received automated welcome emails from me with next steps under the CNCG or Community Group heading.

@evrardjp - please add a headshot of yourself in [your profile](https://community.cncf.io/u/mgzk7k/#/about) and then I can make you forward-facing on the chapter page.

This issue/ticket is now closed.

**Comment by mauromorales** [comment]
Thanks @AudMonte01

**Comment by evrardjp** [comment]
@AudMonte01 I updated my profile with a picture. You can now add me on the chapter.

**Comment by AudMonte01** [comment]
Excellent - thank you. You will now show up on the front-end of the chapter once the description is updated and the chapter "hidden" box is un-ticked.
