### ISSUE TITLE
Cloud Native Telecom India North

### ISSUE THREAD

**Issue by viprat** [cncf/communitygroups#140]
### City or location name for your CNCG

North India

### What country do you want to start your community group in?

India

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Vipin Rathi, vipin.rathi@ramanujan.du.ac.in, University of Delhi, https://github.com/viprat, https://www.linkedin.com/in/vipratos/,  Vipin Rathi, https://community.cncf.io/u/mc2c4m/#/about

### If you already run a meetup, please link it here

https://www.meetup.com/cloud-native-security-india/

### What is your mission statement or objective for this new chapter?

I have been organizing various Linux Foundation project meetups for the last 10 years. We are getting a lot of requests for meetups specific to the Cloud Native telecom domain. That is why we want to start a specific group for Cloud Native Telecom

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by viprat** [comment]
@AudMonte01

**Comment by AudMonte01** [comment]
@k8tgreenley - while this is a general location and we typically advise CNCGs are on a city level, this is a niche topic area. Please add any concerns here, or affirm we can proceed.

**Comment by k8tgreenley** [comment]
Please provide a city

**Comment by viprat** [comment]
North India(Delhi, Noida, Gurugram, Chandigarh, Jaipur etc.)

**Comment by AudMonte01** [comment]
Thank you for this submission. After further internal discussion, given your participation across different Indian chapters and so forth, we think this should be a virtual group tied back to a TAG. That said, this should not even designated as a country-specific chapter, but would be better served as a larger topic that extends past India. The benefit would be joining as a project group which can secure placement on the [CNCF community meetings calendar](https://www.cncf.io/calendar/). Let me know your thoughts @viprat

**Comment by viprat** [comment]
@AudMonte01 I think this is even better idea.

**Comment by AudMonte01** [comment]
That's great! Please follow the link in the upper right corner of community.cncf.io to apply for a project group. I will now close this ticket/issue.
