### ISSUE TITLE
[Organizer Request] Add Christopher Tineo to Santo Domingo chapter

### ISSUE THREAD

**Issue by TineoC** [cncf/communitygroups#142]
### Name of chapter inquiring about

Cloud Native Santo Domingo

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Christopher Tineo, christophertineo02@gmail.com, Banreservas, TineoC, https://www.linkedin.com/in/christopher-tineo, Christopher Tineo, https://community.cncf.io/u/mrekmd/

### Tell us why you want to be added or removed from the chapter

I want to join the CNCF Chapter of Santo Domingo because I have been actively involved for almost a year and have closely collaborated with our leader, Victor Recio. Seeing the need for motivated individuals to develop local communities, I am committed to organizing the KCD Dominican Republic next year and contributing my efforts and knowledge to keep this community vibrant by organizing monthly events and talks.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by TineoC** [comment]
![image](https://github.com/user-attachments/assets/e7af1c20-c465-4cdd-8c8f-bc547ead363b)

Together with Victor Recio, we organized a Docker Workshop at the INTEC university in Santo Domingo.

**Comment by TineoC** [comment]
![image](https://github.com/user-attachments/assets/d3af083a-df0c-4e6a-a227-1f817fbb7390)

**Comment by TineoC** [comment]
@AudMonte01

**Comment by AudMonte01** [comment]
Thank you for your inquiry to join the Santo Domingo chapter in the Dominican Republic as a co-organizer.

I am copying the current organizers @vsrecio and @angelmejiabrito to let you know the best way to get started, if you have not already consistent attended their meetups, or have yet to speak at one of them.

Please loop in Jorge Ortega, as I do not have his GitHub handle.

**Comment by jorgeortegap** [comment]
Hi @AudMonte01 , @TineoC just looped me in, I confirm Christopher is one of our new admins and is doing a great job bringing a younger but eager to learn generation into the chapter; this being the case, please approve his request to become an admin. Thanks in advance!

**Comment by AudMonte01** [comment]
Excellent - thank you for confirming, @jorgeortegap . I have added you, @TineoC as a co-organizer to the chapter. You should have just received an automated welcome email from me with further instruction. I have also introduced you in the community organizer channel. Welcome!

This issue/ticket is now closed.
