### ISSUE TITLE
[Group Request] Create a new chapter in Aachen, Germany

### ISSUE THREAD

**Issue by embik** [cncf/communitygroups#144]
### City or location name for your CNCG

Aachen

### What country do you want to start your community group in?

Germany

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Marvin Beckers
E-Mail: mail@embik.me
Company: Kubermatic
GitHub:  https://github.com/embik
LinkedIn: https://www.linkedin.com/in/marvinbeckers/
CNCF Slack: MarvinBeckers
CNCF Community: https://community.cncf.io/u/m87uac/

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Clemens Röhl
E-Mail: roehl.clemens@gmail.com
Company: CANCOM
GitHub: https://github.com/roehlc
LinkedIn: https://www.linkedin.com/in/clemens-roehl/
CNCF Slack: roehlc
CNCF Community: https://community.cncf.io/u/mcejn5/

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Sebastian Rabenhorst
E-Mail: Sebastian.rabenhorst@shopify.com
Company: Shopify
GitHub: https://github.com/rabenhorst
LinkedIn: https://www.linkedin.com/in/sebastian-rabenhorst-a09336183/
CNCF Slack: Sebastian Rabenhorst
CNCF Community: https://community.cncf.io/u/m2667w/

### If you already run a meetup, please link it here

https://www.meetup.com/de-DE/kubernetes-cloud-native-aachen/

### What is your mission statement or objective for this new chapter?

All of us have been working in the Cloud Native ecosystem for several years at this point and we have been missing the community aspect of it on a local level. Because of that, we wanted to provide a new space in Aachen for Cloud Native professionals and enthusiasts to exchange ideas, learn about new topics, meet each other, and share drinks and food. We hope to build a local network that drives Cloud Native adoption in the cross-border EUREGIO region (Germany, Netherlands, Belgium) around Aachen.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by embik** [comment]
Note: We previously applied for this on 3/8/2024 12:21:23, but it took us a while to open this request through the new process.

**Comment by roehlc** [comment]
I'm confirming that I'm a co-organizer.

**Comment by AudMonte01** [comment]
Thank you for submitting this request. Please confirm, @rabenhorst and @roehl that you agree to the above terms, including having taken the free, inclusive online course through Linux Foundation training?

Also, do any of you know the previous organizers, Michael Rath or Moritz Kröger?

**Comment by embik** [comment]
Honestly, we weren't aware that there was a previous group in Aachen (I don't know Moritz or Michael either, but maybe the others do). I looked at it on archive.org and it appears to have been a study group associated with RWTH (the local university), not sure what exactly the backstory for it is.

We'd be happy to get in touch with them and see if they are interested in participating of course.

**Comment by AudMonte01** [comment]
April 2022 was their last meetup on community.cncf.io. They only have 31 members in the archived chapter, but it's a start!

Those organizer were non-responsive in an email outreach on February 1 of 2023, so they will have to reapply anyway.

That said, I have added each of you as organizers to the revitalized chapter. You should have received automated email from me with next steps.

@roehlc & @rabenhorst - your profiles will not yet show up since you do not have a profile pictures. Please let me know once you have added one to your community account: https://community.cncf.io/u/mcejn5/

**Comment by rabenhorst** [comment]
@AudMonte01 I updated my profile with a picture, agree with the above terms and took the course. Thx!

**Comment by roehlc** [comment]
@AudMonte01 I have also updated my profile with a picture, agree to the terms outlined above, and completed the course two weeks ago.

Thank you for your time and effort.

**Comment by AudMonte01** [comment]
Excellent - everyone is now visible on the chapter. Please follow the instruction in the chapter description and unhide the chapter when you feel it is ready.

I have also introduced the three of you in the global organizer channel which is a great place to gather insights from other organizers inn Europe.

This ticket / issue is now closed.
