### ISSUE TITLE
[Organizer Request] Add Enmanuel Medina to Santo Domingo chapter

### ISSUE THREAD

**Issue by en-medina** [cncf/communitygroups#145]
### Name of chapter inquiring about

Cloud Native Santo Domingo

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Enmanuel Medina, em.enmanuelmarcial@gmail.com, Independent, https://www.linkedin.com/in/enmedina3/, Enmanuel Medina, https://community.cncf.io/u/m2jemv/

### Tell us why you want to be added or removed from the chapter

I am eager to join the CNCF Chapter of Santo Domingo as I collaborate with Victor Recio, the community leader to expand cloud-native knowledge in the Dominican Republic. I am committed to organizing the KCD Dominican Republic next year and look forward to contributing to the growth of our local tech community

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Hello @en-medina - I am looping in the current organizers to review your application and reply with next steps they want you to take to become an organizer.

Cc @TineoC, @vsrecio, and @angelmejiabrito to approve adding you as a co-organizer (I cannot find Jorge Ortega's GitHub handle).

**Comment by jorgeortegap** [comment]
Hi @AudMonte01 ; @en-medina is our latest co-organizer joining the group and he's been of great assistance for our community growth, His ideas, roadmap planning and technical skills regarding cloud native technologies has been really helpful to bring more members into the community. This being the case, please approve this request so Enmanuel can join as a co-organizer. This completes our team, and no more co-organizers will be needed in the near future.

**Comment by AudMonte01** [comment]
Excellent - thank you, @jorgeortegap. I have added @en-medina as a co-organizer. You should have just received an automated welcome email from me with next steps. One of which should be that you add a profile picture of yourself on you community.cncf.io profile so I can make you as an organizer forward-facing on the chapter page. Please confirm when this is complete.

**Comment by en-medina** [comment]
Awesome, thanks @AudMonte01 for the assistance, I have updated my community.cncf.io profile.

**Comment by AudMonte01** [comment]
Thank you - I have made you visible on the [front-end of the chapter](https://community.cncf.io/cloud-native-santo-domingo/) as an organizer.

Please reach out to me [on Slack](https://cloud-native.slack.com/team/U03LC4KAGSC) so I can introduce and welcome your correct CNCF Slack Workspace profile in the organizer Slack channel.

This ticket/issue is now closed.
