### ISSUE TITLE
[Organizer Request] Add 2 Organizers to the Santiago, Chile chapter

### ISSUE THREAD

**Issue by scanalesespinoza** [cncf/communitygroups#146]
### Name of chapter inquiring about

Cloud Native Santiago

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

**Add organizer 1:**
- Name: Sergio Canales
- Email: sergio.canales.e@gmail.com
- Company: Red Hat Inc.
- Country: Chile

My profile and content:
- https://community.cncf.io/u/mnpjgs/#/about
- https://www.linkedin.com/in/sergio-canales-espinoza/
- https://openprofile.dev/profile/SergioCanales
- https://ortelius.io/governing-board/
- https://www.linkedin.com/groups/13025146/
- Discord Server: https://discord.gg/3eawzc9ybc
- https://github.com/scanalesespinoza
- https://youtu.be/3-qy8smcHsU
- https://www.tiktok.com/@sergio.sce/video/7403186008897965317?is_from_webapp=1&sender_device=pc&web_id=7349961311701468678
- https://community.cncf.io/events/details/cncf-santiago-presents-sesion-en-linea-cloud-native-beyond-the-platform-engineering-and-devex/cohost-santiago
- https://youtu.be/OrzIPLiol5Y
- https://medium.com/@sergio-canales-e
- KCD Buenos Aires 2024 Speaker
- KCD Lima 2024 Speaker
- https://sessionize.com/sergio-canales
- https://x.com/Iarwain_BenAdar

**Add organizer 2:**
- Name: Tomás Olivares
- Email: tomas@andesdigital.com
- Company: Andes Digital
- Country: Chile

My profile and content:
- https://community.cncf.io/u/mcquqf/
- https://www.linkedin.com/in/tomasolivares/
- https://github.com/choclo
- https://x.com/tolivaresv
- https://x.com/tolivaresv/status/1716717311275540575
- https://openforumeurope.org/event/open-source-driving-the-european-digital-decade-spain/

### Tell us why you want to be added or removed from the chapter

Hello! We are working with the Santiago Chapter organizer and want to work closer to improve the amount of activities and support the growth of the community in Santiago.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by scanalesespinoza** [comment]
Hello, any updates?

**Comment by AudMonte01** [comment]
Thank you for your submissions @scanalesespinoza - I am reaching out to the current organizers to at least have a majority vote of adding you and Tomás as co-organizers to the chapter.

I also want to highlight an opportunity you mentioned to me on Slack which is that Sergio is presenting and participating at [DevNation Chile](https://developers.redhat.com/devnation/dnd) as link to the communities. It would be cool to participate as a Santiago Chapter. He can ask to have a stand for example.

**Comment by scanalesespinoza** [comment]
I have confirmation for Santiago Chapter having a stand and 1 session in the event agenda :)
Also the event is public now: https://developers.redhat.com/devnation/devnation-day-santiago-2024

**Comment by AudMonte01** [comment]
Hello @scanalesespinoza - I have not yet heard back from the organizers, and I do not have their GitHub handles. I just followed up with them today (in Spanish). Thank you for your patience.

**Comment by pesquerra** [comment]
On behalf of the team, I apologize for the delay. Communication has been a bit slow due to the holidays and ongoing work. As the current organizers of the Santiago Chapter, we’ve discussed and are all in agreement to add Sergio Canales as a co-organizer at this time. Since he joined one of the WhatsApp groups, he has been motivated, active, and fully involved in all activities, making a great contribution.

As for Tomás Olivares, we would like to wait a bit and give him more time to become more active and participatory in future activities. Although he is also part of the same WhatsApp group, he has remained quiet so far.

**Comment by AudMonte01** [comment]
Thank you, @pesquerra - this makes sense to me.

With that, I have added the @scanalesespinoza as a co-organizer to the chapter. Sergio - you should have just received an automated welcome email from me with further instructions. While you are added to the chapter, you will not show up on the front-end of the chapter page until you add a profile picture to [your account](https://community.cncf.io/u/mnpjgs/#/about). Please let me know once you have done so.

This issue/ticket is now closed.
