### ISSUE TITLE
[Organizer Request] Add or Remove Organizer Name Julia Furst Morgado

### ISSUE THREAD

**Issue by abebars** [cncf/communitygroups#147]
### Name of chapter inquiring about

Cloud Native Midtown

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Adding Julia Furst Morgado, Global Technologist, Veeam, [juliafmorgado@gmail.com](mailto:juliafmorgado@gmail.com), Julia Furst Morgado

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you, @abebars. @juliafmorgado, please affirm you agree with the above terms, and we can move forward with adding you to the chapter as a co-organizer. Thank you.

**Comment by juliafmorgado** [comment]
Hi @AudMonte01 yes I agree to the terms. Thanks

**Comment by AudMonte01** [comment]
Thank you, @juliafmorgado - you have now been added as an organizer to the chapter. You should have just received an automated welcome email from me. Most of the instruction is already complete on your end although I just added you and the team to the CNCG organizer channel.

This issue is now closed.
