### ISSUE TITLE
[Group Request] Create a new chapter in Stuttgart, Germany

### ISSUE THREAD

**Issue by danijel-soldo** [cncf/communitygroups#149]
### City or location name for your CNCG

Cloud Native Stuttgart

### What country do you want to start your community group in?

Germany

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Danijel Soldo, Red Hat, Solution Architect, https://github.com/danijel-soldo, https://www.linkedin.com/in/danijel-soldo/, CNCF Slack: Danijel Soldo, https://community.cncf.io/u/mrkhgw/#/about

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Jens Schwarzer, IBM, Brand Technical Specialist, https://github.com/jusxman, https://www.linkedin.com/in/jschwarzer/, Slack: Jens Schwarzer,  https://community.cncf.io/u/m6snbk/#/about

### If you already run a meetup, please link it here

n/a

### What is your mission statement or objective for this new chapter?

We want to become the catalyst for open exchange of cloud native topics in Stuttgart all around Kubernetes, Open Source, GitOps, Edge - you name it.  
Besides, we're a dynamic community where Open Source innovation meets sustainability. Our group is all about bringing together passionate individuals who are excited to explore the intersection of Open Source software and sustainable, green coding practices. Whether you're a seasoned developer or just starting out, join us to exchange ideas, share experiences, and collaborate on projects that drive positive change.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [ ] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by danijel-soldo** [comment]
@stefan-bergstein FYI

**Comment by AudMonte01** [comment]
Hello @danijel-soldo - thank you for submitting this request to host a chapter. One concern here is that each organizer is from the same company. I see you checked the box "I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies", so I unchecked it for you.

That said, to assure vendor neutrality, please either:
* add 3 more organizers from another company
* remove 1 organizer and add 2 from another company
* remove 2 organizers and add 1 from another company

**Comment by danijel-soldo** [comment]
Hello @AudMonte01 , thanks for the feedback. 
I removed the 2 organizers from Red Hat and added Jens Schwarzer from IBM as co-organizer. 
I hope this is fine to move to the next phase here. We would definitely love to get started with the event page for the sustainability week. 

Thanks for your support ;) 
Danijel

**Comment by AudMonte01** [comment]
Excellent - @jusxman, please comment here that you agree to all of the above organizer terms.

@danijel-soldo - I have re-enabled the chapter (only had 1 member), and added you as an organizer to get started. You should be receiving an automated welcome email from me momentarily.
