### ISSUE TITLE
[Organizer Request] Add Krish Aryan to New Delhi chapter

### ISSUE THREAD

**Issue by KrishAryan** [cncf/communitygroups#154]
### Name of chapter inquiring about

Cloud Native Community Group New Delhi

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Krish Aryan, krisharyan.36@gmail.com, Webnish Software LLP,  https://github.com/KrishAryan, https://www.linkedin.com/in/krisharyan3612/, Krish Aryan in CNCF Slack, https://community.cncf.io/u/m2ge9n/#/about

### Tell us why you want to be added or removed from the chapter

I, Krish Aryan would like to join as an organizer at CNCG New Delhi. I have known about CNCF for more than 3 years, attended numerous CNCF events like Kubecon(virtually),KCDs and CNCG events, contributed to various CNCF projects, became a GSoC mentee at CNCF (Kubearmor), gave multiple talks about CNCF and its projects, achieved certifications like KCNA, CKA and CKAD (and on the path of becoming Kubestronaut) and contributed to [eight](https://docs.google.com/document/d/12tzgYhu_52MXdRnWN4Smku446ilqhkSjrV8hKPve8xk/edit) CNCG New Delhi events as a volunteer. During my journey I learnt many things and met many people which helped me grow my skills and network immensely. I want to help do the same for other people in my city.

CC: @AudMonte01 @akumar-99 @Abhinav-26 @satyampsoni

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by satyampsoni** [comment]
+1

Krish has been consistently contributing to the CNCG New Delhi community. Thanks for the work you have done dedicatedly.

**Comment by AudMonte01** [comment]
Thank you for your affirmation, @satyampsoni. Please have at least 3 more of your current co-organizers confirm they accept Krish as a co-organizer here.

**Comment by akumar-99** [comment]
+1
Krish has been our most active volunteer yet. Having him onboard as an organizer will help us a lot.

**Comment by its-harsshhh** [comment]
Krish has been an invaluable contributor to many of our past events, consistently going above and beyond to support the CNCG New Delhi community. I fully support his role as a co-organizer, and I believe his passion and dedication will continue to elevate our events and initiatives. +1 from my side!

**Comment by AudMonte01** [comment]
Excellent! With at least 50% of the organizers voting yes (and likely more), I will move forward with adding Krish as a co-organizer.

@KrishAryan - you should have just received an automated welcome email from me with further instructions, as well as a notification that you have been added to the [CNCG global organizer Slack channel in the CNCF workspace](https://cloud-native.slack.com/archives/C04KB96TA2X).

This ticket/issue is now closed.
