### ISSUE TITLE
[Organizer Request] Add Organizers to dormant Sydney Chapter

### ISSUE THREAD

**Issue by bradmccoydev** [cncf/communitygroups#155]
### Name of chapter inquiring about

Sydney

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

KCD Australia Organiser Group
organisers
Brad McCoy @bradmccoydev
Sharlene Tee https://www.linkedin.com/in/sharlenetee/
Brendon Thwaites https://www.linkedin.com/in/bthwaitesaus/
Matt Flannery https://www.linkedin.com/in/devopsaustralia/

### Tell us why you want to be added or removed from the chapter

As discussed regarding continuing on the KCD Australia and running the monthly meetups

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you for submitting this issue, @bradmccoydev. It is good to see this chapter being reactivated with CNCF ambassadors/legacy community members, as well as those have co-organized the successful community-driven KCD.

I have reactivate the chapter: https://community.cncf.io/cloud-native-sydney/. You should have all received automated welcome emails from me.

No need for the co-organizers to comment regarding the terms, as they have already done so via the KCD, as well as taken the inclusive LF training.

**Comment by matthewflannery** [comment]
Thanks @AudMonte01 !
