### ISSUE TITLE
Regarding discontinuation as a volunteer 

### ISSUE THREAD

**Issue by Kirtikagoyal** [cncf/communitygroups#156]
Dear community,
It's always been an amazing opportunity to be a part of CNCF New delhi as a volunteer.
Although I couldn't contribute much to the community due to other commitments.
I am sorry for this, and i hope once i'm a little settled in my entrepreneurial journey i'd love to contribute better. cncf has given me friends who're always there cheering me. 
Thank you cncf for all the learnings, network and community love. 
And i wish the best for the community and the friends I've made along the journey. 
Will try to attend upcoming events as attendees and help with small activities there.

Cheers!
Kirtika

**Comment by satyampsoni** [comment]
It was great working with you kiritka, we hope to see you at our future events and learn from those events.

cc @AudMonte01
