### ISSUE TITLE
Remove Organizer from New Delhi Chapter

### ISSUE THREAD

**Issue by ShivangShandilya** [cncf/communitygroups#157]
### Name of chapter inquiring about

Cloud Native New Delhi

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Shivang Shandilya
[LinkedIn](https://www.linkedin.com/in/shivang-shandilya/)
[X](https://x.com/shivv_twt)

### Tell us why you want to be added or removed from the chapter

I, Shivang Shandilya would like to be removed from Cloud Native New Delhi chapter as I'm currently focused in a different work altogether and I'm not able to devote time to help organize events alongside my fellow organizers.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by satyampsoni** [comment]
cc @AudMonte01

**Comment by AudMonte01** [comment]
Thank you, @ShivangShandilya - we are sorry to see you go, but happy to learn your focus is broadening. Wishing you the best in your cloud native journey.

This issue/ticket is now closed.
