### ISSUE TITLE
[Group Request] Create a new chapter "CNCG Dehradun"

### ISSUE THREAD

**Issue by ashutoshkandpal89** [cncf/communitygroups#158]
### City or location name for your CNCG

Cloud Native Dehradun

### What country do you want to start your community group in?

India

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

I am Technology Consultant and Social Entrepreneur with a mission to empower the world via the latest technological advancements. I am a self-taught programmer striving to take up and solve the new challenges of life, In this journey of learning, I thank the open source and open courseware community/free learning of Harvard, MIT, and Stanford. Especially thanks to the platforms such as Edx, Coursera, and Youtube.  I am a Microsoft Certified Trainer and Kubernetes Explorer with certifications like AZ-104, AZ-400, AI-102, CKA, and CKS.

https://www.linkedin.com/in/ashutoshkandpal/

(https://github.com/ashutoshkandpal89)

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Mohit Bisht, a Computer Science undergraduate, is passionate about designing and building innovative solutions. With expertise in graphic design and web development, he transforms ideas into visually appealing and functional realities. Mohit's proficiency spans across Photoshop, Figma, and extends into web development, cloud technologies, and open-source contributions. His technical skills include AWS, JavaScript, Kubernetes, Docker, Go, and C++. He's eager to connect with those who share his enthusiasm for open source, startups, and continuous learning.

(https://github.com/Mohiit70)

https://www.linkedin.com/in/mohit-bisht70/

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Not Applicable

### If you already run a meetup, please link it here

Not Applicable

### What is your mission statement or objective for this new chapter?

"To make it easy for individuals and organizations in Dehradun to understand and use cloud-native technologies, and to support each other in building better software solutions and contributing to the growth of the cloud-native ecosystem in the region."

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by ashutoshkandpal89** [comment]
cc @AudMonte01

**Comment by Mohiit70** [comment]
@ashutoshkandpal89 , I would like to co-organize with you.

**Comment by ashutoshkandpal89** [comment]
Hi Mohit,

Thank you for expressing interest in taking on an organizing role with us. Your enthusiasm is greatly appreciated. 

In order to ensure that our organizers are fully committed and well-aligned with our community's values, we require a minimum volunteer commitment of six months. This period allows us to gauge your dedication and consistency. Notably, our chapter in Delhi, CNCG Delhi, was built on the foundation of such dedicated volunteer efforts.

Should you wish to proceed with volunteering, I invite you to connect with me via LinkedIn:

Looking forward to potentially working together to further our collective goals.

@AudMonte01  my linkedin id is https://www.linkedin.com/in/ashutoshkandpal/

**Comment by AudMonte01** [comment]
Also, do either of you know the previous organizers of this chapter? They were Sarthak Jain and Kshitiz Saini, both from Dot Questionmark.

**Comment by ashutoshkandpal89** [comment]
@AudMonte01 I'm not acquainted with them. 

@Mohiit70 , let's continue via LinkedIn DM.  ( https://www.linkedin.com/in/ashutoshkandpal/ )

**Comment by AudMonte01** [comment]
Thank you, @ashutoshkandpal89 - any response from them?

**Comment by ashutoshkandpal89** [comment]
@AudMonte01  No response as of now. Additionally, I've updated the relevant information for both Mohit and myself within the issue. Could you please confirm receipt of these updates? Thank you.

**Comment by AudMonte01** [comment]
That is okay - I appreciate you trying. We have not received response from them either, so we will move forward with you, @ashutoshkandpal89 and @Mohiit70 as organizers. But first, please do provide your community.cncf.io accounts. I will also need @Mohiit70 to confirm he accepts all of the above terms, and confirm he has taken the open and inclusive, free online exam listed above.

**Comment by Mohiit70** [comment]
> That is okay - I appreciate you trying. We have not received response from them either, so we will move forward with you, [@ashutoshkandpal89](https://github.com/ashutoshkandpal89) and [@Mohiit70](https://github.com/Mohiit70) as organizers. But first, please do provide your community.cncf.io accounts. I will also need [@Mohiit70](https://github.com/Mohiit70) to confirm he accepts all of the above terms, and confirm he has taken the open and inclusive, free online exam listed above.

@AudMonte01 I accept all the above terms and confirm that I have taken the open and inclusive exam as mentioned. My certification ID for LFC102 is LF2zl5w5lg7d.

**Comment by ashutoshkandpal89** [comment]
@AudMonte01 Please find attached my CNCF community profile. Please find attached https://community.cncf.io/u/mc23pw/#/about. Let me know if you require anything further.

**Comment by AudMonte01** [comment]
Thank you, @ashutoshkandpal89 - I have now added you as an organizer to the Dehradun chapter. You should have just received an automated welcome email from me. Please focus on what is under the CNCG heading.

@Mohiit70 - please also confirm your community.cncf.io profile so I can also add you as an organizer to the chapter.

**Comment by ashutoshkandpal89** [comment]
@AudMonte01 yes I did receive it. Thanks a ton!. will go through this and shall reach back if necessary.

also find Mohit's CNCF community profile. https://community.cncf.io/u/mn9qer/.

**Comment by AudMonte01** [comment]
Great! @Mohiit70 - you should have just received an automated welcome email from me as well. Please follow next steps there.

This issue/ticket is now closed.
