### ISSUE TITLE
Update text to discuss new CommunityGroups program

### ISSUE THREAD

**Issue by caniszczyk** [cncf/communitygroups#16]
https://github.com/cncf/communitygroups

**Comment by caniszczyk** [comment]
@idvoretskyi can you update all the language here in the README and various places

**Comment by idvoretskyi** [comment]
Fixed with https://github.com/cncf/communitygroups/pull/17

**Comment by idvoretskyi** [comment]
Also fixed by https://github.com/cncf/communitygroups/commit/4e7379469bf1a38fedad207fe2b25b3b50969c66
