### ISSUE TITLE
[Group Request] Create a new chapter in Brasília, Brazil

### ISSUE THREAD

**Issue by ruan-oliveira** [cncf/communitygroups#161]
### City or location name for your CNCG

Cloud Native Brasília

### What country do you want to start your community group in?

Brasil

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Currently, I am an operations and delivery executive at **Jack Experts**. I also work in design, architecture, consulting and training in Kubernetes, in addition to managing teams focused on the customer and/or continuous deliveries.

I have supported several companies in having environments monitored beyond the basics, workloads hosted in Kubernetes in a resilient way, multcluster and multcloud, promoting good practices from the container. Among the public and private companies are: TCU, Ministry of Justice, Antaq, Globalweb, Fintech Magalu, Empiricus, Banco do Brasil, Caixa Econômica, RNP, Sebrae, CGU, etc.

Linkedin: https://www.linkedin.com/in/ruan-sysadmin/
Github: https://github.com/ruan-oliveira
CNCF: https://community.cncf.io/u/mysatb/#/about

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

We are a group of organizers from the DevOps community in Brasília and would like to join the CNCF to organize events in the capital of the country.

https://devopsdays.org/events/2024-brasilia/contact

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

We are a group of organizers from the DevOps community in Brasília and would like to join the CNCF to organize events in the capital of the country.

https://devopsdays.org/events/2024-brasilia/contact

### If you already run a meetup, please link it here

We are a DevOps community in Brasília and the topics are quite common.

Meetup: https://meetupdevopsbsb.eventize.com.br/?preview
DevOpsDays: https://devopsdaysbrasilia.eventize.com.br/

### What is your mission statement or objective for this new chapter?

I have been working with DevOps and Cloud Native for over 5 years. I joined other people engaged in sharing knowledge and exchanging ideas about tools, processes and people involved in this entire ecosystem. In addition, I manage a Kubernetes consulting company and I know that we can strengthen and promote Kubernetes in the capital of Brazil.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Hello @ruan-oliveira - please pardon my delay here. We have a KubeStronaut that is interested in organizing a chapter in Brasilia as well. I have asked him to take a look at this submission, with the intention that the two of you could co-organize together.

The more organizers the better so the responsibility to stay an active chapter does not fall on only one person.

**Comment by pedrocrc** [comment]
> Hello [@ruan-oliveira](https://github.com/ruan-oliveira) - please pardon my delay here. We have a KubeStronaut that is interested in organizing a chapter in Brasilia as well. I have asked him to take a look at this submission, with the intention that the two of you could co-organize together.
> 
> The more organizers the better so the responsibility to stay an active chapter does not fall on only one person.

Hello @ruan-oliveira and @AudMonte01 . I've talked to Christophe Sauthier about creating the CNCF Chapter in Brasilia, Brazil. @AudMonte01 have told me about this issue and the fact that you are seeking to also do such organization.

I'd like to know if you are open to co-organize it with me, @ruan-oliveira .

I'm also based in Brasilia, Brazil. My LinkedIn is [https://linkedin.com/in/pedrocrc/](https://linkedin.com/in/pedrocrc/) . I'm currently a Principal SRE at CLDF (Câmara Legislativa do Distrito Federal), and I'm also a special contractor at Bank of Brazil, where I have been co-creating the SRE Center of Excellence.

I have great experience in cloud native technologies for over 6 years, and I've led several great projects, specially the modernization of the legacy computing environment at CLDF into cloud-native, as well as designing the observability architecture at Bank of Brazil with focus on SLO tracking.

I currently hold 10 CNCF certifications, as well as being the 2nd Kubestronaut in Brazil. I also hold several other certifications on SRE, AWS, GCP, MC Azure and so on.

Also, I'm part of the CNCF OpenTelemetry SME group, and I'm a candidate to the CNCF Platform Engineering SME group.

**Comment by pedrocrc** [comment]
@AudMonte01 , I've reached out @ruan-oliveira and we both agreed to join efforts to the creation of the chapter. Since you said that the more organizers, the better, I'll reach out to some other people to find out about their interest, and share this issue URL with them, so they can manifest here. What would be the next steps?

**Comment by neuhauss** [comment]
Hey guys, I have been participating in the past Kubernetes meetups in Brasilia, and I would definitely like to help collaborate.

**Comment by ruan-oliveira** [comment]
> [@AudMonte01](https://github.com/AudMonte01) , I've reached out [@ruan-oliveira](https://github.com/ruan-oliveira) and we both agreed to join efforts to the creation of the chapter. Since you said that the more organizers, the better, I'll reach out to some other people to find out about their interest, and share this issue URL with them, so they can manifest here. What would be the next steps?

Perfect! I'm very energetic and want to contribute as much as I can. I just organized the DevOps Days Brasília (https://linktr.ee/devopsdaysbsb) and it was a success. I believe I can contribute to the organization's learnings, supplier contact, input management and sponsorships! Let's go together.

**Comment by sandrorgguimaraes** [comment]
Hello everyone, I would like to make myself available to help organize the chapter. I work on the PaaS Cloud team at Banco do Brasil.

https://www.linkedin.com/in/sandrorgguimaraes/

Best regards.

**Comment by AudMonte01** [comment]
This is great to see so much interest in the organization of this chapter!
@neuhauss - please provide your LinkedIn profile and agree to the above organizers terms.

Everyone should also provide proof of having taken the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) by simply commenting with a link to your Credly badges.

Also, aside from @ruan-oliveira, I will need each of you to either create an account on community.cncf.io or point to your account their.

Thank you,

Audra Montenegro
CNCF Community Program Manager
KCDs & CNCGs

**Comment by ggrcha** [comment]
What a great iniciative. I am making myself available to help with any means necessary to make this project up and running. Currently I work as Tech Lead of Public Cloud Engineering at Banco do Brasil.


Linkedin: https://www.linkedin.com/in/ggrcha/

**Comment by neuhauss** [comment]
Here is my linkedin profile 
https://www.linkedin.com/in/neuhauss/

**Comment by paulogabriel13** [comment]
Great idea to start a CNCF chapter in Brasília! I work as an SRE and would love to help organize events and build the community. Here’s my LinkedIn: https://www.linkedin.com/in/paulo-gabriel-ribacionka-38297622b

**Comment by sandrorgguimaraes** [comment]
Hello, Audra.
Here is [my credly badge for the course](https://www.credly.com/badges/4820f122-5b3d-4152-bc48-251a5e2f5c5b/public_url).
Here is [my CNCF profile](https://community.cncf.io/u/mjfg93).

**Comment by neuhauss** [comment]
My CNCF profile https://community.cncf.io/u/mzp375/#/about
My Badge https://openprofile.dev/profile/vneuhauss

**Comment by uere** [comment]
Hi everyone, 

I would like to make myself available to help organize the chapter. I work on the PaaS Cloud/ Cloud Platfform as IT Specialist at Banco do Brasil, since 2017.

https://www.linkedin.com/in/uere-edilson-jr/
https://community.cncf.io/u/mg5duv/
https://www.credly.com/badges/7c4b4aa2-640b-407c-a8ac-cf118979faa1/public_url

Best regards.

**Comment by pedrocrc** [comment]
@AudMonte01 , we can move on with the following organizers, who have successfully posted their profiles and badges:
@pedrocrc, @ruan-oliveira, @neuhauss, @sandrorgguimaraes,  @uere

**Comment by AudMonte01** [comment]
Thank you everyone! I have added the 5 organizers who completed the course and provided their community profiles. This is the fastest I have seen a chapter come together with the recommended maximum amount of organizers. Please note - some chapters have 10 organizers, but since this one is just getting started, I recommend first getting established with roles and responsibilities, and building out a strategy for cadence of meetups, and meetup styles.

You 5 should have received automated welcome emails from me with next steps. This ticket is now closed.
