### ISSUE TITLE
[Organizer Request] Add Jeffry Hernández to Cali, Colombia chapter

### ISSUE THREAD

**Issue by jeffincloud** [cncf/communitygroups#165]
### Name of chapter inquiring about

Cloud Native Cali

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

- Name: Jeffry Hernández
- Email: guitarrojeff@gmail.com
- GitHub: https://github.com/jeffincloud
- Company: Wizeline
- LinkedIn: https://www.linkedin.com/in/jeffry-hernandez/
- CNCF Slack Workspace name: Jeffry Hernández in CNCF Slack
- https://community.cncf.io/u/mpdmu2/#/about

### Tell us why you want to be added or removed from the chapter

Hi there ✋ 
I'm Jeffry Hernández, an SRE based in Cali - Colombia that works remotely for Wizeline. I've been in the IT industry for above 6 years and I love the open source and the community initiatives, everything that is related to the help people grow through the learning of new technologies.

I'm a CKA certified and I'm preparing for the CKAD exam.

And last but not least I've been supporting the Cali Community Group since the beginning and have seen closely the fast growth of this group and I would be more than happy to be selected as co-organizer.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
This is great, @jeffincloud - please have the current organizers comment here with their approval of adding you as a co-organizer to the Cali chapter.

**Comment by bedoyacloud** [comment]
Hi @AudMonte01 Yes,  I'm speaking of behalf of the organizers, we are more than happy that @jeffincloud can be in the Organizers team, He has been providing great value to CNCF Cali Colombia Community.

**Comment by AudMonte01** [comment]
Thank you, @bedoyacloud - I have added @jeffincloud as an organizer to the Cali, Colombia chapter.

Jeff - you should have just received an automated welcome email from me with next steps.

This issue/ticket is now closed.
