### ISSUE TITLE
[Group Request] Create a new chapter in Molise, Italy

### ISSUE THREAD

**Issue by nicolanoviello** [cncf/communitygroups#166]
### City or location name for your CNCG

Cloud Native Molise

### What country do you want to start your community group in?

Italy

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Nicola Noviello, https://github.com/nicolanoviell, https://github.com/nicolanoviello, https://www.linkedin.com/in/nicola-noviello/, Nicola in CNCF Slack, https://community.cncf.io/u/m5aktj/#/about

### What is your mission statement or objective for this new chapter?

Our mission is to promote the adoption and growth of cloud-native technologies within our local community, serving as a hub for professionals, students, and enthusiasts. Through events, workshops, and collaborations, we aim to foster knowledge exchange, develop skills, and create synergies that accelerate innovation in cloud computing, containers, Kubernetes, and modern infrastructure.

### Code of Conduct

- [x] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [x] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [x] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [x] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [x] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [x] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [x] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [x] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [x] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [x] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Ciao @nicolanoviello,

Based in your K8s certifications, Cloud Native connections and work as a University Professor, you seem like a great fit to run a Molise chapter, which we do not have a history of anyone owning.

That said, all I need is proof of your completion of the open and inclusive open source exam mentioned above.

Grazie,

Audra Montenegro
CNCF Community Program Manager
Cloud Native Community Groups
community-groups@cncf.io

**Comment by nicolanoviello** [comment]
**Ciao** Audra! What great news! I’m thrilled to take the first step in building this community. 
Regarding the exam, you can check the completion certificate [here](https://www.credly.com/badges/6d7630e1-46fc-4c8d-a385-eb33b7d5fe67/public_url). 
Grazie!!!!
Nicola

**Comment by AudMonte01** [comment]
Excellent! I just created the chapter. You should have received an automated welcome email from me with next steps. Please be sure to add a profile picture in your commuity.cncf.io account. I also host office hours every Friday, so if you care to attend tomorrow for some onboarding, please register here: https://community.cncf.io/e/m9z6gg/.

This ticket is now closed.
