### ISSUE TITLE
[Organizer Request] Remove Arne Mejholm Organizer from Aalborg chapter

### ISSUE THREAD

**Issue by tuxiem** [cncf/communitygroups#167]
### Cloud Native Aalborg, Denmark

Inquiry from: Camilla Larsen, https://community.cncf.io/u/mytytt/ on behalf of Cloud Native Aalborg Orgs. Team.

We have a change in organizers, in our local community group.

Please remove `mejlholm@mejlholm.org` from the list of organizers.  
<img src="https://github.com/user-attachments/assets/0337aae2-7668-48ca-bc64-57ab7d566c40" width="350" />

### Tell us why you want to be added or removed from the chapter

Not relevant

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [ ] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [ ] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [ ] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [ ] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [ ] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [ ] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [ ] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you, @tuxiem for submitting this. We just need @mejlholm to confirm his resignation.

**Comment by mejlholm** [comment]
@AudMonte01 I currently cant find the time to help organize, so go ahead and remove me 🫡

**Comment by AudMonte01** [comment]
Thank you for the response, @mejlholm - I have removed you from the chapter. Best wishes in your cloud native journey.

This issue/ticket is now closed.
