### ISSUE TITLE
[Organizer Request] Add Christoffer Hollensen to Aalborg Chapter

### ISSUE THREAD

**Issue by cholle99** [cncf/communitygroups#169]
### Name of chapter inquiring about

Aalborg

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Name: Christoffer Hollensen
Email: chollensen1999@gmail.com
Company: Trifork A/S
GitHub URL: https://github.com/cholle99
LinkedIn URL: https://www.linkedin.com/in/cchqwe/
CNCF Slack Workspace: cloud-native-nordics.slack.com
CNCF profile: https://community.cncf.io/u/m94kh9/#/about

### Tell us why you want to be added or removed from the chapter

I would like to join as an organizer in the Aalborg Community after receving an invitation to join by the organizers. I have already participated in the first organizer meeting. Also, I have my first talk in the CNCF community on 29. October on alerting & dashboards.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by tuxiem** [comment]
Approved 👍 @AudMonte01

**Comment by AudMonte01** [comment]
Excellent. I have added you, @cholle99 to the chapter as an organizer. You should have just received an automated welcome email from me with further instructions.

This ticket/issue is now closed.
