### ISSUE TITLE
[Organizer Request] Add Harsha Thirimanna to K8s Austin chapter

### ISSUE THREAD

**Issue by harsha1979** [cncf/communitygroups#172]
### Name of chapter inquiring about

Kubernetes Austin

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Harsha Thirimanna, harsha.thirimanna@gmail.com, harshat@wso2.com, WSO2 LLC, https://github.com/harsha1979, https://www.linkedin.com/in/harshathirimanna, Harsha Thirimanna in CNCF Slack, https://community.cncf.io/u/mnagxn/#/about

### Tell us why you want to be added or removed from the chapter

I would like to join as a co-organizer. With over 17 years of experience in the software industry and currently serving as the head of the IAM BU at WSO2 LLC, I believe my expertise would be a valuable asset to this community. I’m eager to contribute and actively participate in the group's activities.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by chadmcrowell** [comment]
Approved! Great to have you @harsha1979 !!

**Comment by AudMonte01** [comment]
Thank you @harsha1979 and @chadmcrowell for following the guidelines and submitting this form with the organizer terms. I have added Harsh to the chapter, and he should have just received an automated welcome email from me with next steps.

This issue/ticket is now closed.
