### ISSUE TITLE
[Organizer Request] Add Rob Kenefeck as a co-organizer for CNCG Melbourne

### ISSUE THREAD

**Issue by rkenefeck** [cncf/communitygroups#174]
### Name of chapter inquiring about

Cloud Native Melbourne

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Rob Kenefeck, ControlPlane, https://github.com/rkenefeck, https://www.linkedin.com/in/robkenefeck/, CNCF Slack: Rob Kenefeck,  https://community.cncf.io/u/mvam65/

### Tell us why you want to be added or removed from the chapter

I have been a member of this community for a number of years, from back when Containerisation was focused on Docker. I am a regular atendee at the Melbourne meetups related to anything in the Cloud Native space, I've presented talks at Infracoders, K8SUG, Cloud Native Auckland, ContainerCamp and been an active participant (asking questions, speaking with guests) at many of the event which include Cloud or DevOps including DevOpsDays and KCD Australia. 

I used to work at Servian, where I started a Cloud Native Guild to give approx 150 consultants interested in the space a forum to discuss Cloud Native news, as well as coaching more junior consultants on researching and presenting interesting talks once a month to the other consultants. I also used to run all the internal training on Kubernetes, both an entry level course for all new starters to the company and more in depth courses for those looking to progress their  learning. Since moving to ControlPlane, I've started to get involved with the APAC TAG Security, have sponsored both the K8SUG Meetup and KCD Australia, and have hosted Kubernetes CTF events at 2 conferences in Australia. 

I'm keen to keep building this community in Australia, and instead of hiding in the background persuading people and supporting initiatives as a silent backer I now want to take a bigger role in growing our local community.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by rkenefeck** [comment]
@thiago4go

**Comment by thiago4go** [comment]
Hi @rkenefeck Thanks so much for your submission and your eagerness to collaborate with our chapter. Together, we're working to make Cloud Native ubiquitous Down Under, driving growth, innovation, and transformation in the tech landscape.

If you haven't already, I'd highly recommend taking the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/). This course is a fantastic resource for fostering inclusivity and ensuring our community remains welcoming and diversity-friendly.

Your expertise in Cloud Native Security and your influence in the ANZ region will be invaluable to helping our chapter achieve its goals. I'm thrilled to welcome you aboard!

Approved! @AudMonte01 @k8tgreenley

**Comment by AudMonte01** [comment]
This is great, @rkenefeck - you would be a good addition to the chapter. Please finish the above-mentioned course and let us know once it is completed. Thank you.

**Comment by rkenefeck** [comment]
Hey @AudMonte01 - I've now completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

**Comment by AudMonte01** [comment]
Excellent - thank you, @rkenefeck. Please point me to your Credly badge for proof of completion.

**Comment by rkenefeck** [comment]
> Excellent - thank you, @rkenefeck. Please point me to your Credly badge for proof of completion.
Here you go @AudMonte01 
https://www.credly.com/badges/bb3365cc-de0d-48cb-88fe-655c038d02fb/public_url

**Comment by AudMonte01** [comment]
Excellent! I have now added you as an organizer to the chapter, @rkenefeck . You should have received an automated welcome email from me.

Please add a profile picture to your https://community.cncf.io/u/mvam65/ account so we can make sure you show up as an organizer on the chapter page.

This ticket is now closed.
