### ISSUE TITLE
[Group Request] Create a new chapter in Hong Kong

### ISSUE THREAD

**Issue by huanwei** [cncf/communitygroups#175]
### City or location name for your CNCG

Cloud Native Hong Kong

### What country do you want to start your community group in?

China

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Huan Wei, HarmonyCloud, https://github.com/huanwei, https://www.linkedin.com/in/huan-wei-b53932255/, Huan Wei in CNCF slack, https://community.cncf.io/u/m8hak9/#/about

### What is your mission statement or objective for this new chapter?

We're excited about microservices, containers, the distributions that run them and the solutions that deploy, manage and extend them. Any skill level is welcome, from Kubernetes beginners to Kubernetes best practices experts. We want to create an open, welcoming environment for all Kubernauts.

### Code of Conduct

- [x] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [x] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [x] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [x] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [x] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [x] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [x] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [x] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [x] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [x] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Thank you, @huanwei for your interest in starting this chapter. Since you applied for a Hangzhou KCD and your LinkedIn says Hangzhou, It is only fair to let those who live in Hong Kong to be the ones running this chapter.

Kind regards,
Audra Montenegro
CNCF Community Program Manager
community-groups@cncf.io
