### ISSUE TITLE
[Group Request] Reactivate Guwahati chapter

### ISSUE THREAD

**Issue by paras3c** [cncf/communitygroups#176]
### City or location name for your CNCG

Cloud Native Guwahati

### What country do you want to start your community group in?

India

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Name: Siddhartha Rajbongshi
Company: Space Generation Advisory Council
Email: officialparasec@gmail.com
GitHub URL: https://github.com/paras3c
LinkedIn URL: https://www.linkedin.com/in/siddhartharajbongshi
CNCF Profile Link: https://community.cncf.io/u/mybf95/#/about
CNCF Slack Workspace Name: Siddhartha Rajbongshi

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Name: Shreyash Kashyap
Company: Gauhati University
Email: kashyapshreyash826@gmail.com
GitHub URL: https://github.com/SYK-08
LinkedIn URL: https://www.linkedin.com/in/shreyash-kashyap-bb2933300
CNCF Profile Link: https://community.cncf.io/u/mz2wry/#/about
CNCF Slack Workspace Name: Need to be invited

### What is your mission statement or objective for this new chapter?

At Cloud Native Guwahati, we are committed to building a dynamic, knowledge-sharing community where technology enthusiasts can come together to learn, experiment, and innovate. Our mission is to equip members with the skills and expertise needed to excel in the rapidly evolving field of cloud-native technologies. Through engaging workshops, hackathons, speaker sessions, and hands-on coding events, we aim to create an environment that fosters creativity, collaboration, and continuous learning.

We envision this chapter as a hub for cloud-native solutions, encouraging the adoption of best practices in microservices, container orchestration, CI/CD pipelines, and more. Whether you're a beginner looking to get started or an experienced professional seeking to stay ahead of the curve, Cloud Native Guwahati is the space where ideas turn into impactful innovations. By contributing to open-source projects and tackling real-world challenges, we aim to empower our community to lead the digital transformation in the region and beyond.

Our goal is to bridge the gap between academia and industry, helping individuals and organizations alike embrace cloud-native architectures to enhance scalability, security, and performance in modern applications.

### Code of Conduct

- [x] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [x] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [x] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [x] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [x] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [x] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [x] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [x] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [x] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [x] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Hello @paras3c - thank you for submitting this issue to reactivate the Guwahati chapter. Please have Shreyash comment here agreeing to the above terms. He should comment via his own GitHub account. Above you listed yours again with his information.

Thank you,

Audra Montenegro
CNCF Core Community Program Manager
CNCGs & KCDs

**Comment by SYK-08** [comment]
@AudMonte01 I agree to all the terms mentioned above and ready to work in the CNCF Guwahati Chapter.

Thank you,
Shreyash B Kashyap
CNCF Co-organizer, Guwahati Chapter

**Comment by AudMonte01** [comment]
Thank you, both. I have updated the above issue with the proper link for @SYK-08.

Please either provide me with the certification number of the open and inclusive exam you took, or add the badge to your LinkedIn profiles.

**Comment by paras3c** [comment]
Sure Audra, I have just completed the certification. Here’s the credly link: https://www.credly.com/badges/30318fe0-4be9-488a-ae3d-aa1ab04461f1/public_url

Hope it helps :)

**Comment by SYK-08** [comment]
@AudMonte01 Just updated my LinkedIn Profile by adding the LFC102 Badge.

Badge URL: https://www.credly.com/badges/3688ae79-f27f-4104-a565-1e8e68298cda/public_url

**Comment by AudMonte01** [comment]
Excellent - thank you. I have reactivated the chapter with just the two of you as organizers.

Please follow [the logo guidelines here](https://github.com/cncf/communitygroups/blob/main/assets.md) to create a new logo.

This issue/ticket is now closed.
