### ISSUE TITLE
[Organizer Request] Add Ayesha Yege to Santo Domingo chapter

### ISSUE THREAD

**Issue by Ayege** [cncf/communitygroups#177]
### Name of chapter inquiring about

Cloud Native Santo Domingo 

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

I’m Ayesha Yege, a passionate software engineer and technology enthusiast with a strong focus on backend development, cloud infrastructure, and DevOps. I specialize in building scalable applications using modern technologies like .NET, EF Core, Docker, Kubernetes, and cloud services like Azure and AWS.

With a diverse background in software development, I’ve successfully contributed to various projects ranging from API development to cloud-native architectures. I thrive in fast-paced environments, continuously learning new tools and techniques to optimize workflows and deliver high-quality solutions.

I’m also an advocate for open-source contributions and community engagement. I’m actively involved in the CNCF community and excited about sharing knowledge, mentoring others, and fostering collaboration among developers worldwide.

-Name: Ayesha Yege
-Email: yegeayesha@gmail.com
-Company: Sigma Petroleum
-GitHub URL: https://github.com/Ayege
-LinkedIn URL: https://www.linkedin.com/in/ayesha-yege/
-Community Profile URL: https://community.cncf.io/u/m893kc/

### Tell us why you want to be added or removed from the chapter

As a woman in STEM, I am passionate about promoting diversity and inclusivity in the technology community. I believe that fostering a more diverse and representative community can spark innovation, new perspectives, and a stronger support system for underrepresented groups. By joining the CNCF Santo Domingo chapter as an organizer, I aim to encourage more women and diverse individuals to engage with cloud-native technologies, contribute to open-source projects, and pursue careers in tech.

Being involved in this community is important to me because I’ve seen firsthand the impact that mentorship, community engagement, and knowledge sharing can have on individuals who might otherwise feel isolated in this field. I hope to inspire others by showing that gender, background, or circumstances should not be a barrier to success in tech.

With my experience in cloud-native development and active involvement in various technical communities, I am eager to contribute to the CNCF Santo Domingo chapter by organizing events, workshops, and discussions that champion diversity and encourage collaboration among all members of the tech ecosystem.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you for your submission @Ayege - I will put this issue in front of the current organizers so they can tell you the best next steps for joining as an co-organizer.

But first, if you have not yet already - please attend their meetups regularly and become a member of [the Santo Domingo chapter](https://community.cncf.io/cloud-native-cali/).

**Comment by AudMonte01** [comment]
Hello @jorgeortegap - Ayesha seems like a good addition to the chapter. Please let her know what the appropriate ext steps would be to partake in organizing.

**Comment by jorgeortegap** [comment]
Hi @AudMonte01 , that's correct! @Ayege initiated as a community member in our chapter, but her skills, contributions, and community-driven efforts have made of her a key member organizer for our team. This being the case, please approve this request for Ayesha to join as a co-organizer. Thanks in advance!

**Comment by AudMonte01** [comment]
Excellent - thank you for confirming @jorgeortegap. @Ayege - I have added you as an organizer to the Santo Domingo chapter. You should have received an automated welcome email from me with next steps. Please update your profile picture so AWS is not in it, as CNCF remains vendor-neutral and so should all the community group chapters.

Thank you - this ticket is now closed.
