### ISSUE TITLE
[Organizer Request] Remove Nagaraju Kancherla from CNCF Vancouver

### ISSUE THREAD

**Issue by ShankyJS** [cncf/communitygroups#178]
### Name of chapter inquiring about

CNCF Vancouver

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Hey, I'm Shanky, part of the organizing team of Cloud Native Vancouver.

[Github](github.com/ShankyJS)
[Linkedin](linkedin.com/in/shankyjs)

### Tell us why you want to be added or removed from the chapter

Hey, so Nagaru Kancherla was one of the OG team members in Cloud Native Vancouver, sadly he's moving away from Vancouver and has decided to step down from the CNCF Community.

We truly appreciate all the efforts that Raj did during his time with CNCF Vancouver and we are welcoming in case Raj would like to join us again if he decides to come back to the city of Vancouver.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [ ] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you for this submissions @ShankyJS - please have Raj comment on this issue with his confirmation of resignation.

**Comment by kancherlanagaraju** [comment]
@AudMonte01  and @ShankyJS , please consider this as my confirmation of resignation for Cloud Native Vancouver.

**Comment by AudMonte01** [comment]
Thank you for all your efforts up until now, @kancherlanagaraju. I have removed you from the chapter as an organizer. We hope you will stay as a member and attend future meetups.  Best regards, Audra

This issue/ticket is now closed.
