### ISSUE TITLE
[Organizer Request] Add Adenn Tumba as a member from CNCF from Salvador

### ISSUE THREAD

**Issue by adenntumba** [cncf/communitygroups#182]
### Name of chapter inquiring about

Cloud Native Salvador Bahia

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

E-mail: adinn.tumba@hotmail. com
GitHub: https://github.com/adenntumba
LinkedIn: https://www.linkedin.com/in/adenntumba/
Cloud Native Salvador Bahia Slack workspace name: Adenn Tumba
Profile link on community.cncf.io: https://community.cncf.io/u/mw38wh/#/about

[PT-BR]
Atuo como Engenheiro de Cloud e possuo mais de 7 anos de experiência na área tech. Entusiasta de infraestrutura como código, buscando desafios em projetos inovadores com foco em automatizar processos e garantir a confiabilidade dos sistemas. Empolgado em contribuir para a comunidade CNCF Salvador e contribuiu para a adoção de práticas de nuvem nativa na região.

Tenho interesse em pertencer ao grupo CNCF Salvador, para ajudar no fomento e contribuir para a adoção de práticas cloud nativas na comunidade de Salvador. Acredito que a colaboração e o compartilhamento de conhecimento são fundamentais para o crescimento do ecossistema.

[EN]
I work as a Cloud Engineer and have more than 7 years of experience in the tech area. Infrastructure as code enthusiast, seeking challenges in innovative projects focused on automating processes and ensuring system reliability. Excited to contribute to the CNCF Salvador community and contributed to the adoption of native cloud practices in the region.

I am interested in joining the CNCF Salvador group, to help promote and contribute to the adoption of native cloud practices in the Salvador community. I believe that collaboration and knowledge sharing are fundamental to the growth of the ecosystem.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you for your submission, @adenntumba! With Milton's thumbs-up, it seems you have been approved to join this chapter. That said, all I need from you is proof of having taken the open and inclusive course listed above. A link to your Credly badge will work.

**Comment by adenntumba** [comment]
Hi @AudMonte01  about the inclusive course listed above follow the Credly badge link https://www.credly.com/badges/12941bff-8aaf-4bfa-ad24-58fbad5eaf26/public_url

**Comment by AudMonte01** [comment]
Excellent - thank you, @adenntumba . I have added you as a chapter member. You should have just received an automated welcome email from me with next steps.

This issue/ticket is now closed.
