### ISSUE TITLE
[Organizer Request] Add or Remove Organizer Name

### ISSUE THREAD

**Issue by rodxvalenca** [cncf/communitygroups#183]
### Name of chapter inquiring about

Cloud Native São Paulo

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Rodolfo Valença, e-mail: [rod_valenca@hotmail.com](mailto:rod_valenca@hotmail.com), Engineering Manager at Nubank responsible for the Computing scope (e.g. Kubernetes), https://www.linkedin.com/in/rodvalenca/, I don't have yet a CNCF Slack so I need to be invited (@rod.valenca / [rodolfo.valenca@nubank.com.br](mailto:rodolfo.valenca@nubank.com.br))

### Tell us why you want to be added or removed from the chapter

I would like to be a organizer/co-organizer to be more engaged with the community, support and help this community to growth and form new talents. I have many years of experience managing teams and  projects with different technological scopes.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if not relevent to request)

### Organizers companies/affiliations

- [ ] I come from xyz company which is differing from that of the current organizers (do not mark if not relevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if not relevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if not relevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if not relevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if not relevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if not relevent to request)

**Comment by krol3** [comment]
@rodxvalenca, Thanks for your interest in participate in the Sao Paulo Chapter. 

My name is Carol, organizer of chapter Sao Paulo, I recommended you first participate in our local meetups, and in our internal regular meetings to do planifications about events. Everyone is welcome, please go to our next meetup to meet you better and introduce you to the team.

**Comment by rikatz** [comment]
-1.

Please attend some meetups first, get in touch with the current organizers.

**Comment by AudMonte01** [comment]
I agree with these first steps. Once the team has seen your commitment and agree to add you as an organizers, then we can re-open this issue. For now I will close it.

Best regards,

Audra Montenegro
CNCF Community Program Manager
community.cncf.io
