### ISSUE TITLE
[Organizer Request] Add Santosh Kumar Perumal

### ISSUE THREAD

**Issue by Santosh-Kumar-Perumal** [cncf/communitygroups#189]
### Name of chapter inquiring about

Cloud Native Westminster

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Name: Santosh Kumar Perumal
Mail: [santosh.personalid@gmail.com](mailto:santosh.personalid@gmail.com)
LinkedIn: https://www.linkedin.com/in/santosh-kumar-perumal/
GitHub: https://github.com/Santosh-Kumar-Perumal
CNCF slack: U04TLLUCE31
Profile: https://community.cncf.io/u/mnjaba/#/about

### Tell us why you want to be added or removed from the chapter

Hi @AudMonte01 👋 

I am reaching out to express my interest in becoming an organizer for the **[Cloud Native Westminster](https://community.cncf.io/cloud-native-westminster/)** chapter. After organising the first ever meetup under Cloud Native Westminster chapter as part of CNCF TAG Sustainability week 2024 along with @MathewJoseph1993 and @rohitg00 current organisers of the chapter , they suggested I submit a request to be added as an organizer to this chapter to continue further contributing to the chapter by organising In-person and Virtual meetups.

---

### 🔗 Community Engagement Highlights

- 🌱 **Organized the First-Ever [Cloud Native Sustainability Meetup](https://community.cncf.io/events/details/cncf-cloud-native-westminster-presents-cncf-sustainability-week-2024-london-meetup/)**  
  Held as part of **CNCF TAG Sustainability Week 2024**.

- 🤝 **Volunteered for the [OpenUK SOOCON Event 2024](https://stateofopencon.com/)**  
  As an OpenUK [Ambassador](https://openuk.uk/ambassadors/), I focus on advocating, mentoring, and frequently organizing local meetups alongside fellow OpenUK Ambassadors.

- 📜 **Completed the [Inclusive Open Source Community Orientation Course](https://www.credly.com/badges/49af3831-a64c-4ff7-b220-913242b2a1ca/public_url)**  
  Focused on building inclusive, welcoming open-source communities.

- 🇵🇰 **Contributed to Kubernetes Community Day Pakistan**  
  I had the opportunity to [speak](https://badgr.com/public/assertions/1SjhIX_aQAGrVByn7SZ4VQ?identity__email=santosh.personalid@gmail.com) about the Knative open-source project.

- 🚀 **[CD Foundation Ambassador](https://cd.foundation/ambassadors/)**  
  Serving in this role for the past two years.

- ☁️ **Google Cloud WTM Ambassador**  
- 🌟 **Google Cloud Innovator**  
- 🌐 **STEM Ambassador**  
- 💼 **Member of the FinOps community**  
- 🐾 **Tigera Calico Big Cat**  
- 🪐 **Astronomer Champion for Apache Airflow** (focused on OpenSource Apache Airflow)  
- 🤲 **Open Source Contributor**  
- 🎤 **Public Speaker**  
- 💻 **Google Developer Expert - Google Cloud**  
- 🌍 **Google Champion Innovator - Google Cloud**  
- 🌎 **Peoplecert Ambassador for DevOps Institute**

- 🎤 **Speaker at Multiple Events**  
  You can find more details on my [Sessionize directory](https://sessionize.com/santosh-kumar-perumal).

@AudMonte01 can you please help with this request?  
Please let me know if you need more details.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if not relevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if not relevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if not relevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if not relevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if not relevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if not relevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if not relevent to request)

**Comment by rohitg00** [comment]
+1

**Comment by MathewJoseph1993** [comment]
@Santosh-Kumar-Perumal it would be a pleasure if you could be part of our team 😊

**Comment by Santosh-Kumar-Perumal** [comment]
> +1

Thanks for the upvote @rohitg00

**Comment by Santosh-Kumar-Perumal** [comment]
> [@Santosh-Kumar-Perumal](https://github.com/Santosh-Kumar-Perumal) it would be a pleasure if you could be part of our team 😊

Thanks @MathewJoseph1993 happy to collaborate for a better cause and give back to community.

**Comment by AudMonte01** [comment]
Excellent - thank you for this submission, @Santosh-Kumar-Perumal. It is a pleasure to see @rohitg00 and @MathewJoseph1993 upvote you as an addition to the chapter.

I have added you as an organizer. You should have just received an automated welcome email from me with next steps.

This issue/ticket is now closed.

**Comment by Santosh-Kumar-Perumal** [comment]
> Excellent - thank you for this submission, [@Santosh-Kumar-Perumal](https://github.com/Santosh-Kumar-Perumal). It is a pleasure to see [@rohitg00](https://github.com/rohitg00) and [@MathewJoseph1993](https://github.com/MathewJoseph1993) upvote you as an addition to the chapter.
> 
> I have added you as an organizer. You should have just received an automated welcome email from me with next steps.
> 
> This issue/ticket is now closed.

Thanks @AudMonte01 @rohitg00 and @MathewJoseph1993 for all the support.
