### ISSUE TITLE
Failure syncing bevy events with Meetup events

### ISSUE THREAD

**Issue by rikatz** [cncf/communitygroups#19]
We've started migrating our Cloud Native Sao Paulo Meetup from Meetup.com to community.cncf.io

It seems that the sync between the event creation is not working :(

I've created an event in [bevy](https://community.cncf.io/events/details/cncf-cloud-native-sao-paulo-presents-cncf-community-brasil-livestream-2020/#/) last week, expecting this to be replicated to Meetup but this didn't happened, so I've manually created  the [Meetup](https://www.meetup.com/pt-BR/Cloud-Native-Sao-Paulo/events/272085885/) event.

Opening this to register :)

/cc @idvoretskyi

**Comment by idvoretskyi** [comment]
@rikatz thanks, we'll pass this to Bevy!

**Comment by idvoretskyi** [comment]
@rikatz should be fixed now, can you please check?

**Comment by rikatz** [comment]
I've created an event now (https://community.cncf.io/events/details/cncf-cloud-native-sao-paulo-presents-online-cloud-native-sao-paulo-meetup-16/#/), it has shown me in the confirmation page this would be synchronized with meetup.com but right now there's no event created yet.

Will wait until tomorrow and re-check again :)

**Comment by idvoretskyi** [comment]
@rikatz any updates? :)

**Comment by rikatz** [comment]
@idvoretskyi no joy :( 

The past event I've created now have a "Meetup logo" linking it to the meetup I've created manually, but the newer one (Aug/11) not :(

**Comment by idvoretskyi** [comment]
@rikatz thanks, asking Bevy for the further investigation.

**Comment by rikatz** [comment]
@idvoretskyi I'm thinking about manually opening this in Meetup.com so people will get some spare time to plan their participation. We can still continue to try this in other demo/test event inside the chapter, WDYT?

Thanks :)

**Comment by idvoretskyi** [comment]
@rikatz sure!

**Comment by rikatz** [comment]
@idvoretskyi any news from Bevy? Created this new one event (https://community.cncf.io/events/details/cncf-cloud-native-sao-paulo-presents-online-cloud-native-sao-paulo-meetup-17/#/) and synced by hand in Meetup.com :)

**Comment by idvoretskyi** [comment]
Bevy reported to us that the issue is caused by the broken Meetup API presumably, but no solution yet.

We'll keep this issue updated.

**Comment by rikatz** [comment]
Great! Thanks for the follow up Ihor!
