### ISSUE TITLE
[Organizer Request] Add Organizer Sajeeva Nambadawa Vithanage

### ISSUE THREAD

**Issue by nvsajeeva** [cncf/communitygroups#190]
### Name of chapter inquiring about

Cloud Native Westminster

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Sajeeva Nambadawa Vithanage, nvsajeeva@gmail.com, KUBEFLEX LIMITED, https://github.com/nvsajeeva, https://www.linkedin.com/in/sajeeval/,  Sajeeva Lakmal, https://community.cncf.io/u/mwv65v/#/about

### Tell us why you want to be added or removed from the chapter

I, Sajeeva Nambadawa Vithanage would like to join as a co-organizer for the [Cloud Native Westminster](https://community.cncf.io/cloud-native-westminster/) chapter. I had the pleasure of attending the chapter's first event on October 24th and was impressed by how well it was organized. I also had a chance to chat with the current organizers (@MathewJoseph1993), where we briefly discussed potential ways I could contribute to future events.

I'm passionate about Cloud Native technologies and actively promote them through my LinkedIn and Medium posts to raise awareness and engage the community.

---
**Achievements**
👉 Earliest Kubestronaut
👉 Became the 4th person globally to complete all CNCF certifications. See [Credly](https://www.credly.com/users/sajeeva-lakmal.e53b189d). 

Hi @AudMonte01  can you please help with this request?
Please let me know if you need more details.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if not relevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if not relevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if not relevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if not relevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if not relevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if not relevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if not relevent to request)

**Comment by MathewJoseph1993** [comment]
Hi @nvsajeeva , I would be happy if you could be part of our team 😊

**Comment by AudMonte01** [comment]
Thank you @nvsajeeva for this submission. I just need an upvote from @rohitg00 as well.

**Comment by rohitg00** [comment]
I approve of this; we had a quality discussion and suggested some important pointers for being an organizer and contributing to CNCF.
@AudMonte01

**Comment by AudMonte01** [comment]
Excellent! The final step is to please point me to your Credly badge proving your completed the open and inclusive training, @nvsajeeva.

**Comment by MathewJoseph1993** [comment]
Hi @AudMonte01  any updates on @nvsajeeva application?

**Comment by AudMonte01** [comment]
Excellent - thank you, everyone. @nvsajeeva - you have been added as a co-organizer to the chapter. You should have received an automated welcome email from me with next steps.

This issue/ticket is now closed.

**Comment by nvsajeeva** [comment]
Thank you so much @AudMonte01 !
