### ISSUE TITLE
[Organizer Request] Add Vinod Sulochana Raveendran

### ISSUE THREAD

**Issue by vinodsr007** [cncf/communitygroups#191]
### Name of chapter inquiring about

Cloud Native Westminster

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Hi @AudMonte01 👋

Name: Vinod Sulochana Raveendran (Vinod SR)
Mail: vinodsr007@gmail.com
LinkedIn: https://www.linkedin.com/in/srvinod/
GitHub: https://github.com/vinodsrincloud
CNCF slack: U04TLLUCE31
Profile: https://community.cncf.io/u/mvkrqb

### Tell us why you want to be added or removed from the chapter

I am reaching out to express my interest in becoming an organizer for the [Cloud Native Westminster](https://community.cncf.io/cloud-native-westminster/) chapter. After organising the first ever meetup under Cloud Native Westminster chapter as part of CNCF TAG Sustainability week 2024 along with @MathewJoseph1993 and @rohitg00 current organisers of the chapter , they suggested I submit a request to be added as an organizer to this chapter to continue further contributing to the chapter by organising In-person and Virtual meetups.

🔗 Community Engagement Highlights
🌱 Organized the First-Ever [Cloud Native Sustainability Meetup](https://community.cncf.io/events/details/cncf-cloud-native-westminster-presents-cncf-sustainability-week-2024-london-meetup/)
Held as part of CNCF TAG Sustainability Week 2024

🌐 STEM Ambassador

🌎 Peoplecert Ambassador for DevOps Institute

@AudMonte01 can you please help with this request?
Please let me know if you need more details.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if not relevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if not relevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if not relevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if not relevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if not relevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if not relevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if not relevent to request)

**Comment by MathewJoseph1993** [comment]
Hi @vinodsr007 I would be happy if you could be part of our team 😊

**Comment by AudMonte01** [comment]
Thank you for your submission @vinodsr007.

I just need @rohitg00 to confirm you as an additional organizer.

**Comment by rohitg00** [comment]
Yes, @MathewJoseph1993 and I had discussion we would like to add @vinodsr007

**Comment by AudMonte01** [comment]
Excellent - I have added you, @vinodsr007 as an organizer to the chapter. You should have just received an automated welcome email from me with next steps.
