### ISSUE TITLE
[Organizer Request] Add Matthew Slane to KCDUK

### ISSUE THREAD

**Issue by mattslane** [cncf/communitygroups#193]
### Name of chapter inquiring about

KCD UK

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Matthew Slane, matthewjslane@googlemail.com, Platform Engineer, https://github.com/mattslane, https://www.linkedin.com/in/mjslane/
M Slane in Slack - https://cloud-native.slack.com/team/U0170PPLHFY

### Tell us why you want to be added or removed from the chapter

I would like to join KCD UK as an organiser. I am already in communication with the rest of the KCD UK organising team, have joined their private slack channel on the cncf slack, have helped out with the recent London event and have started help with organising the 2025 event.

I am based near Edinburgh in the UK.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if not relevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if not relevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if not relevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if not relevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if not relevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if not relevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if not relevent to request)

**Comment by AudMonte01** [comment]
Excellent - thank you, @ckranz ! Will you have at least half the KCD UK team give your comment a thumbs up?

**Comment by ckranz** [comment]
Thanks @AudMonte01, done! (albeit with a little confusion over exactly which comment to thumbs-up 😆)

**Comment by AudMonte01** [comment]
Awesome! Yes, "your comment" versus the GitHub issue submission by Matt. Thank you :-)

**Comment by AudMonte01** [comment]
@mattslane - it looks like we just need you to update your community.cncf.io profile with a bio and headshot image since your profile will be forward-facing as an organizer. Please and thank you!

**Comment by mattslane** [comment]
@AudMonte01 That should be updated now. Thanks, Matt

**Comment by AudMonte01** [comment]
Excellent! You should have just received an automated welcome email from me with next steps. I have also added you to all the proper channels and aliases.

This issue/ticket is now closed.
