### ISSUE TITLE
[Organizer Request] Add Elcio Castro as a member from CNCF from Salvador

### ISSUE THREAD

**Issue by elciocastro** [cncf/communitygroups#194]
### Name of chapter inquiring about

Cloud Native Salvador Bahia

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

E-mail: elciocastro89@gmail.com
GitHub: https://github.com/elciocastro
LinkedIn: https://www.linkedin.com/in/elciocastrocosta/
Cloud Native Salvador Bahia Slack workspace name: Elcio Castro
Profile link on community.cncf.io: https://community.cncf.io/u/mcqzs3/#/about

### Tell us why you want to be added or removed from the chapter

[PT-BR]
Atuo como Engenheiro de Cloud e possuo mais de 9 anos de experiência na área tech. Entusiasta pelo mundo da tecnologia e por solucoes opensource.

Tenho interesse em integrar o grupo CNCF Salvador para apoiar a comunidade local e ajudar a disseminar o conhecimento.

[EN]
I work as a Cloud Engineer and have over 9 years of experience in the tech field. I am passionate about the world of technology and open source solutions.

I am interested in joining the CNCF Salvador group to support the local community and help spread knowledge.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if not relevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if not relevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if not relevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if not relevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if not relevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if not relevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if not relevent to request)

**Comment by miltlima** [comment]
+1

**Comment by elciocastro** [comment]
Hi @AudMonte01 

Here is the link to the credly badge - https://www.credly.com/badges/8458cbe8-e008-4a53-8c81-7767b1862d51/public_url

**Comment by AudMonte01** [comment]
Thank you! I have added you to the chapter. You should have received an automated welcome email from me.

Please be sure to update your https://community.cncf.io/u/mcqzs3/#/about account with a photo of yourself, as it will be forward-facing as an organizer of the chapter.

This ticket/issue is now closed.
