### ISSUE TITLE
[Group Request] Create a new chapter in Pereira/Risaralda/Colombia - CNCF Pereira

### ISSUE THREAD

**Issue by h3ct0rjs** [cncf/communitygroups#195]
### City or location name for your CNCG

Pereira/Risaralda

### What country do you want to start your community group in?

Colombia

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Hello Everybody 😎, 👋My name is Hector Fabio Jimenez Saldarriaga @h3ct0rjs , but you can call me H or Hector. I’m from the beautiful🌠country of Colombia 🌎. I’m Currently working as a Site Reliability Engineer at GoDaddy Inc,  I have also been in other roles in the past like CloudOps/NetOps/DevOps🥷 Engineer,  having the opportunity to work with some awesome technologies and different Cloud Providers like AWS, Azure, GCP and different Datacenters providers for CDNs. I hold a bachelor’s degree in Computer and Systems Engineering and an Electrical Technology bachelor’s degree from Universidad Tecnológica de Pereira.

I’m a co-organizer of a local community where I try to support and collaborate in different kinds of meetups/events/cons here, in our beautiful city 😄. See [PereiraTechTalks](https://www.pereiratechtalks.com/) for more info. When I'm not working with IaC I'm working in my technical skills and contributing to OSS projects, also like to be a speaker from time to time. 

Name: Hector Fabio Jimenez Sladarriaga
Email: [h3ct0rjs@gmail.com](mailto:h3ct0rjs@gmail.com)
GitHub: https://github.com/h3ct0rjs
Company: GoDaddy Inc
LinkedIn: https://www.linkedin.com/in/h3ct0rjs/
CNCF Slack Workspace name: Hector Fabio Jimenez in CNCF Slack/Kubernetes Slack
https://community.cncf.io/u/m9zsyu/#/about

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

👋 I am Andrés Torres @elfotografo007 and I am a senior software engineer at FirmScribe. I specialize in backend development and software architecture. Previously I have worked at VMware/Broadcom in the Tanzu offering, having contributed there to a couple of products targeting Kubernetes. I have also contributed to a couple of open-source projects like Sigstore and Knative. I've been a speaker at local conferences
and meetups.

Name: Andrés Felipe Torres Cano
Email: elfotografo007@gmail.com
GitHub: [https://github.com/elfotografo007](https://github.com/elfotografo007)
Company: FirmScribe Inc
LinkedIn: https://www.linkedin.com/in/elfotografo007/
I do need to be invited to the CNCF Slack workspace
Profile Link: https://community.cncf.io/u/mzpbwq/#/about

### If you already run a meetup, please link it here

We don't have a CNCF meetup at this moment in our Region (Eje Cafetero), but we run our local community of Pereira Tech Talks where we talk about different technologies 

See for more : 
https://www.pereiratechtalks.com/meetups/
https://www.meetup.com/pereira-tech-talks/

See for more info : 

https://www.pereiratechtalks.com/about/

We would love to open a chapter here in Pereira

### What is your mission statement or objective for this new chapter?

✨Our mission is to cultivate a vibrant, inclusive community in Pereira focused on advancing cloud-native technologies, fostering collaboration, and building expertise. With the support of Pereira Tech Talks, we aim to empower developers, IT professionals, and enthusiasts by providing access to cutting-edge knowledge, hands-on learning, and opportunities for networking. Together, we’re committed to establishing Pereira as a hub for cloud-native innovation and contributing to the global CNCF ecosystem.

### Code of Conduct

- [x] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [x] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [x] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [x] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [x] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [x] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [x] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [x] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [x] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [x] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Hello @h3ct0rjs - you seem like a great fit as a chapter organizer. Also, we do not yet have a chapter in Pereira/Risaralda which is central to the other chapters in Colombia that are Medellin, Bogota, and Cali.

Before we get your started, please send me the Credly badge each person receives once completing the above, online open and inclusive course.

Thank you,
Audra Montenegro
CNCF Community Program Manager

**Comment by h3ct0rjs** [comment]
Hi @AudMonte01  I hope you're doing great, here it is : 

- https://www.credly.com/badges/a9b2042b-f69e-4254-b96e-4e7ab5b49f31/public_url
- https://www.credly.com/badges/45b5d1a9-cf87-457c-a330-dc61b7223e8f/public_url

**Comment by AudMonte01** [comment]
Thank you, @h3ct0rjs - I have added you both as organizers. You should have just received automated welcome emails from me with next steps.

@elfotografo007 - please update your profile with a headshot and bio, as this will be forward-facing to the community on your chapter page. Right now I have your profile hidden.

This issue/ticket is now closed.
