### ISSUE TITLE
[Organizer Request] Remove 3 Organizers of Cloud Native Montpellier

### ISSUE THREAD

**Issue by juliencresta** [cncf/communitygroups#199]
### Name of chapter inquiring about

Cloud Native Montpellier

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Daniel Beruben
https://www.linkedin.com/in/damoul/

Guillaume Leroy
https://www.linkedin.com/in/gleroypro/

Cyril Cuvier
https://www.linkedin.com/in/cyril-cuvier/

### Tell us why you want to be added or removed from the chapter

The 3 person listed above are no longer apart of the Cloud Native Montpellier organisation. 

Some others have replace them but we can't add them to bevy because places are occupied by these old members.

Thanks for your help.
 
@AudMonte01 

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [ ] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if not relevent to request)

### Organizers companies/affiliations

- [ ] I come from xyz company which is differing from that of the current organizers (do not mark if not relevent to request)

### Inclusive

- [ ] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if not relevent to request)

### Vendor Neutral

- [ ] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if not relevent to request)

### Remain an active chapter

- [ ] I understand the activity level standards of all CNCF chapters (do not mark if not relevent to request)

### Collaboration with other chapters

- [ ] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if not relevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [ ] I will do my best to host diverse speakers throughout the year (do not mark if not relevent to request)

**Comment by AudMonte01** [comment]
Thank you, @juliencresta. Please have Daniel, Guillaume, and Cyril comment within this issue confirming their resignation.

**Comment by dberuben** [comment]
I confirm, you can delete myself

**Comment by dberuben** [comment]
👍

**Comment by cyrilcuvier** [comment]
please remove me from this list 👍

**Comment by AudMonte01** [comment]
I have removed @dberuben and @cyrilcuvier. Thank you for your time with this community group and helping to bring cloud native to Montpellier.

I am now just awaiting Guillaume Leroy to comment confirming his resignation from the chapter before closing this ticket.

**Comment by leroyguillaume** [comment]
Please remove me 🙏

**Comment by AudMonte01** [comment]
Thank you for your time previously, @leroyguillaume in helping spread the knowledge of cloud native. We hope you stay a member of the chapter and attend future meetups. Kind regards, Audra

This issue/ticket is now closed.
