### ISSUE TITLE
[Bevy] Tags to link chapters together

### ISSUE THREAD

**Issue by Solisol** [cncf/communitygroups#20]
We're hosting a set of chapters in the Nordics that we collect under something we call Cloud Native Nordics. We usually do different collaborations, especially now that we're doing virtual sessions. 

We wish there was a way to tag chapters with something like #CloudNativeNordics and that there would be a landing page where you can view all chapters linked to the tag. (or maybe just link to [https://cloudnativenordics.com](https://cloudnativenordics.com))
We want to be able to reconfigure the tag as we go.

We know about subgroups, but as the chapters are located in different cities and countries we don't feel that fulfils the needs we have. 

We would appreciate if this was possible to add to Bevy. 🙏 

This request came up during the monthly Cloud Native Nordics community call, on Sept 2 2020, and following people wanted tracking 😄 
@solisol 
@kaspernissen
@luxas
@idvoretskyi

**Comment by idvoretskyi** [comment]
@Solisol thanks, we'll pass this to Bevy!

**Comment by AudMonte01** [comment]
This was resolved with a "Cloud Native Nordics" chapter all last year, but then determined by the team that the visibility and search capabilities were altered for the sub chapters, once this assignment was made. BUT there is a co-hosting feature in bevy that the team is able to take advantage of. This can happen on a per event bases within the event settings of the main hosting chapter. I will close this issue, unless there is further need around these connected chapters.
