### ISSUE TITLE
[Organizer Request] Add Tanguy Ladet as co-organizer of Cloud Native Montpellier Chapter

### ISSUE THREAD

**Issue by juliencresta** [cncf/communitygroups#200]
### Name of chapter inquiring about

Cloud Native Montpellier

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Thanks to add: 

> Tanguy Ladet
> tanguyladet@gmail.com
> https://www.linkedin.com/in/tanguy-ladet-58954b171/

to the Cloud Native Montpellier Chapter

### Tell us why you want to be added or removed from the chapter

Tanguy would be added as a co-organizer. He is already apart of the team and help us finding speakers and organizing events.
 

@AudMonte01 

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [ ] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if not relevent to request)

### Organizers companies/affiliations

- [ ] I come from xyz company which is differing from that of the current organizers (do not mark if not relevent to request)

### Inclusive

- [ ] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if not relevent to request)

### Vendor Neutral

- [ ] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if not relevent to request)

### Remain an active chapter

- [ ] I understand the activity level standards of all CNCF chapters (do not mark if not relevent to request)

### Collaboration with other chapters

- [ ] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if not relevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [ ] I will do my best to host diverse speakers throughout the year (do not mark if not relevent to request)

**Comment by AudMonte01** [comment]
Thank you, @juliencresta - please have Tanguy comment pointing to the open and inclusive course Credly badge for proof of completion.

**Comment by ladettanguy** [comment]
Hello, I am indeed part of the team.

**Comment by ladettanguy** [comment]
That’s my Credly Profil: https://www.credly.com/users/tanguy-ladet

**Comment by AudMonte01** [comment]
Excellent, @ladettanguy - I have added you to the chapter as an organizer. You should have just received an automated welcome email from me with next steps. And if you agree to the above organizer terms, please check the box upon accessing the chapter via Bevy.

Please be sure to add a profile picture to your community.cncf.io account so it may be forward-facing on the chapter page.

This issue/ticket is now closed.
