### ISSUE TITLE
[Organizer Request] Remove Julien Cresta of Cloud Native Montpellier Chapter

### ISSUE THREAD

**Issue by juliencresta** [cncf/communitygroups#202]
### Name of chapter inquiring about

Cloud Native Montpellier

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

I'm the leading organizer of the Cloud Native Montpellier Chapter

I have 2 profils in Bevy cause I registered with 2 different mail adresses. 

Can you please remove the **julien.cresta@fgtech.fr** profil please ? 

--> This one : ![Image](https://github.com/user-attachments/assets/fd15080f-b644-4bc7-9288-62794cf444b9)

### Tell us why you want to be added or removed from the chapter

Thanks to NOT REMOVE my actual profil : julien.cresta@gmail.com

(and sorry for all the requests, I needed this to be done to clear a little bit)

@AudMonte01 

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [ ] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if not relevent to request)

### Organizers companies/affiliations

- [ ] I come from xyz company which is differing from that of the current organizers (do not mark if not relevent to request)

### Inclusive

- [ ] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if not relevent to request)

### Vendor Neutral

- [ ] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if not relevent to request)

### Remain an active chapter

- [ ] I understand the activity level standards of all CNCF chapters (do not mark if not relevent to request)

### Collaboration with other chapters

- [ ] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if not relevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [ ] I will do my best to host diverse speakers throughout the year (do not mark if not relevent to request)

**Comment by AudMonte01** [comment]
Hi @juliencresta - I have removed your second account attached to the chapter. This ticket is now closed.
