### ISSUE TITLE
[Group Request] Create a new chapter in Kochi - India

### ISSUE THREAD

**Issue by the-yathrikan** [cncf/communitygroups#204]
### City or location name for your CNCG

Cloud Native Kochi 

### What country do you want to start your community group in?

India

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Name: Govind Krishna
Email: govindkrishna00@gmail.com
Company & Designation: Senior Software Engineer, Advanced Millennium Technologies

Currently, I am a **Senior Software Engineer at Advanced Millennium Technologies**, Kochi, specializing in Cloud Native Technologies, and DevOps, with experience across Web2 and Web3 projects. A cloud computing enthusiast, I actively lead multiple projects on Kubernetes, emphasizing sustainable cloud-native practices. I work extensively with CNCF projects like Prometheus and Open telemetry tools, ensuring resilient monitoring and observability for robust, scalable solutions. In addition, I am an active participant, organizing team member, and volunteer at various CNCF global events, including **Kubernetes Days Kerala**, **Kubernetes Birthday Bash**, and **DevOps Days Kerala**.

LinkedIn: https://www.linkedin.com/in/govind-krishna-224633120/
GitHub: https://github.com/the-yathrikan
CNCF: https://community.cncf.io/u/m9mjgk/#/about
Slack: Govind Krishna

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Name: Nakul Dev
Email: nakuldev36@gmail.com
Company & Designation: Cloud Support Engineer II,  Amazon Web Services (AWS)
Slack: Nakul Dev
LinkedIn: https://www.linkedin.com/in/nakul-dev-33723182/
CNCF: https://community.cncf.io/u/mcd3xg
GitHub: https://github.com/denakul

A passionate Cloud Support Engineer at Amazon Web Services, I specialize in container orchestration technologies, particularly Elastic Container Service (ECS) and Elastic Kubernetes Service (EKS). With a strong foundation in EC2 Linux and other core AWS services, I am committed to delivering reliable and scalable cloud solutions.

Beyond technical expertise, I am an active member of the cloud community, having delivered a session on "Running Applications as Containers on AWS" at a community-led event. I am also a dedicated volunteer at various industry events, including Kubernetes Days Kerala, Kubernetes Birthday Bash, and DevOps Days Kerala.

### If you already run a meetup, please link it here

https://devopsdayskerala.in/

### What is your mission statement or objective for this new chapter?

My mission is to drive innovation and foster collaboration within the cloud-native and DevOps ecosystem. With over five years of experience in cloud-native application development and DevOps, I’ve had the privilege of working with talented individuals who are deeply committed to sharing knowledge and promoting best practices. Through my journey with cloud-native-focused companies, I’ve built strong connections with open-source enthusiasts and like-minded tech professionals. Now, I aim to contribute to the growth of this community, enabling them to engage closely with the CNCF from our own city of Kochi.

### Code of Conduct

- [x] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [x] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [x] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [x] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [x] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [x] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [x] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [x] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [x] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [x] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Hello @the-yathrikan - thank you for your submission. However, there is already a Kochi chapter: https://community.cncf.io/cloud-native-kochi/.

I suggest you, Govind, and Nakul first join as members, and attend meetups consistently if you have not already been doing so. 

This issue/ticket is now closed.
