### ISSUE TITLE
[Group Request] Create a new chapter in Djerba, Tunisia

### ISSUE THREAD

**Issue by YoussefBayouli** [cncf/communitygroups#205]
### City or location name for your CNCG

Cloud Native Djerba

### What country do you want to start your community group in?

Tunisia

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Youssef BAYOULI (Youssef is a certified Kubernetes Administrator (CKA) and Kubernetes Security Specialist (CKS) with a deep commitment to nature and sustainability. Driven by a passion for building resilient, efficient, and environmentally conscious solutions, he is focused on advancing cloud-native technologies in his community. Motivated to empower others and promote sustainable tech practices, Youssef is back to his home island and wants to launch the CNCF Cloud Native Djerba chapter to foster collaboration, awareness, and innovation in cloud-native ecosystems.), bayouliyoussef@gmail.com,https://github.com/YoussefBayouli,https://www.linkedin.com/in/youssef-bayouli/, cncf profile : Youssef BAYOULI

### What is your mission statement or objective for this new chapter?

Our mission is to build a thriving cloud-native community in Djerba, harnessing the expertise of local engineers who work at renowned global companies like Google, Amazon, and Apple. Many of these skilled professionals are eager to contribute their knowledge and engage with others in the region. By raising awareness, offering hands-on workshops, and creating a platform for collaboration, this chapter aims to empower local developers, students, and tech enthusiasts to adopt and advance cloud-native technologies, positioning Djerba as a recognized contributor within the global tech ecosystem.

### Code of Conduct

- [x] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [x] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [x] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [x] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [x] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [x] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [x] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [x] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [x] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [x] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Hello @YoussefBayouli - thank you for your submission. We currently have a [Tunisia chapter](https://community.cncf.io/cloud-native-tunisia/), but since that is named by country, we had asked that organizer to be willing to name by city once the time comes another city in Tunisia would want to start a chapter. That said, please allow me to approach this organizer to ask about a name change ahead of moving forward with your chapter in Djerba.

**Comment by AudMonte01** [comment]
Hello @YoussefBayouli - I have good news that the Tunisia chapter has agreed to change their chapter name to Tunis. They are excited to have more organizers to collaborate with on a potential national event in the future.

That said, I will move forward with creating the Djerba chapter. Please first let me know which location is correct between the below two?

<img width="826" alt="Image" src="https://github.com/user-attachments/assets/2bffdec0-9099-450c-9379-925550d7e227" />

**Comment by YoussefBayouli** [comment]
Hi @AudMonte01,

Thank you so much for the great news! I’m thrilled to hear that. Is there a possibility to explore other cities options besides the two provided? My city, Houmt Souk, is the largest and most prominent city in Djerba, and it would be wonderful if we could reflect Djerba in the chapter name.

Looking forward to your thoughts!

**Comment by AudMonte01** [comment]
Yes, it is possible. Thank you for letting me know Djerba is like a state versus a city.

I also noticed you currently reside in Germany. Please tell me how much you visit Tunisia, as we have [90-day activity standards you can review here](https://github.com/cncf/communitygroups?tab=readme-ov-file#community-group-inactivity).

**Comment by YoussefBayouli** [comment]
Actually I am back to Djerba again and left Germany since 2 months ago.

**Comment by AudMonte01** [comment]
Excellent

I have added you as a chapter organizer to this newly created chapter called "Cloud Native Djerba" with a location of Houmt Souk, Tunisia. You should have just received an automated welcome email from me with next steps.

One of them being to explore this GitHub repository starting with the [README](https://github.com/cncf/communitygroups/blob/main/README.md).

This issue/ticket is now closed.
