### ISSUE TITLE
Create a new chapter in Boise ID

### ISSUE THREAD

**Issue by ryandcoates** [cncf/communitygroups#207]
### City or location name for your CNCG

Cloud Native Boise

### What country do you want to start your community group in?

United states

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Ryan Coates
ryan@rdc.dev

Sr Manager @ Deloitte
Faculty @ Codeworks LLC
President @ Boise Software Developer Group Inc, a 501(c)3 supporting tech events and communities in Boise, ID

https://github.com/ryandcoates
https://linkedin.com/in/ryandcoates
in cncf slack as ryan@rdc.dev
https://community.cncf.io/u/m9ymsz/#/about (new member)

### If you already run a meetup, please link it here

https://www.meetup.com/bsdg-meetup/
https://boisecodecamp.com

### What is your mission statement or objective for this new chapter?

We want to bring the cloud native community back to Boise, if you want to learn about microservices, containers, apis, kubernetes, serverless or anything related, join us as we traverse the cloud native landscape together!
Open to all, any experience level, community driven and supported.

### Code of Conduct

- [x] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [x] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [x] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [x] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [x] I/We have read what [vendor-neutrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-neutral

### Agree to use CNCG branding

- [x] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [x] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [x] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [x] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [x] I/We will do our best to host diverse speakers throughout the year

**Comment by ryandcoates** [comment]
@AudMonte01 tagging you per our slack :)

**Comment by AudMonte01** [comment]
Hi @ryandcoates - it was great to meet you on-site at KubeCon in Salt Lake City. You are a perfect fit! Please send proof of having taken the open and inclusive course linked above. A Credly badge usually works. Then I can get you added as a new organizer to the current dormant chapter.

Adding @mattmessinger, previous organizer, as an FYI.

**Comment by ryandcoates** [comment]
https://www.credly.com/badges/dfc4e592-42b5-4993-be6f-e3c7e04e6e1a

hoping this renders fine here

**Comment by AudMonte01** [comment]
Thank you, @ryandcoates - you have now been added as an organizer for the dormant Boise chapter. You should have just received an automated welcome email from me with next steps.

This issue/ticket is now closed.
