### ISSUE TITLE
[Organizer Request] Add Pedro Ignacio as co-organizer of Cloud Native Sao Paulo Chapter

### ISSUE THREAD

**Issue by krol3** [cncf/communitygroups#210]
### Name of chapter inquiring about

Cloud Native Sao Paulo

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Please add this new member:

Nome - Pedro Ignácio
Github - https://github.com/pedroignacio13
Linkedin - https://www.linkedin.com/in/pedroirufo/
Slack CNCF - Pedro Ignacio
CNCF Community Groups Profile - https://community.cncf.io/u/mv7z58/#/about

### Tell us why you want to be added or removed from the chapter

Pedro would be added as a co-organizer. He has already been part of the team, helping us find speakers and organize events for more than six months, and has been actively supporting as a co-organizer.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if not relevent to request)

### Organizers companies/affiliations

- [x] I come from Itau company which is differing from that of the current organizers (do not mark if not relevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if not relevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if not relevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if not relevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if not relevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if not relevent to request)

**Comment by AudMonte01** [comment]
Thank you, @krol3 for this addition/submission.

@pedroignacio13 - please comment on this GitHub issue with the following:
* Agreeing with the organizer terms
* A link to your Credly badge for the open and inclusive course we require you take

**Comment by pedroignacio13** [comment]
Hi Audra!
- I do agree with the organizer terms;
- Here's the badge of the Open and Inclusive course: https://www.credly.com/badges/cfcda260-adfe-4077-9f93-a3476d6cb854/public_url

**Comment by AudMonte01** [comment]
Thank you, @pedroignacio13 - you have now been added as an organizer to the Sao Paulo chapter! You should have received an automated welcome email from me.

This issue/ticket is now closed.
