### ISSUE TITLE
[Organizer Request] Add mbianchidev to CNCG Amsterdam / KCD Netherlands

### ISSUE THREAD

**Issue by mbianchidev** [cncf/communitygroups#217]
### Name of chapter inquiring about

CNCG Amsterdam / KCD Netherlands

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Matteo Bianchi, Independent, [https://github.com/mbianchidev](https://github.com/mbianchidev), @mbianchidev in the CNCF Slack, https://community.cncf.io/u/m9crwf/#/about

### Tell us why you want to be added or removed from the chapter

I, Matteo Bianchi, would like to join the chapter(s) as I'm part of the organization of both kind of events CNCG and KCD for the Netherlands and Amsterdam/Utrecht.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if not relevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if not relevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if not relevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if not relevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if not relevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if not relevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if not relevent to request)

**Comment by mbianchidev** [comment]
/assign @AudMonte01 

(doubt I can assign it in this way but I'm trying)

**Comment by AudMonte01** [comment]
Thank you, @mbianchidev - since I know your involvement with this team, I am adding you without requesting the other members to approve here with their comments. You should receive an automated welcome email shortly.

This ticket is now closed.
