### ISSUE TITLE
[Organizer Request] Add Faraj Khalid to Cloud Native Kuala Lumpur

### ISSUE THREAD

**Issue by mageshwaransekar** [cncf/communitygroups#224]
### Name of chapter inquiring about

Cloud Native Kuala Lumpur

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Mageshwaran Sekar, Organizer - Cloud Native Kuala Lumpur

### Tell us why you want to be added or removed from the chapter

@AudMonte01  - please add a new co-organizer Faraj Khalid to our chapter. 

- GitHub ID: @wolfsoldier47
- https://community.cncf.io/u/mbygu9
- CNCF Slack Profile: https://cloud-native.slack.com/team/U083RD48YTS

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if not relevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if not relevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if not relevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if not relevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if not relevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if not relevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if not relevent to request)

**Comment by wolfsoldier47** [comment]
I have completed "Inclusive Open Source Community Orientation (LFC102) " course.

**Comment by mageshwaransekar** [comment]
@AudMonte01 - all the steps are completed by Faraj Khalid. Please add him to our chapter. Thank you

**Comment by AudMonte01** [comment]
Excellent, @wolfsoldier47 - please send me a link to your Credly badge for proof of completion of the course.

**Comment by wolfsoldier47** [comment]
https://www.credly.com/badges/828cdfd2-4066-40d5-adaf-9eae8a6644f3/public_url

**Comment by AudMonte01** [comment]
Excellent, thank you @wolfsoldier47 ! Please add a profile image to your https://community.cncf.io/u/mbygu9 profile since it will be forward-facing on the chapter page.

**Comment by mageshwaransekar** [comment]
The profile seems updated now. Good to go, @AudMonte01

**Comment by AudMonte01** [comment]
Excellent

@wolfsoldier47 - you should have just received an automated welcome email from me with next steps. Welcome to the Kuala Lumpur team!

This issue/ticket is now closed.
