### ISSUE TITLE
[Organizer Request] Please Add or Organizer Conner Schiissler to Cloud Native Calgary

### ISSUE THREAD

**Issue by kevinevans1** [cncf/communitygroups#225]
### Name of chapter inquiring about

Cloud Native Calgary

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Conner is an IT generalist with a diverse background spanning DevOps, data engineering, software development, and cybersecurity. He is passionate about leveraging technology to drive business value and thrives at the intersection of innovation and practical solutions.

LinkedIn:  https://www.linkedin.com/in/conner-schiissler/

GitHub : https://github.com/Schiiss

CNCF Profile: https://community.cncf.io/u/m5qt7v/#/about

@AudMonte01 

### Tell us why you want to be added or removed from the chapter

Conners words: I’m eager to join the chapters Organizer to contribute to and bolster the incredible work of the current team. As a passionate advocate for open-source technologies and a self-proclaimed Kubernetes enthusiast, I’m excited to collaborate and drive meaningful impact within the community.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if not relevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if not relevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if not relevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if not relevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if not relevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if not relevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if not relevent to request)

**Comment by AudMonte01** [comment]
Thank you for submitting this @kevinevans1 ! Please have Conner comment here with him agreeing to the above terms and showing proof of having completed the above open and inclusive course.

**Comment by Schiiss** [comment]
Hey @AudMonte01, I agree to the above terms and have completed the inclusive course

![Image](https://github.com/user-attachments/assets/68910d25-d30c-4fd3-8dcc-461908e6897d)

**Comment by AudMonte01** [comment]
Thank you, @Schiiss - please point me to your Credly badge or certificate, which you can find in the button once you click through the email. Kind regards ~ Audra

**Comment by Schiiss** [comment]
Hey @AudMonte01, here it is, does this help: ![Image](https://github.com/user-attachments/assets/bb496f0f-8059-4c5d-af08-e5ac1cbef2ac)

**Comment by Schiiss** [comment]
@AudMonte01, here is the link to the badge as well: https://www.credly.com/badges/8d7d1787-c784-4677-b3a0-e168cd2aaaf9/public_url

**Comment by AudMonte01** [comment]
Excellent, @Schiiss ! I have added you as an organizer to the chapter. You should have just received an automated welcome email from me with next steps.

This issue/ticket is now closed.

**Comment by AudMonte01** [comment]
Yes, it looks like it's updated. Thank you!

<img width="1311" alt="Image" src="https://github.com/user-attachments/assets/69fa3322-b738-4f28-a662-98ff203bffaa" />
