### ISSUE TITLE
[Organizer Request] Add Faseela K to Cloud Native Aachen, NRW

### ISSUE THREAD

**Issue by kfaseela** [cncf/communitygroups#228]
### Name of chapter inquiring about

Cloud Native Aachen, NRW

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Faseela(@kfaseela) is a cloud-native developer at Ericsson, and a maintainer and Steering Committee member at Istio. She has given talks and workshops at several conferences evangelizing CNCF projects, including the recent KubeCons. She is a CNCF Ambassador, LFX Mentor, Program Chair of IstioDays co-located with KubeCons and the winner of the prestigious CNCF “Chop Wood Carry Water” award, 2023. She is also the creator of "Izzy saves the Birthday", a children's illustrated book from Istio.

Github : https://github.com/kfaseela
LinkedIn: https://www.linkedin.com/in/faseela-k-42178528/
CNCF Slack - Faseela K
https://community.cncf.io/u/m5maez/#/about

### Tell us why you want to be added or removed from the chapter

I, Faseela K, would like to join as a co-organizer for the Aachen chapter. I live in the same area, and I am a CNCF Ambassador. I am also a Steering Committee member at Istio and have been the Program Chair of Istio Days co-located with KubeCon NA and EU in 2023. I believe my expertise can be brought to use while organizing the cloud native meetups, especially in bringing experienced speakers to the event, as well as I can bring more local end users to the cloud-native team by bridging the gap between the two worlds. I have also spoken to the current organizers at our latest community meetup, and hence decided to create this issue with the request

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if not relevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if not relevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if not relevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if not relevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if not relevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if not relevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if not relevent to request)

**Comment by kfaseela** [comment]
cc @AudMonte01

**Comment by embik** [comment]
+1

**Comment by roehlc** [comment]
+1. Already looking forward to the contributions to our upcoming events!

**Comment by AudMonte01** [comment]
Excellent, thank you @kfaseela and to the up-vote from the organizers! All I need is proof of having completed the open and inclusive course mentioned above. A link to your Credly badge is usually the best. Thanks in advance!

**Comment by kfaseela** [comment]
> Excellent, thank you @kfaseela and to the up-vote from the organizers! All I need is proof of having completed the open and inclusive course mentioned above. A link to your Credly badge is usually the best. Thanks in advance!

Thanks @AudMonte01 . Here is the link to credly badge : https://www.credly.com/badges/508b6dac-4f13-43ad-818a-411d80a3e08c/public_url

**Comment by AudMonte01** [comment]
Thank you, @kfaseela - I have added you to the chapter. You should have received an automated welcome email from me with next steps.

This issue/ticket is now closed.
