### ISSUE TITLE
[Group Request] Create a new chapter for Portland, OR

### ISSUE THREAD

**Issue by mircubed** [cncf/communitygroups#231]
### City or location name for your CNCG

Cloud Native Portland

### What country do you want to start your community group in?

United States 

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Miranda Carter, Head of Community at Dagger. Previously Bitnami and VMware. 
email - miranda@dagger.io 
Company - Dagger
GitHub URL - https://github.com/mircubed
LinkedIn URL - https://www.linkedin.com/in/mirandamyerholtz/
CNCF Slack Name - Miranda Carter
Profile Link - https://community.cncf.io/u/m25yss/#/about

I've noticed that there hasn't been as many CNCF meetups in Portland recently, so I would love to help organize a new chapter. 

### If you already run a meetup, please link it here

I run all the [meetups for Dagger.io](https://www.meetup.com/pro/dagger/), but I do understand that the CNCF meetups would be separate and I would be volunteering my own time to do the CNCF chapter. 

### What is your mission statement or objective for this new chapter?

We’re thrilled to reignite the CNCF meetup experience in Portland, showcasing the incredible talent, cutting-edge technology, and innovative engineering that make our local community shine. Let’s connect, learn, and celebrate the amazing work happening right here in our backyard!

### Code of Conduct

- [x] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [x] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [x] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [x] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [x] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [x] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [x] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [x] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [x] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [x] I/We will do our best to host diverse speakers throughout the year

**Comment by mircubed** [comment]
as requested, tagging @AudMonte01 :)

**Comment by AudMonte01** [comment]
Hi @jberkus - tagging you on this GitHub issue, as it would be great to get the Portland chapter up and running again. Miranda here is willing to step in as organizer or co-organizer if you still wish to keep meetups going?

**Comment by jberkus** [comment]
Sure!  We also have someone who's been running periodic Kubernetes Meetups, let's sync everyone up.

@AudMonte01 am I able to just add her as co-organizer?

@mircubed can you ping me on CNCF Slack?

**Comment by AudMonte01** [comment]
I can add her, as well as other organizers here: https://www.meetup.com/cloud-native-pdx/. They will just need comment here confirming they agree to the above terms and show proof of having taken the open and inclusive course listed above. @mircubed do you have a Credly badge for your course completion?

We also need to be sure the PDX meetups are published on community.cncf.io. You can still use meetup.com as a marketing engine by cross-promoting/publishing.

**Comment by mircubed** [comment]
@AudMonte01 yes, I do. [miranda-carter-971dbae5-36ed-4a60-ac5d-61b2182519ed-certificate.pdf](https://github.com/user-attachments/files/18085109/miranda-carter-971dbae5-36ed-4a60-ac5d-61b2182519ed-certificate.pdf)

Pinged @jberkus on slack. We'll connect on next steps to see how I can help.

**Comment by jberkus** [comment]
So we'd like to un-archive the Portland Chapter in community.cncf.io.  That way we can list the holiday party (this week) as well as adding both Miranda and Chris Crow (hopefully).

**Comment by AudMonte01** [comment]
Excellent! I have made the chapter active again, and @mircubed has been added as a co-organizer. Miranda.- you should have just received an automated welcome email from me with next steps.

@jberkus - please do publish this week's meetup on community.cncf.io asap. Thank you, kindly ~ Audra

This issue/ticket is now closed.
