### ISSUE TITLE
[Organizer Request] Add or Remove Organizer Name

### ISSUE THREAD

**Issue by deloitte-saghili** [cncf/communitygroups#233]
### Name of chapter inquiring about

Cloud Native Frankfurt

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Shahrooz Aghili, Deloitte Consulting, https://github.com/aghilish, https://www.linkedin.com/in/aghilish/, Shahrooz Aghili in CNCF Slack, https://community.cncf.io/u/mmyp4r/#/about

### Tell us why you want to be added or removed from the chapter

I, Shahrooz Aghili would like to join as a new organizer, as the current organizer has been inactive for more than 3 months and has stepped down as an organizer on the community meetup.com group. I stepped up to save the meetup group and contacts. 
https://www.meetup.com/cloud-native-frankfurt/
In addition I have relevant expertise in cloud native technologies and actively track CNCF landscape and create educational content on cloud native technologies my YouTube channel. 
I gave a talk in the last event of Cloud Native Frankfurt. 
https://community.cncf.io/events/details/cncf-cloud-native-frankfurt-presents-cloud-native-frankfurt-meetup-jul-2024/
I am also a new contributor to the k8sgpt CNCF project.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [x] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if not relevent to request)

### Organizers companies/affiliations

- [x] I come from xyz company which is differing from that of the current organizers (do not mark if not relevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if not relevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if not relevent to request)

### Remain an active chapter

- [x] I understand the activity level standards of all CNCF chapters (do not mark if not relevent to request)

### Collaboration with other chapters

- [x] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if not relevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if not relevent to request)

**Comment by aghilish** [comment]
https://github.com/cncf/communitygroups/issues/234

**Comment by deloitte-saghili** [comment]
wrong github id was used to issue the request.
