### ISSUE TITLE
Google Calendar integration

### ISSUE THREAD

**Issue by caniszczyk** [cncf/communitygroups#29]
https://help.bevy.com/hc/en-us/articles/4411796136215-Google-Calendar-integration

**Comment by amye** [comment]
I'll start a thread with @jeefy and @cjyabraham about where the best place to put this on the CNCF website, but this is cool!

**Comment by AudMonte01** [comment]
Here is a sharable calendar that is synced with Bevy. It's actually more than just CNCGs, as it's every event hosted in Bevy: https://calendar.google.com/calendar/u/0?cid=Y181NTZiZjI1YzE2M2IwMzU3OWViOWUxNDZhYTcxNDUzYjU5MDgwYmI3ZjhlYzQ1YTVjZTU5MWQyN2U2ZDVhN2JiQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20

**Comment by AudMonte01** [comment]
@caniszczyk - I am closing this ticket based on the above solution.
