### ISSUE TITLE
Fix the CNCF meetup link in best_practices.md

### ISSUE THREAD

**Issue by ibatulanandjp** [cncf/communitygroups#41]
Update the link "_meetups.cncf.io_" to "_community.cncf.io_" in:
- File: [best_practices.md](https://github.com/cncf/communitygroups/blob/main/best_practices.md)
  - Section: [CNCF swag](https://github.com/cncf/communitygroups/blob/main/best_practices.md#cncf-swag)

Reference (Highlighted part):
<img width="536" alt="image" src="https://github.com/cncf/communitygroups/assets/62828060/80f1ad10-57c2-4698-92de-6db1aa1cf765">

```[tasklist]
### Tasks
- [ ] Update best_practices.md
```

**Comment by ATREAY** [comment]
hey @ibatulanandjp, can I work on this issue?

**Comment by AudMonte01** [comment]
This has been fixed a while back. Closing the ticket now.
