### ISSUE TITLE
Move to a system similar to KCDs when applying to host a CG/meetup

### ISSUE THREAD

**Issue by caniszczyk** [cncf/communitygroups#47]
We should move to a system where community groups (meetups) have to apply via github issue, similar to what we do with KCDs. This level of transparency will make it easier to see who is organizing these things, also provide opportunity to resolve any conflict if existing groups exist in the same city/region. In essence, this is just making the process more transparent which has proven to work very well for KCDs.

**Comment by k8tgreenley** [comment]
https://github.com/cncf/communitygroups/issues/new/choose - This has been completed and will be updated with a blog post this week
