### ISSUE TITLE
[Organizer Request] Add or Remove Organizer Name

### ISSUE THREAD

**Issue by halil-bugol** [cncf/communitygroups#51]
### Name of chapter inquiring about

Cloud Native Istanbul

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Halil Bugol, Co-Founder @Kubezy, CNCG Istanbul and KCD Istanbul Lead Organizer, CNCF Ambassador, https://www.linkedin.com/in/halilbugol/

### Tell us why you want to be added or removed from the chapter

Fırat Yaşar needs to be removed from the organizer list. It has been inactive for more than 6 months since last year.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you for submitting this issue @halil-bugol - please tag Yazar here in the comments so he can confirm his resignation as an organizer. Thank you.

**Comment by aliok** [comment]
+1 from me. Thanks for driving this Halil.

**Comment by eminalemdar** [comment]
+1 from me as well.

**Comment by koksay** [comment]
+1 from me

**Comment by AudMonte01** [comment]
Thank you for providing the majority vote. I have removed Firat from the chapter as an organizer.
