### ISSUE TITLE
[Organizer Request] Remove Organizer Sao Paulo

### ISSUE THREAD

**Issue by krol3** [cncf/communitygroups#53]
### Name of chapter inquiring about

Cloud Native Sao Paulo

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Community Link: https://community.cncf.io/cloud-native-sao-paulo/

### Tell us why you want to be added or removed from the chapter

Yago Nobre moved to another city, unfortunately he can't participated anymore of the organization.
Please remove Yago Nobre from the organizers list. 

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you for submitting this @krol3 - please tag Yago here and have them confirm their resignation.

**Comment by AudMonte01** [comment]
Following up on this request, @krol3 - I know you are traveling right now.

**Comment by k8tgreenley** [comment]
@krol3 can you please tag Yago's GitHub in this ticket for confirmation to remove

**Comment by krol3** [comment]
Good afternoon @k8tgreenley and @AudMonte01  I will put this information soon. Thanks for the remind

**Comment by yagonobre** [comment]
I no longer live in São Paulo, so I can't actively help with this chapter anymore. @krol3, thank you for continuing this work!

**Comment by AudMonte01** [comment]
Thank you for writing, @yagonobre - I have removed you from the chapter as an organizer. This ticket is now closed.
