### ISSUE TITLE
[Organizer Request] Add Sai Linn Thu as an Organizer to Singapore chapter

### ISSUE THREAD

**Issue by sailinnthu** [cncf/communitygroups#56]
### Name of chapter inquiring about

Cloud Native Singapore

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Sai Linn Thu (https://www.linkedin.com/in/sailinnthu/)
<img width="801" alt="Screenshot 2024-05-07 at 7 57 26 AM" src="https://github.com/cncf/communitygroups/assets/11147428/130da6e0-4c16-4bea-bb1c-6bfebfdb7857">

- Senior Solutions Architecture Specialist, HashiCorp
- CNCF Ambassador (https://www.cncf.io/people/ambassadors/?_sft_lf-country=sg)
- Co-Chair KubeDay Singapore

### Tell us why you want to be added or removed from the chapter

I, Sai Linn Thu, would like to join as co-organizer for Cloud Native Singapore Chapter.
Why I am excited to be an ambassador: Singapore and ASEAN Region need more active and organized meetups around cloud native community. The activities are behind compare to US, EMEA and ANZ Region. As an ambassador and organizer, I will continue to create more awareness and advocate CNCF projects in Singapore and ASEAN Region. I was also participated for the KubeDay Singapore as one of the event chairs, and continue to contribute. I’m very proud of being CNCF Ambassador and representing CNCF in Singapore and APAC Region.
I also would like to contribute CNCF Projects in Burmese Language.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by sailinnthu** [comment]
ping request @k8tgreenley @AudMonte01

**Comment by AudMonte01** [comment]
Hello @sailinnthu - It is great to see you apply to bring your efforts to the existing chapter. I am copying @yongkanghe here who organizes it to see if he has any questions for you.

**Comment by yongkanghe** [comment]
Thanks @sailinnthu for your interest! I'm in discussion with @AudMonte01 @k8tgreenley about the plan to go forward. In a short, I'm very strict in accepting anyone to be part of the community organizing team. Everyone will be starting as a volunteer for a few events. Then, based on the contribution, we will review and add her/him as an event organizer to begin with, then possibly associate co-organizer, then co-organizer again based on the active involvements. With the right process in place, it proved it worked very well for the community to grow effectively.

**Comment by sailinnthu** [comment]
@yongkanghe @AudMonte01 @k8tgreenley 
Thanks for your reply. I'd like to clarify that starting as a volunteer for a few events, May I know which community groups you're referring to ?

- https://community.cncf.io/singapore/  (there is no event running since Jul 2023)
- https://www.meetup.com/k8s-sg/ (this is active and I contribute and speak there time to time)

**Comment by AudMonte01** [comment]
That is great that you speak regularly at the current K8SUG! Then the collaboration for you to first join as a speaker, should not be an issue.
Cc @yongkanghe

**Comment by k8tgreenley** [comment]
@yongkanghe can you please confirm the steps for Sai to get involved to become a co-organizers?

**Comment by yongkanghe** [comment]
@k8tgreenley, at this point, we're not adding any additional co-organizers. We already have a very strong team with Fazir @fazirmfahmy and Ritesh @rhegde1 etc., who have been contributing to the Kubernetes community for over a year now.

We appreciate @sailinnthu's interest in joining us and would be happy to welcome him as a volunteer initially.

**Comment by k8tgreenley** [comment]
@yongkanghe, per our conversation, please provide the steps for Sai to volunteer to become an organizer. What kind of volunteer help is needed at this time?

**Comment by k8tgreenley** [comment]
@sailinnthu I have confirmed with Yongkang that @fazirmfahmy @rhegde1 will follow up with next steps for volunteering. Please let me know if you have questions.
