### ISSUE TITLE
[Organizer Request] Add new Organizers Team to Bergen chapter

### ISSUE THREAD

**Issue by Starefossen** [cncf/communitygroups#58]
### Name of chapter inquiring about

Bergen

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

| Name | Slack | GitHub | LinkedIn | CNCF Profile |
|------|-------|--------|----------|--------------|
| Anders Runningen | [@Anders Runningen](https://cloud-native.slack.com/team/U05BY0HP4KG) | @AndersRunningen | https://www.linkedin.com/in/%C3%B8yvind-randa-50722310/ | https://community.cncf.io/u/mz3f8e |
| Andreas Thuen | | @andreasthuen | https://www.linkedin.com/in/andreasthuen/ | https://community.cncf.io/u/m49e2a/ |
| Bjørge Solli | [@Bjørge Solli](https://cloud-native.slack.com/team/U0395DHG6TE) | @bjorges | https://www.linkedin.com/in/bjorgesolli/ | https://community.cncf.io/u/mcuqnt/ |
| Odin Herjan | | @odin-masta | https://www.linkedin.com/in/odinherjan/ | |
| Øyvind Randa | [@Øyvind Randa](https://cloud-native.slack.com/team/U0212L5DM3K) | @randax | https://www.linkedin.com/in/%C3%B8yvind-randa-50722310/ | https://community.cncf.io/u/m6wpsd |

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you, Hans ~
It would be great if each organizer can provide proof of having recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/). Simply having them comment on this ticket. Thanks again!

**Comment by AndersRunningen** [comment]
I have done the course 👍

**Comment by bjorges** [comment]
I have completed the LFC102 course.

**Comment by randax** [comment]
I have completed the LFC102 course

lør. 18. mai 2024 kl. 12:59 skrev Bjørge Solli ***@***.***>:

**Comment by k8tgreenley** [comment]
@AndersRunningen @bjorges @randax you have all been added to the Bergen chapter as organizers.

@andreasthuen @odin-masta please let me know when you complete and I will add you to the chapter as well.

**Comment by andreasthuen** [comment]
Hi, @AudMonte01 I have just completed the course now :)

**Comment by odin-masta** [comment]
@k8tgreenley LFC102 Course completed ✓

**Comment by Starefossen** [comment]
@AudMonte01 can you add them to the Slack channel as well?

**Comment by AudMonte01** [comment]
I have able to add 3 out of 5 to the exclusive organizer channel, and invite the other two to the CNCF Slack workspace. Closing out this ticket.
