### ISSUE TITLE
[Group Request] Create a new chapter - Innsbruck, Austria

### ISSUE THREAD

**Issue by UnseenWizzard** [cncf/communitygroups#59]
### City or location name for your CNCG

Cloud Native Innsbruck

### What country do you want to start your community group in?

Austria

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

**Nico Riedmann**
📧 nico@riedmann.dev
🏢 Dynatrace
:octocat: https://github.com/UnseenWizzard
LinkedIn: https://www.linkedin.com/in/nico-riedmann/
CNCF slack: Nico Riedmann
Community Profile: https://community.cncf.io/u/mp8fw9

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

**Johannes Kleinlercher**
📧 johannes@kleinlercher.at
🏢 suXess information technologies gmbh
:octocat: https://github.com/jkleinlercher
LinkedIn: https://www.linkedin.com/in/johannes-kleinlercher/
CNCF slack: Johannes Kleinlercher
Community Profile: https://community.cncf.io/u/mctbx6/

---

**Christoph Stanger**
📧 [christoph@stanger.eu.com](mailto:christoph@stanger.eu.com)
🏢 Google
:octocat: https://github.com/cstanger
LinkedIn: https://www.linkedin.com/in/cstanger/
CNCF slack: Christoph Stanger
Community Profile: https://community.cncf.io/u/mwwdjw

---

**Andreas Doblander**
📧 [andreas.doblander@dynatrace.com](mailto:andreas.doblander@dynatrace.com)
🏢 Dynatrace
:octocat: https://github.com/AndreasDoblander
LinkedIn: https://www.linkedin.com/in/andreas-doblander-813b8849/
CNCF slack: Andreas Doblander
Community Profile: https://community.cncf.io/u/mckyhf/

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

(see field above as it's >2)

### If you already run a meetup, please link it here

I (Nico) co-organize
* [Agile International Graz](https://www.meetup.com/agile-international-graz/) an Agile meetup held locally in Graz and remote every ~2 months
* An online book-club as part of the [New Leadership Community](https://www.meetup.com/New-Leadership/) - a local leadership and new work meetup in Graz, Austria, which I co-organized before moving to Innsbruck, Austria. Now I just continue organizing the book-club as other community meetups are in person.

### What is your mission statement or objective for this new chapter?

We want to create a space for the cloud-native community in Innsbruck to get together and exchange. While this a large and ever-growing group of people and companies that are working in and around cloud-native, there are no existing community groups.

For this, we plan to host meetups every 2-3 months - a higher frequency seems too much for the size of community and speaker pool that we currently expect to have here.

We also intend to align and exchange with other Austrian communities and the Cloud Native Austria parent community. 

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by UnseenWizzard** [comment]
Open ToDos for us:

- [ ] add GitHub & CNCF profile links for all organizers
- [ ] finish "Inclusive Open Source Community Orientation (LFC102)" course

**Comment by UnseenWizzard** [comment]
We would like to organize this chapter as a sub-group of [Cloud Native Austria](https://community.cncf.io/cloud-native-austria/) like the Graz and Vienna chapters. This is already aligned with the organizers who already supported us in organizing a first [Cloud Native Innsbruck event](https://community.cncf.io/events/details/cncf-cloud-native-austria-presents-meetup-cloud-native-innsbruck/) late last year.

**Comment by jkleinlercher** [comment]
Johannes Kleinlercher
📧 [johannes@kleinlercher.at](mailto:johannes@kleinlercher.at)
🏢 suXess information technologies gmbh
:octocat: https://github.com/
LinkedIn: https://www.linkedin.com/in/johannes-kleinlercher/
CNCF slack: Johannes Kleinlercher
Community Profile: https://community.cncf.io/u/mctbx6/

**Comment by AndreasDoblander** [comment]
Andreas Doblander
📧 [andreas.doblander@dynatrace.com](mailto:andreas.doblander@dynatrace.com)
🏢 Dynatrace
:octocat: https://github.com/AndreasDoblander
LinkedIn: https://www.linkedin.com/in/andreas-doblander-813b8849/
CNCF slack: Andreas Doblander
Community Profile: https://community.cncf.io/u/mckyhf/

**Comment by cstanger** [comment]
Christoph Stanger
📧 [christoph@stanger.eu.com](mailto:christoph@stanger.eu.com)
🏢 Google
:octocat: [https://github.com/cstanger](https://github.com/cstanger)
LinkedIn: https://www.linkedin.com/in/cstanger/
CNCF slack: Christoph Stanger
Community Profile: [https://community.cncf.io/u/mwwdjw](https://community.cncf.io/u/mwwdjw)

**Comment by k8tgreenley** [comment]
I appreciate the resubmission and clarification. We are confirming on our end with the chapters to add your request to the parent chapter.

**Comment by AudMonte01** [comment]
Thank you everyone. I have created the chapter and everyone has been added accordingly. You all should have received an automated welcome email from me.

Before I unhide the chapter, please confirm that @jkleinlercher, @cstanger, and @AndreasDoblander have completed the open source inclusive course linked above.

**Comment by UnseenWizzard** [comment]
Thanks a lot @AudMonte01!
AFAIK @AndreasDoblander completed the course today, @jkleinlercher @cstanger will update here once they've done it/if they have already.

**Comment by AndreasDoblander** [comment]
Yes, I've completed LFC102 🙂
________________________________

**Comment by cstanger** [comment]
Yes, I've completed LFC102

**Comment by AudMonte01** [comment]
Excellent - that chapter is ready and viewable: https://community.cncf.io/cloud-native-innsbruck/

You are all added to the organizer channel in the Slack workspace where announcements will occur. Thank you in advance for helping making cloud native ubiquitous.

I am now closing this issue.

**Comment by jkleinlercher** [comment]
Yes, I've completed LFC102
