### ISSUE TITLE
[Organizer Request] Add Organizer Name

### ISSUE THREAD

**Issue by vishalanarase** [cncf/communitygroups#60]
### Name of chapter inquiring about

Cloud Native Pune

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Name: Vishal Anarase
Email: iamvishalanarase@gmail.com
Company: Civo
Github URL: https://github.com/vishalanarase
LinedIn URL: https://www.linkedin.com/in/vishal-anarase-623707104
CNCF Slack: Vishal Anarase
CNCF Community: https://community.cncf.io/u/mjfqfx/\#/about

### Tell us why you want to be added or removed from the chapter

I Vishal Anarase, would like to join as co-organizer for Cloud Native Pune Chapter to actively participate in its initiatives and contribute to the community's growth. With eight years of software development experience and contributions to projects like Kubernetes cluster autoscaler and Percona operators, I bring valuable insights and a passion for collaborative work. I look forward to engaging with like-minded professionals and contributing to the advancement of cloud-native computing in Pune.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by vishalanarase** [comment]
@AudMonte01 I'm not able to assign this issue to you, Can you assign it to yourself please.

**Comment by AudMonte01** [comment]
I am looping in the current organizers @Sagar2366 and @vipulvc08 .
I would assume they would like to see you first attend their meetups to showcase how you can help on a 1-off bases to start.
Anything upcoming should be listed on [their chapter page here](https://community.cncf.io/pune/).
Thank you!

**Comment by k8tgreenley** [comment]
@Sagar2366 and @vipulvc08 please provide the next steps in terms for @vishalanarase to start volunteering. Possibly a plan to meet at the next meetup to make initial introductions?

**Comment by vishalanarase** [comment]
@AudMonte01 I have personally contacted @Sagar2366 and @vipulvc08 on CNCF Slack, but I haven't received a reply yet. Could you assist in facilitating the introduction or suggest any other steps I should take?

Thank you for your help!

**Comment by Sagar2366** [comment]
@vishalanarase We both were on leave last week.
Audra and I already had a meeting and we shared the next steps. Post our meeting, she replied above with the next steps.
Let me put the steps again -
The starting point for you would be to attend the meetups regularly and make a contribution to the local community chapter.
 
We have volunteers working with us for years and based on their performance and contribution we add them to the next role.

I hope this gives you starter points on where to start now and clarity why we follow this process.

Thank You.

**Comment by vishalanarase** [comment]
Hi @Sagar2366,

Thank you for the update and clarification.

I will make sure to attend the meetups regularly and contribute to the local community chapter as much as I can. I appreciate the opportunity and look forward to getting started.

Additionally, could you please share how you manage to organize the meetups? Is there a community meeting where this is discussed? If so, I would like to attend to understand the process better and to see how I can help.

Thanks again for your guidance!

**Comment by Sagar2366** [comment]
Let me share the CNCG Pune community chapter link here for you - https://community.cncf.io/pune/
Feel free to join the community chapter to get all future updates.

**Comment by vishalanarase** [comment]
Hi @Sagar2366,

Thank you for sharing the CNCF Pune community chapter link. I have already joined and am following the updates.

I am particularly interested in understanding how you manage to organize the meetups. Could you please share more details on this? Is there a community meeting where these details are discussed? I would like to attend.

Thank you!

**Comment by Sagar2366** [comment]
For now, the above information should be enough to start with.
Most of the discussions about upcoming meetups and other things we discussed during an in-person meetup.

**Comment by vishalanarase** [comment]
Thank you for the information.

I will make sure to attend the upcoming meetup and contribute wherever possible. I'm looking forward to being an active part of the community and helping out with the events.

Thanks for your support!

**Comment by k8tgreenley** [comment]
Thank you @Sagar2366 for replying with next steps

@vishalanarase please work with Sagar and Vipul by joining upcoming meetups

**Comment by vishalanarase** [comment]
Hi @k8tgreenley,

Thank you for your response and guidance. I appreciate the next steps provided by @Sagar2366.

However, I didn't expect this issue to be closed yet. I would like to keep it open until I have successfully joined as a co-organizer. This will help ensure that all necessary steps are tracked and completed, which is the intention of this issue.

Thank you for your understanding and support.

**Comment by k8tgreenley** [comment]
@vishalanarase, you can open a new ticket after you have been attending meetups regularly and have been working with Sagar and Vipal on volunteering.

**Comment by vishalanarase** [comment]
@Sagar2366 I see Vipul is being removed in the [issue](https://github.com/cncf/communitygroups/issues/404) 

There is any opportunity I can join and contribute!
