### ISSUE TITLE
[Group Request] Create a new chapter in Queretaro 

### ISSUE THREAD

**Issue by parraletz** [cncf/communitygroups#61]
### City or location name for your CNCG

Queretaro

### What country do you want to start your community group in?

Mexico

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Alex Parra, parraletz@gmail.com, OCC, https://github.com/parraletz, https://linkedin.com/in/parraletz, CNCF Slack : Alex Parra

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Jaime Omar Montenegro,omar.mx.1990@gmail.com, Epam, https://www.linkedin.com/in/jm19/

### If you already run a meetup, please link it here

https://www.meetup.com/es-ES/cloud-native-queretaro/

### What is your mission statement or objective for this new chapter?

Our mission is to spark a dynamic community ignited by the power of cloud-native technologies. We're all about connecting tech enthusiasts and professionals to exchange cutting-edge insights, hacks, and stories in the cloud tech sphere. Join us to dive into a world where beginners morph into experts, and every voice fuels the next wave of cloud innovation. Let's innovate, collaborate, and elevate the cloud experience together!

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by parraletz** [comment]
the original submission was : which was 2/28/2024 22:15:51. 

best regards

**Comment by k8tgreenley** [comment]
@parraletz please have Jamie create a profile on community.cncf.io

**Comment by AudMonte01** [comment]
Hello @parraletz - this chapter had already been created: https://community.cncf.io/queretaro/

It looks like Jaime Omar still needs to create a profile per Katie's comment above. Please comment here once this is  complete.
