### ISSUE TITLE
[Group Request] Create a new chapter in Cluj-Napoca, Romania

### ISSUE THREAD

**Issue by Mirciulica15** [cncf/communitygroups#62]
### City or location name for your CNCG

Cluj-Napoca

### What country do you want to start your community group in?

Romania

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Mircea Talu, talumircea13@gmail.com, Accesa IT Systems, https://github.com/mirciulica15/, https://www.linkedin.com/in/mircea-talu-679845243/, CNCF Slack - need to be invited, https://community.cncf.io/u/mj2t3c/#/about

### What is your mission statement or objective for this new chapter?

In the heart of Transylvania, we pioneer Cloud Native innovation. Our mission is to welcome enthusiasts of any skill level to the CNCF landscape. Within our open community, collaboration is key, learning is constant, and curiosity is inspired.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by k8tgreenley** [comment]
@Mirciulica15 will you have any co-organizers at this time?

**Comment by Mirciulica15** [comment]
Hello @k8tgreenley, currently I don't have any co-organizers. Is this an issue? Thank you!

**Comment by AudMonte01** [comment]
Hello @Mirciulica15 - thank you for resubmitting your request after we spoke in Paris. I am pleased to let you know that I have created this chapter for you. You should have just received an automated welcome email from me. Please follow the instructions there, and I will close this ticket.
