### ISSUE TITLE
[Group Request] New chapter request for Athens, Greece

### ISSUE THREAD

**Issue by kouk** [cncf/communitygroups#63]
### City or location name for your CNCG

Cloud Native Athens

### What country do you want to start your community group in?

Greece

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Konstantinos Koukopoulos, Persado, https://github.com/kouk, https://www.linkedin.com/in/kkoukopoulos, Konstantinos Koukopoulos in CNCF Slack, https://community.cncf.io/u/mp6mc3/

SRE/MLOps at Persado

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Konstantinos Tsakalozos, Canonical, https://github.com/ktsakalozos, https://www.linkedin.com/in/konstantinos-tsakalozos-92657a24/, Konstantinos Tsakalozos in CNCF Slack, https://community.cncf.io/u/mnxerv/

 Engineering Manager for Kubernetes at Canonical Ltd. 

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Christos Markou, Elastic, https://github.com/ChrsMark, https://www.linkedin.com/in/christos-markou-a6542ab4/, Christos Markou in CNCF Slack, https://community.cncf.io/u/mn9kxy/

 Senior Software Engineer at Elastic | CNCF Ambassador

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Meg Stefouli-Vozza, Lovelace Engineering, https://github.com/megilicious, https://www.linkedin.com/in/megstefuli/, Meg Stefouli in CNCF Slack, https://community.cncf.io/u/mgq24h/

### If you already run a meetup, please link it here

https://www.meetup.com/Athens-Kubernetes-Meetup/

### What is your mission statement or objective for this new chapter?

Foster our local community interested in Kubernetes, CI/CD, Container Orchestration, Microkernels, Unikernels and Cloud Native applications.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by k8tgreenley** [comment]
@kouk Good news it looks like we previous hosted your meetup on community.cncf.io but the final steps for migration didn't happen in 2020. Your group isn't alone when it came to this step. 

Your meetup.com has 5 organizers but you only listed 3 in the issue, will we need to add the additional 2 or will it only be 3 organizers?

**Comment by kouk** [comment]
Hi @k8tgreenley , those other organizers are in a "Emeritus" status, and not active currently.  I will reach out to them in case they want to get involved again, but in case they do not, is it ok if we leave them as meetup.com organizers?

**Comment by AudMonte01** [comment]
Thank you for this chapter request @kouk - Meg Stefouli had previously spoke to me about a KCD in Greece, and I see this collaboration about a [Cloud Native Day Greece in Slack](https://cloud-native.slack.com/archives/C06670402KC). Do you want to add Meg as an organizer?

**Comment by kouk** [comment]
@AudMonte01 yes, we have two parallel efforts that are converging into one. I will add @meglicious as an organizer.

**Comment by AudMonte01** [comment]
Excellent - thank you, @kouk 

Next steps is, we will need everyone here (aside from you, Konstantinos to confirm they have take the Open Source Inclusivity course mentioned above.

**Comment by ChrsMark** [comment]
I confirm: https://www.credly.com/badges/de20e6d2-368e-46cd-ab4b-a0b742391bbd

**Comment by ktsakalozos** [comment]
I am certificated now! ID: LF-o1sm68bpuy

**Comment by AudMonte01** [comment]
Thank you, everyone. Hello @meglicious - can you please confirm you have taken the course? I believe you have given the past KCD organization.

**Comment by meglicious** [comment]
Hello, I confirm that I do have completed the course. https://www.credly.com/badges/9e9907e4-2a36-4820-ad68-5497b12d239f/public_url

**Comment by AudMonte01** [comment]
Excellent - this chapter has been revived and the three of you have been added as organizers. You each should have received an automated welcome email from me with further instructions.

@kouk - please add a profile picture of yourself here https://community.cncf.io/u/mp6mc3/ since you will be shown as an organizer on the front-end of the chapter page. For now, I have hidden your profile.

This ticket is now closed.
