### ISSUE TITLE
[Group Request] Cloud Native Galicia

### ISSUE THREAD

**Issue by exorcito** [cncf/communitygroups#64]
### City or location name for your CNCG

Vigo

### What country do you want to start your community group in?

Spain

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

I'm Alberto Lorenzo, I've been Developer, Sysadmin, DBA, tech lead  and I've been the last 8 years as a cloud architect for several companies. I love to learn and use new technologies that allow me to do my job better and better.

My email is alberto@alorenzo.es and I am working as Head of Infra for Alice Biometrics, a startup focused on artificial intelligence for biometric verification.

Github URL: [https://github.com/exorcito](https://github.com/exorcito)
Linkedin URL: [https://www.linkedin.com/in/albertolamora/](https://www.linkedin.com/in/albertolamora/)
CNCF Slack workspace name: Alberto Lorenzo ( exorcito@gmail.com )
CNCF Profile LInk: https://community.cncf.io/u/m9axt4/#/about

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

I have several people who could help me but more for organizing talks, if it is necessary to have co-organizers as a requirement I can discuss it with them as well.

### What is your mission statement or objective for this new chapter?

I would like to expand the Cloud Native community by creating a new regional/local community here, in Galicia ( Spain ).

Here in Galicia there are many universities, people working on the cloud and above all programming communities but there are hardly any groups about the Cloud even though there are important companies like Inditex and Stellantis located here.

In fact there are currently meetups like the ones organized mainly focused for developers that are working very well, so the community is very active ( for ex: https://www.meetup.com/es-ES/aindustriosa/ ) . Proof of all this is that Python Spain will also be held in Vigo.

Therefore I believe that both in Vigo and in the region of Galicia is the ideal place to create a group and begin to mobilize people to create networking, added value, raise awareness and help align these professionals with the technological advances that are emerging almost daily through events.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by exorcito** [comment]
Any update of this pls?

**Comment by AudMonte01** [comment]
Thank you for your patience, @exorcito.

The reason this has taken me so long is we have another group titled, Cloud Native Iberia, but they are mostly hosting meetups in Madrid. That said, I can sync with them to see if we can change the naming convention of their chapter, as I understand Galicia is in the Iberian region. Please confirm.

**Comment by exorcito** [comment]
Iberia always represents the whole of Spain, it is not a region, it is a whole country. For me Cloud Native Iberia would be renamed to Cloud Native Madrid. Cloud Native Galicia is equivalent to Cloud Native Rioja, for example, which already exists but refers to two different and very distant regions of Spain.

**Comment by exorcito** [comment]
Any update of this?

**Comment by AudMonte01** [comment]
Thank you for your patience, @exorcito - so far the team definitely wants a name change to Cloud Native Madrid, but there is a discrepancy on meetup.com that is the current blocker and caused confusion in the past. We are working through this, and thank you for your patience.

It is my understanding Spain is essentially closed down for the summer, so there is no rush since finding a venue will take time with sponsors, etc? Please correct me if I am wrong here or if you have alternate plans like using a University during summer break.

**Comment by exorcito** [comment]
Ok Aura, thanks for the explanation.

The main idea is to take advantage of the summer to organise speakers, communicate with other meetups and groups, generate synergies with them and see initiatives with the group already created to start in September. 

There is no urgency but as soon as possible will help to organise everything. 
Once again thank you very much

**Comment by AudMonte01** [comment]
Hi Alberto - thank you for your patience. I have created a chapter for you, and you should have just received an automated welcome email from me with further steps.

I also host office hours weekly on Fridays if the hour works for you, you can join anytime within it: https://community.cncf.io/e/mya67u/

This ticket/issue is now closed.
