### ISSUE TITLE
[Organizer Request] Add Alessandro Pilotti as Organizer

### ISSUE THREAD

**Issue by romina2001** [cncf/communitygroups#65]
### Name of chapter inquiring about

Timisoara

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Alessandro Pilotti 
company: CloudBase Solutions
email: apilotti@cloudbasesolutions.com
https://www.linkedin.com/in/alessandropilotti/
https://github.com/alexpilotti

### Tell us why you want to be added or removed from the chapter

Alessandro is a CNCF contributor. He contributed to several CNCF projects repositories

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [ ] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [ ] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by romina2001** [comment]
Not sure why I cannot add  @AudMonte01  as assignee.

**Comment by AudMonte01** [comment]
Thank you for submitting this @romina2001 - it looks like [alexpilotti](https://github.com/alexpilotti) is already an organizer, he just needs to update his profile on community.cncf.io to have a headshot (photo) since he is forward-facing on the [chapter page](https://community.cncf.io/timisoara-romania/).

Mihnea Popescu and Andrei Ghilencea should do the same

**Comment by k8tgreenley** [comment]
@romina2001 I am following up on if @alexpilotti, Mihnea, and Andrei have updated their profiles?

**Comment by alexpilotti** [comment]
@AudMonte01 @k8tgreenley I updated my profile, please let me know if anything needs to be changed. Thanks!

**Comment by romina2001** [comment]
@k8tgreenley Mihnea and Andrei updated their profiles. Also Alessandro.

**Comment by AudMonte01** [comment]
Excellent - thank you, everyone. I am now closing this ticket.
