### ISSUE TITLE
Remove Manish from Cloud Native Hooghly

### ISSUE THREAD

**Issue by hrittikhere** [cncf/communitygroups#66]
### Name of chapter inquiring about

Cloud Native Hooghly

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Hrittik Roy, Loft Labs | CNCF Ambassador 

### Tell us why you want to be added or removed from the chapter

Manish Kumar Barnwal ( @imanishbarnwal )  cannot continue as an organizer for CNC Hooghly and has requested to be removed from the organization.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [ ] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [ ] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [ ] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [ ] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [ ] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [ ] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [ ] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by imanishbarnwal** [comment]
Yes, thanks for creating the issue @hrittikhere

**Comment by k8tgreenley** [comment]
@imanishbarnwal @hrittikhere thank you both for creating and confirming in this issue. I have removed @imanishbarnwal from the organizer list.
