### ISSUE TITLE
[Organizer Request] Add Ali Ok to Ankara chapter

### ISSUE THREAD

**Issue by aliok** [cncf/communitygroups#67]
### Name of chapter inquiring about

Cloud Native Ankara

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Ali Ok, Red Hat, https://github.com/aliok/, https://www.linkedin.com/in/aliok/, https://cloud-native.slack.com/team/U030UQH8QNR, https://community.cncf.io/u/m52hgw/#/about

### Tell us why you want to be added or removed from the chapter

I will move to Ankara this summer. I want to continue what I've been doing in Istanbul chapter in Ankara.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by aliok** [comment]
@AudMonte01 I am in Istanbul chapter.
Can I be both in Ankara and Istanbul chapters? I want Ankara chapter to work closely with the Istanbul one.

**Comment by AudMonte01** [comment]
Thank you for submitting this request @aliok , and offering support @halil-bugol - I am tagging the current organizer who was just enabled this year, and may need the help.

@sdtslmn - Introducing Ali and Halil. They are both organizers of [KCD Istanbul](https://kcd.istanbul/), and the CNCF [Istanbul chapter](https://community.cncf.io/istanbul/). I hope you will be able to collaborate with Ali on organizing meetups for Ankara.

**Comment by aliok** [comment]
Thanks for the intro @AudMonte01 
@sdtslmn I see in your profile that you live in Dubai. Are you able to organize events/meetups/etc. in Ankara?

**Comment by sdtslmn** [comment]
> Thanks for the intro @AudMonte01 @sdtslmn I see in your profile that you live in Dubai. Are you able to organize events/meetups/etc. in Ankara?

Hello sorry, I was away because of a health issue. 
I frequently travel between Ankara and Dubai, but I spend most of the year in Ankara.
I will check all the conversations this week

**Comment by AudMonte01** [comment]
Thank you for the response, @sdtslmn. Please schedule some time with Ali here, a CNCF Ambassador with community organization experience. It would be great for you to learn how you both can best collaborate.

**Comment by aliok** [comment]
@sdtslmn Let's connect in the 2nd half of July? Would that work for you?

**Comment by AudMonte01** [comment]
Hi @aliok and @sdtslmn - were you both able to connect?

**Comment by aliok** [comment]
@AudMonte01 we weren't able to.

@sdtslmn what would work for you?

**Comment by AudMonte01** [comment]
Since @sdtslmn is not responsive, and the chapter activity has been 0 since we enabled him, I will remove @sdtslmn as an organizer and add @aliok if there is no response by the end of this week.

Kind regards,
Audra

**Comment by sdtslmn** [comment]
Hello Audra

My wife started cancer treatment. As of today, we had the last session. I
was a little busy with her and had to deal with my daughter  so that I
couldn't pay much attention to the chapter up to know.
However, I want to align with Ali within this month according to
his availability and start activities as of the beginning of September as a
chapter.

**Comment by AudMonte01** [comment]
Thank you for the response and insight, @sdtslmn. I am glad to hear of her recovery.

We look forward to you and Ali's communication.

**Comment by AudMonte01** [comment]
Hello @aliok - can you confirm @sdtslmn has reached out?

**Comment by aliok** [comment]
Hi @AudMonte01 

Unfortunately no. I wish him and his wife well. Family is obviously more important than work.

**Comment by AudMonte01** [comment]
100% agree

In the meantime, I am adding you as an interim organizer, and Sedat can always come back and participate when he is ready.

That said, you should have received an automated welcome email from me just now with further instructions.

This issue is closed for now.

**Comment by aliok** [comment]
@sdtslmn ,

@expeto and @kemrec are going to lead the Ankara chapter. See https://github.com/cncf/communitygroups/issues/251

You might want to reach out to them and Audra to get involved.
