### ISSUE TITLE
[Group Request] New chapter request for Jalgaon, India

### ISSUE THREAD

**Issue by UtkarshUmre** [cncf/communitygroups#68]
### City or location name for your CNCG

Kubernetes & Cloud Native Jalgaon

### What country do you want to start your community group in?

India

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

My name is Utkarsh Umre, and I am an open-source contributor to projects such as Keptn and Glasskube, both of which are CNCF projects. Additionally, I advocate for cloud-native and DevOps, meaning I introduce newcomers to the ecosystem, thereby helping to spread awareness of CNCF and cloud-native technologies in my area. Apart from that, I am interested in organizing a CNCF local chapter in my area to further raise awareness about CNCF, arrange events, and encourage more individuals to join the community. My beliefs align with the CNCF motto, which aims to make cloud-native technologies ubiquitous. Here are my contact links for email [ utkarshumre@outlook.com ], GitHub [ [https://github.com/UtkarshUmre](https://github.com/UtkarshUmre) ], LinkedIn [ [https://in.linkedin.com/in/utkarsh-umre-250293222](https://www.linkedin.com/in/utkarsh-umre-250293222) ], and Utkarsh Umre in CNCF Slack channel, https://community.cncf.io/u/mbb246/

### What is your mission statement or objective for this new chapter?

My mission for this new CNCF chapter is to raise more awareness about CNCF and the cloud-native ecosystem, as well as cloud-native technologies in my area. I aim to engage the community, spread education among them, and foster a great community that can lead to further advancements in CNCF and the cloud-native ecosystem. My objective and goal are to create a thriving community of like-minded individuals who will contribute to future advancements in CNCF and the cloud-native ecosystem.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Hello @UtkarshUmre - thank you for your interest in organizing a chapter. And thank you for following all the proper steps. 

The good news for you, is there is no current chapter in Jalgaon that has been hosted on community.cncf.io or meetup.com. With that, I will move forward in creating this new chapter for you as an organizer, as your experience and LinkedIn connections showcase that you would be a great candidate.

Before I do so, please let me know which is the proper location for me to assign to this chapter?
<img width="330" alt="Screenshot 2024-06-12 at 10 30 40 AM" src="https://github.com/cncf/communitygroups/assets/107572090/caadbd7c-7690-4eb8-9df9-1dde1df74e92">

**Comment by UtkarshUmre** [comment]
Hey, thank you, @AudMonte01  The correct location is the first option: "Jalgaon, Maharashtra, India."

**Comment by AudMonte01** [comment]
Hello @UtkarshUmre - I have created "Cloud Native Jalgaon" as Kubernetes is Cloud Native. You should have just received an automated welcome email from me with further instructions. If you can attend my office hour this Friday, it would be great to learn ways on how to get started with your first meetup. https://community.cncf.io/e/mjh9z7/

I am now closing this issue.
