### ISSUE TITLE
remove KCD DC organizers

### ISSUE THREAD

**Issue by mcascio** [cncf/communitygroups#69]
### Name of chapter inquiring about

KCD Washington DC

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Matthew Cascio

### Tell us why you want to be added or removed from the chapter

Could you remove these organizers from our chapter, please? We've had 16 meetings so far and they haven't attended any yet.  They're not responding to inquiries by slack or email either.
Amit Sagtani
Ryan Kelley
John Guthrie

### Code of Conduct

- [ ] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [ ] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [ ] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [ ] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [ ] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [ ] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [ ] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [ ] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by k8tgreenley** [comment]
@mcascio is this for the CNCG or the KCD?

**Comment by mcascio** [comment]
@k8tgreenley this is for KCD Washington DC
https://community.cncf.io/kcd-washington-dc/
Thanks!

**Comment by AudMonte01** [comment]
Hi @mcascio - please comment within your KCD ticket for now, and tag the mentioned organizers for their commentary. Whil this this repo us for CNCGs, but we will soon have an organizer request form for KCDs specifically
