### ISSUE TITLE
[Group Request] Create a new chapter Vale do Paraíba / SP

### ISSUE THREAD

**Issue by thehoneycomb** [cncf/communitygroups#70]
### City or location name for your CNCG

Cloud Native Vale do Paraíba - SP

### What country do you want to start your community group in?

Brazil

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Anderson Souza Luna, andersonluna@gmail.com, Zenvia, https://github.com/thehoneycomb, https://www.linkedin.com/in/andersonluna, I need to be invited to CNCF Slack workspace, https://community.cncf.io/u/mne3rn/#/about

As Audra Montenegro requested by email, the date of my original submission was 4/5/2024 22:47:41.

Best Regards,
Anderson Luna

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Fabricio Santos, fabricio.santos@nextlayer.com.br, CYCLOPS, https://www.linkedin.com/in/fabricio-santos-058b817,  https://community.cncf.io/u/m5rdm6/#/about

### What is your mission statement or objective for this new chapter?

 we are tech enthusiasts and loves opensource,
our mission is to support the development and growth of cloud native technologies and community in Vale do Paraíba by fostering a local community that contributes to and benefits from open source and collaborative technologies. We aim to provide a forum for networking, sharing ideas, and promoting the CNCF's values, diversity, and solutions. Through workshops, meetups, and collaborations, we seek to empower the community and technology companies in our region to innovate and thrive in a cloud native world.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Thank you for your submission @thehoneycomb - I am looping in one of the lead organizers of the Sao Paulo chapter to:
* showcase your interest in collaborating
* or bring awareness to me about the location/distance between the two chapters since Sao Paulo has over 12 million people in it

Cc @krol3

**Comment by krol3** [comment]
Hi @AudMonte01 👋 and @thehoneycomb , nice to meet you 

It will be my pleasure to help you in any doubt or support that you need. I will contact you to chat 🙂

**Comment by AudMonte01** [comment]
Thank you, @krol3 
Please let me know here, the result of your conversation

**Comment by thehoneycomb** [comment]
Hi! Audra,

How are you doing?

I am already in contact with @krol3 , and through her, it is possible to have the chapter in the Vale do Paraíba region due to the distance between Vale and the city of São Paulo.

Well, can I start the work here already, or do I still need some more approval?

How should we proceed? Can we create our LinkedIn and Instagram pages independently and report to you or to her?

Please, @krol3 cloud you confirm?

Best,

**Comment by krol3** [comment]
Hi @thehoneycomb and @AudMonte01 , happy to collaborate with the new chapter with any doubt or support.

**Comment by AudMonte01** [comment]
Thank you, @krol3 for meeting with @thehoneycomb 

Anderson - is the city technically called Vale Real in RS, Brazil?

**Comment by thehoneycomb** [comment]
Hi! @AudMonte01, 

No, the Vale do Paraíba, or Paraíba Valley, is a region located in southeastern Brazil, straddling the states of São Paulo and Rio de Janeiro. This valley is named after the Paraíba do Sul River, which flows through it. The region is known for its historical significance, particularly during the coffee boom in the 19th century. Today, it is a vibrant area with a mix of industrial development, agricultural activities, and cultural heritage. The cities within the valley, such as São José dos Campos, Taubaté, and Resende, are key economic and technological hubs in Brazil.

If we have to choose a city, we can choose either São José dos Campos or Taubaté.

Best,

**Comment by AudMonte01** [comment]
Thank you for answering my questions and collaborating with @krol3.

I have created the chaptered titled, "Vale do Paraíba" with a mandatory selection of a location, which I assigned as São José dos Campos. Please note, you can hide the map on your chapter page if you wish (and think it may cause confusion with the community).

That said, you should have just received an automated welcome email from me. 

Thank you in advance for helping make cloud native ubiquitous! This ticket is now closed.
