### ISSUE TITLE
[Group Request] Create a new chapter for Moka, Mauritius

### ISSUE THREAD

**Issue by ishwon** [cncf/communitygroups#71]
### City or location name for your CNCG

Cloud Native Mauritius

### What country do you want to start your community group in?

Mauritius

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Nitin K Sookun (a.k.a Ish), ishwon@opensuse.org, La Sentinelle Ltd, https://github.com/ishwon, https://www.linkedin.com/in/ishsookun, I requested an invitation to the CNCF Slack workspace, https://community.cncf.io/u/mngj9t/#/about

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Alexandre Bissessur, alexbissessur@gmail.com, Intern at SWAN, https://github.com/xelab04, https://www.linkedin.com/in/alexandre-bissessur-b9986123a, https://community.cncf.io/u/mgekzm/

_No response_

### What is your mission statement or objective for this new chapter?

The Kubernetes users community in Mauritius is slowly picking up pace and through this chapter, we would like to give the users a "home" where they are welcome to share knowledge and learn together. In particular, this year at the annual [Developers Conference](https://conference.mscc.mu) in Mauritius, which will be held in July, we're planning to announce the formation of this chapter. The conference is an ideal time and location to obtain maximum reach.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Thank you for this submission. There is currently or never previously been a Cloud Native chapter in Mauritius. That said, this is approved, however, we need @xelab04 to confirm they have take then Inclusive Open Source course mentioned above, as well as add his headshot photo his community.cncf.io profile.

**Comment by ishwon** [comment]
Thank you @AudMonte01. Talking to @xelab04 to complete the Inclusive Open Source course.

**Comment by xelab04** [comment]
Hi @AudMonte01 I have completed the course (and have the badge). I also updated my profile.
Thanks a lot.

On a side note, is it possible to change the location from Asia to Africa? No problem if not.

**Comment by AudMonte01** [comment]
Excellent - thank you @xelab04. You have now been added as an organizer and should have just received an atuomated welcome email from me. Please follow instructions from there.

Yes, the region is now Africa.

I am now closing this ticket.

**Comment by ishwon** [comment]
Awesome. Thank you Audra.
