### ISSUE TITLE
[Organizer Request] Add Organizer to Valencia chapter

### ISSUE THREAD

**Issue by marcelomrwin** [cncf/communitygroups#72]
### Name of chapter inquiring about

Cloud Native Valencia

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Marcelo Sales, marcelo.d.sales@gmail.com, Red Hat, https://github.com/marcelomrwin, https://www.linkedin.com/in/marcelo-daniel-sales/, https://community.cncf.io/u/mgnd4c/#/about

### Tell us why you want to be added or removed from the chapter

I have worked in the world of information technology for over twenty years. I participated in many communities in Latin America. I have lived in Valencia for just over three years. As a master's student at the Polytechnic University of Valencia, I seek to support my colleagues in open source technologies, especially aimed at the cloud world. I have experience with several CNCF projects such as kubernetes, nats, keycloak, helm, operator, knative, istio and others, to name a few.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [ ] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [x] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you for your inquiry @marcelomrwin. Please agree to the last term, and let me know if you need any clarification. Once agreed, then I will bring in the current/new organizers in Valencia to see what the next steps would be to have you join as a co-organizer.

**Comment by AudMonte01** [comment]
hello @marcelomrwin - please let me know if you have any questions.

**Comment by marcelomrwin** [comment]
Hi @AudMonte01 , thanks for your response. I forgot to mark the last one.

**Comment by AudMonte01** [comment]
Excellent @marcelomrwin - please let @jlassery and @levenhagen know what company you are from, and they can let you know the best way to collaborate with them on this chapter.

**Comment by marcelomrwin** [comment]
Of course, I know them very well. Thanks @AudMonte01. Would you like me to do anything else?

**Comment by AudMonte01** [comment]
Just post here what company/organization you are associated with, as we cannot have the majority of organizers from the same company. This is in an effort to remain vendor-neutral.

I just need Jade or Bernardo to confirm the acceptance of you as a co-organizer or collaborator in another way, before I move forward.

**Comment by marcelomrwin** [comment]
Yes of course. Today I am an employee of Red Hat, however, I was active in the community long before becoming part of the Red Hat team

**Comment by jlassery** [comment]
I confirm Marcelo as an organizer @AudMonte01 @marcelomrwin

**Comment by AudMonte01** [comment]
Excellent - thank you, @jlassery.

@marcelomrwin - you should have just received an automated welcome email from me with next steps, as you are now added as a co-organizer on the [Valencia chapter page](https://community.cncf.io/cloud-native-valencia/).
