### ISSUE TITLE
[Organizer Request] Add Luiz Bernardo Levenhagen as CNCF Valencia organizer

### ISSUE THREAD

**Issue by levenhagen** [cncf/communitygroups#74]
### Name of chapter inquiring about

Cloud Native Valencia

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Luiz Bernardo Levenhagen, levenhal@gmail.com, Red Hat, @levenhagen, https://www.linkedin.com/in/blevenhagen/, Luiz Bernardo Levenhagen in CNCF Slack, https://community.cncf.io/u/m98uyy/#/about

### Tell us why you want to be added or removed from the chapter

I, Luiz Bernardo Levenhagen, would like to join as an organizer in Cloud Native Valencia. I have participated in many CNCF and other open source activities in the past years, including organizing a KCD (Sao Paulo) and being a speaker in KubeCon and Open Source Summit. I'm a Valencia resident and I believe the region has a great audience and community that can be bloomed with my experience and passion as an organizer.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by k8tgreenley** [comment]
@levenhagen Your request has been shared with the current organizer to review

**Comment by AudMonte01** [comment]
@levenhagen has been added to the Valencia chapter as an organizer. This ticket is now closed.
