### ISSUE TITLE
[Group Request] Create a new chapter - Cloud Native Minas Gerais

### ISSUE THREAD

**Issue by ste-bartels** [cncf/communitygroups#77]
### City or location name for your CNCG

Cloud Native Minas Gerais

### What country do you want to start your community group in?

Brasil

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Stephanie Chaia Bartels, JackExperts, ste.bartels@gamil.com, https://github.com/ste-bartels , https://www.linkedin.com/in/stephanie-chaia-bartels/ , https://community.cncf.io/u/m9p663/#/about  , need a invited to slack

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Name: Paulo Henrique Antunes de Cerqueira
E-mail: ph.a.cerqueira@gmail.com
Company: 4Linux
GitHub URL: https://github.com/phacerqueira
LinkedIn: https://www.linkedin.com/in/phcerqueira/
CNCF Profile: https://openprofile.dev/profile/phacerqueira

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Bruno Pacheco da SIlva, pacheco.bs@gmail.com, Fundação CAEd, https://github.com/pacheco-bs, https://community.cncf.io/u/mbcxat, slack (need to be invited).

### What is your mission statement or objective for this new chapter?

We are creating a community called Tech Hub JF to strengthen the IT community in Minas Gerais in all areas of IT. Our main objective is to provide this community with knowledge of what the CNCF is and everything that surrounds it.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by k8tgreenley** [comment]
@ste-bartels Please see a few questions below:

- Can you please provide the cadence of your meetup, i.e. will it be monthly, quarterly, etc.? What day of the week will it be held?
- Is there a specific audience you are trying to reach?
- Is there a particular area this will be hosted?

**Comment by ste-bartels** [comment]
Currently, we are at the core of organizing the Tech Hub Juiz de Fora Movement, which aims to foster and encourage meetings among technology professionals in the region. For instance, last April, we hosted the Tech Hub Conf event, bringing together professionals from various fields, including participants from different parts of the country. The event attracted 224 attendees, in addition to the organizing team (you can find more information about the event [here](https://techhubjf.org/conf)  ).

Additionally, every 15 days, we organize an informal gathering called ‘Chopp da TI’ (you can find details [here](https://linktr.ee/techhubjf)). The purpose of these gatherings is to maintain community engagement by discussing technology-related topics.

In this context, we are considering incorporating CNCF (Cloud Native Computing Foundation) meetings on a quarterly basis. We plan to leverage the existing ‘Chopp da TI’ event as an initial platform, utilizing the same venue and reaching out to the recurring audience. Our goal is to encourage new participants through promotion on our social media channels and platforms.

**Comment by AudMonte01** [comment]
Thank you for these details, @ste-bartels - Can you tell me if the majority if your meetups would be held in the State's capital, Belo Horizante? If so, we should revive this chapter, previously started by Andre Almeida Araujo. Do you by chance know, Andre?

**Comment by ste-bartels** [comment]
It would not be in Belo Horizonte, but in Juiz de Fora. Unfortunately I don't know the Andre mentioned. The suggestion for the name covering the entire state was precisely after researching and not finding another meetup in Minas Gerais.

**Comment by AudMonte01** [comment]
The Belo Horizonte chapter is not active, so you are right. This would be the only active chapter in the state. We always recommend naming chapters by cities if they are large enough to be recognized. Otherwise, if you wish to name your chapter by state, then you would have to understand that the branding and naming could change over time if new chapters arise within the state. Please discuss with the others and let me know what your thoughts are.

**Comment by ste-bartels** [comment]
We understand the issues and if necessary we are willing to change the name of the chapter without any problems.  The name covering the entire state is the way to draw attention to the movement.  Within what we are already carrying out here in Juiz de Fora, there has been a range of participants from all over the state and even from other states.  The idea is to help the community grow.

**Comment by ste-bartels** [comment]
We are already moving towards collaboration between the other chapters and even the KCD team.  Is this viable?

**Comment by AudMonte01** [comment]
Given all this, we are happy to announce that we can move forward with the activation of this chapter. Please first have @phacerqueira and @pacheco-bs comment here agreeing to the above terms and confirming they have taken the open source inclusive, free online course.

**Comment by pacheco-bs** [comment]
Hi @AudMonte01, Thank you for the update! 
I’ve reviewed the terms, and I’m happy to move forward with the activation of this chapter. 
I agree to the conditions outlined above, and I confirm that I have completed the open-source inclusive free online course.

**Comment by phacerqueira** [comment]
Hi @AudMonte01 thanks for the update. I also have reviewed the terms and I’m very excited with the activation of the chapter. I confirm that I've read and agree with the conditions. I also confirm that I've completed the inclusive open-source community orientation course.

**Comment by AudMonte01** [comment]
I have added you all as chapter organizers to the new chapter, "Cloud Native Juiz de Fora"! You should have all received an automated email from me. Please follow the next steps there, and if at least 1 of you can attend my office hour on Friday, it would be good to discuss how to get started with your first meetup. https://community.cncf.io/e/mjh9z7/

@pacheco-bs- please update [your profile](https://community.cncf.io/u/mbcxat) with a headshot so it is forward facing on the chapter page (once there is a description and it is un-hidden).

I am now closing this issue.

**Comment by pacheco-bs** [comment]
Hi @AudMonte01, Thank you for the update!
I inform you that I have already applied the requested adjustments to my profile! I also take this opportunity to say that we are very happy with the creation of our chapter. Thank you very much!” 😊🌟

**Comment by AudMonte01** [comment]
Excellent - and thank you three for showing up today at my office hour to be enabled.
