### ISSUE TITLE
[Organizer Request] Add Khanh Tran as CNCF Hanoi Organizer

### ISSUE THREAD

**Issue by khanhtc1202** [cncf/communitygroups#80]
### Name of chapter inquiring about

CNCF Hanoi

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

name: Khanh Tran
email: khanhtc1202@gmail.com
company: CyberAgent, inc.
github: @khanhtc1202 
linkedin: https://linkedin.com/in/khanhtc1202

### Tell us why you want to be added or removed from the chapter

I, Khanh Tran (khanhtc1202), would like to join as a co-organizer. I have joined the CNCF community in Vietnam (both Hanoi and Ho Chi Minh City) as a speaker. Also, I’m the maintainer of a CNCF Sandbox project (named PipeCD - github.com/pipe-cd/pipecd). With my experience as a community member, I want to contribute more to the community as an organizer.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by khanhtc1202** [comment]
@k8tgreenley @tovin07 Please check when you all have time 🙏

**Comment by tovin07** [comment]
Hi @khanhtc1202, welcome you to organizer team of Hanoi chapter.

**Comment by AudMonte01** [comment]
Hello @tovin07 - please let us know which organizer you are on this page: https://community.cncf.io/hanoi/

Also, please add your GitHub profile to your account on community.cncf.io within the About Me section.

Thank you, and kind regards ~

Audra Montenegro
Core CNCF Community Program Manager

**Comment by tovin07** [comment]
> Hello @tovin07 - please let us know which organizer you are on this page: https://community.cncf.io/hanoi/
> 
> Also, please add your GitHub profile to your account on community.cncf.io within the About Me section.
> 
> Thank you, and kind regards ~
> 
> Audra Montenegro Core CNCF Community Program Manager

Hi @AudMonte01,

Thank you for your response.

I am Nguyễn Trọng Vĩnh (https://community.cncf.io/u/m6w6en/#/about).

**Comment by AudMonte01** [comment]
Thank you, @tovin07 - I have added @khanhtc1202 as an organizer to the chapter. 
Khan, you should have received an automated welcome email from me with further instructions.
I will now close this ticket/issue.

**Comment by khanhtc1202** [comment]
Thank you @AudMonte01 @tovin07 🙏
