### ISSUE TITLE
[Group Request] Create a new chapter in Suisse Romande

### ISSUE THREAD

**Issue by oleg-nenashev** [cncf/communitygroups#81]
### City or location name for your CNCG

Cloud Native Suisse Romande

### What country do you want to start your community group in?

Switzerland

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

I am a CNCF Ambassador organizing events and meetups in Switzerland. It would be nice to have an umbrella community group for the French speaking part of Switzerland to organize meetups in Geneva, Lausanne, Neuchatel and other cities in the region. I think one group would be enough

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

We have 3 CNCF Ambassadors in the region, and one CNCF TOC Member. More organizers will join from other related communities later

 Oleg Nenashev, CNCF Ambassador, Gradle, @Oleg Nenashev
 Raphaël Pinson, CNCF Ambassador, Isovalent
 Nuno do Carmo, CNCF Ambassador, Suse/Rancher
 Ricardo Rocha, CNCF TOC, CERN

Same as https://github.com/cncf/kubernetes-community-days/issues/508

### If you already run a meetup, please link it here

- https://www.meetup.com/swiss-jenkins-area-meetup/
- https://api-ne.ch/
- an multiple other online and offline meetups within the CDF

### What is your mission statement or objective for this new chapter?

The French-speaking part of Switzerland has about 2 million people. Some of them can travel to existing CNC/CNCF meetup groups, but it may take multiple hours and there is a language barrier. So, we would like to start a local francophone group which would facilitate local events and cooperation between organizers of multiple meetups from the CNCF landscape

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by oleg-nenashev** [comment]
Thanks @AudMonte01 ! Confirmations with other orgs are pending.

**Comment by nunix** [comment]
Hi @AudMonte01 @oleg-nenashev,

sorry for the delay, and I do confirm I agree with the above and completed the Open Source Inclusion training.

Thanks again for setting this chapter up.

**Comment by AudMonte01** [comment]
Thank you, @nunix - I have added you and @oleg-nenashev as organizers. You should have just received an automated welcome email with further instructions. 

Please have Raphaël and Ricardo reply here with their affirmation of the terms above.

**Comment by oleg-nenashev** [comment]
Thank you @AudMonte01 ! I confirm https://community.cncf.io/cloud-native-suisse-romande/ is up and running. I will do some polishing before the public announcement

**Comment by AudMonte01** [comment]
Tagging @raphink and @rochaporto - please affirm you accept the above organizer terms (though I feel I know the answer given the ambassadorship and TOC involvement :)).

**Comment by AudMonte01** [comment]
Following up here, @raphink and @rochaporto.

**Comment by rochaporto** [comment]
@AudMonte01 affirm :)

**Comment by raphink** [comment]
ok for me, sorry for the delay

**Comment by AudMonte01** [comment]
Wonderful! You too should have received an automated welcome email from me. I will now add everyone to the community group organizer channel, and close this issue.
