### ISSUE TITLE
[Group Request] Create a new chapter for Orléans

### ISSUE THREAD

**Issue by uber94** [cncf/communitygroups#82]
### City or location name for your CNCG

Cloud Native Orléans

### What country do you want to start your community group in?

France

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Hubert NANG, hubertnang2017@gmail.com, JEMS DATAFACTORY, https://github.com/uber94, https://www.linkedin.com/in/hubert-nang-0655ba172/, Uber N

### What is your mission statement or objective for this new chapter?

Our mission is to foster a collaborative community in Orléans for DevOps engineers, cloud architects, and IT professionals to learn, share, and implement Open source & cloud-native technologies and best practices.  This group will bridge the gap between theory and practice, enabling members to build, deploy, and manage scalable and resilient applications in the cloud.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Thank you, @uber94 for submitting this request. I see we have some connections in common!

Please share with me some community efforts you have ran/lead in the past. As well as if you foresee any co-organizers joining you to share the workload of hosting meetups at least once every 90 days?

**Comment by AudMonte01** [comment]
Hello @uber94 - I love [the story you told on LinkedIn about Kuberentes and Istio](https://www.linkedin.com/posts/hubert-nang-0655ba172_the-tale-of-istio-the-superpower-for-your-activity-7199473311708311552-Zqyw?), as well as well as the [lecture you provided on Argo CD](https://www.youtube.com/watch?v=1L3hF4dkRyo). You see you would bring good value to the French community in Orleans.

With that, I have created a chapter for you, and added you as an organizer. You should have received an automated welcome email from me with further instructions. Please add a profile picture to your community.cncf.io account so I can showcase you as an organizer of the chapter.

This issue/ticket is now closed.
