### ISSUE TITLE
[New Co-Organizer Request] Add Ritesh Hegde as Co-Organizer to Singapore chapter

### ISSUE THREAD

**Issue by rhegde1** [cncf/communitygroups#83]
### Name of chapter inquiring about

Cloud Native SIngapore

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Ritesh Hegde,
SPH Media Pte. Ltd.
Sr. Platform Engineering Cloud.
https://www.linkedin.com/in/riteshhegde/
https://community.cncf.io/u/mrp7b3/#/about
https://mvp.microsoft.com/en-US/MVP/profile/d5b9d330-48f5-4ce1-938b-40d375ca5be1
https://www.hashicorp.com/ambassador/directory?q=ritesh%20hegde

### Tell us why you want to be added or removed from the chapter

I, Ritesh Hegde, would like to join as co-organizer for Cloud Native Singapore Chapter.
Why I am excited to be an ambassador: Singapore and ASEAN Region need more active and organized meetups around cloud native community. The activities are behind compare to India, US, EMEA and ANZ Region. As an  organizer, I will continue to create more awareness and advocate CNCF projects in Singapore and ASEAN Region. 
I am currently contributing in the Tech community in Singapore in K8SUG-SG Meetup.
I am Microsoft MVP - for My contribution towards Microsoft Azure Community service
I am Hashicorp Ambassador - for my Contribution towards Hashicorp community in Singapore.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by rhegde1** [comment]
ping request @k8tgreenley @AudMonte01 
@yongkanghe

**Comment by yongkanghe** [comment]
I'm so glad you're keen to join us. Thanks @rhegde1!

**Comment by AudMonte01** [comment]
Hi @yongkanghe - please let @rhegde1 know his option for joining as an organizer, or other ways to collaborate.

**Comment by yongkanghe** [comment]
@AudMonte01, @rhegde1 will be 1 of our co-organizers.

**Comment by rhegde1** [comment]
@yongkanghe Thank for for endorsement. @AudMonte01 could you help to add me as Co-Organizer for CNCF Singapore chapter.

**Comment by yongkanghe** [comment]
@AudMonte01 @k8tgreenley

**Comment by yongkanghe** [comment]
@AudMonte01, can you please add @rhegde1 as the co-organizer ASAP? We will kick start our 1st meetup, actually the KuberTENes celebration in July.

**Comment by AudMonte01** [comment]
Hi @rhegde1 - you have now been added as an organizer to the Singapore chapter, and should have just received an automated welcome email from me. Please follow instructions there. I will close this issue at this time.
