### ISSUE TITLE
Add Organizer Vijay Raj to Cloud Native Trivandrum

### ISSUE THREAD

**Issue by Vijay-j02** [cncf/communitygroups#84]
### Name of chapter inquiring about

Cloud NativeTrivandrum

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Vijay Raj, jvijayraj1998@gmail.com, Konsultera Solutions, https://www.linkedin.com/in/vijay-raj-j, https://github.com/Vijay-j02, https://community.cncf.io/u/m28f7u/#/about, Please invite me to CNCF slack workspace.

### Tell us why you want to be added or removed from the chapter

I am applying to be a CNCF co-organizer to further promote cloud-native technologies. Over the past two years, I have:
   * Organized and hosted CNCF Trivandrum in-person events.
   * Organized DevOps Malayalam events, both in-person and online.
   * Volunteered at KCD Kerala, managing a track successfully.
I am passionate about helping others implement cloud-native technologies and aiding my organisation in adopting the latest tools. As a CNCF organizer, I aim to continue fostering community engagement and knowledge sharing in cloud-native solutions. 

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by Vijay-j02** [comment]
@AudMonte01 @k8tgreenley

**Comment by AudMonte01** [comment]
Thank you for your inquiry @Vijay-j02. I am copying one of the current lead organizers to let you know what would be the first steps to helping organizer meetups with this chapter.

Cc @ebinbabu

**Comment by ebinbabu** [comment]
Hi @Vijay-j02,

We are happy to onboard you!

@AudMonte01, could you please help add @Vijay-j02 to the Bevy platform and send a Slack invite?

Thanks!

**Comment by AudMonte01** [comment]
Thank you for the speedy response, @ebinbabu. Please invite Vijay to the the team's current syncs for collaboration.

@Vijay-j02 - I have just added you as an organizer to the chapter. You should have just received an automated welcome email from me with further instructions. 

This ticket is now closed.

**Comment by Vijay-j02** [comment]
Thank you!! @AudMonte01 @ebinbabu

**Comment by Vijay-j02** [comment]
Hi @AudMonte01, I'm not able to join the CNCF slack workspace. Can you please add me to it.
![Screenshot from 2024-08-11 17-19-10](https://github.com/user-attachments/assets/f3681f83-860b-4c43-8831-d7e9ae5b643e)

**Comment by AudMonte01** [comment]
hi @Vijay-j02 - I just sent you a Slack invite.
