### ISSUE TITLE
[Organizer Request] Remove Organizer Bauer + Schütz to Graz chapter

### ISSUE THREAD

**Issue by DrackThor** [cncf/communitygroups#85]
### Name of chapter inquiring about

Graz

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Daniel Drack, daniel@drackthor.me, FullStackS GmbH, https://community.cncf.io/u/m5wmwy/#/about

### Tell us why you want to be added or removed from the chapter

Please remove "Markus Bauer" and "Thomas Schütz" from our Graz CNCF bevy page.
Both of them were valuable members of our organizer team, but decided to phase out some time ago.
We talked about them leaving the organizer team in person and both are fine with the decision.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Hi @DrackThor - please add Bauer and Schutz to this issue by tagging their GitHub handles, so they can confirm their resignation.

**Comment by AudMonte01** [comment]
Following up here @DrackThor.

**Comment by DrackThor** [comment]
Sorry for the delay - this is Thomas Schütz GH handle @tschue (https://github.com/thschue)
I'll contact you directly regarding Markus Bauer @AudMonte01

**Comment by DrWulfric** [comment]
I hereby confirm the resignation

**Comment by AudMonte01** [comment]
Thank you, @DrWulfric - it is hard to tell who you are based on your profile, if you can confirm by adding a link to your LinkedIn in your profile?

**Comment by DrWulfric** [comment]
Ah, my bad - sorry, yes - Markus Bauer. I'll add the link.

**Comment by AudMonte01** [comment]
Thank you, @DrWulfric - I have removed you from the Graz chapter. 

@thschue - do you confirm your resignation as an organizer as well?

**Comment by AudMonte01** [comment]
With @thschue's thumbs up, I have also removed him as an organizer. This issue is now closed.

Wishing you both all the best in your cloud native journeys outside of community groups.
