### ISSUE TITLE
[Organizer Request] Add Roland Urbano to Graz chapter

### ISSUE THREAD

**Issue by X4mp** [cncf/communitygroups#86]
### Name of chapter inquiring about

Cloud Native Graz

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Roland Urbano, NTS Netzwerk Telekom Service AG, https://github.com/X4mp, https://www.linkedin.com/in/roland-urbano-9b937b164, Roland in CNFC Slack, https://community.cncf.io/u/mvz2xq/#/about

### Tell us why you want to be added or removed from the chapter

I, Roland Urbano want to be added as co-organizer for the CNCF chapter in my home town Graz. I want to help organize events and provide my experience and motivation to the chapter.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
@DrackThor - please either confirm acceptance, or let @X4mp know next steps on how to contribute to this chapter.

**Comment by DrackThor** [comment]
Sorry for the delay, yes please add Roland! he's already a valued member of our team 🙏

**Comment by AudMonte01** [comment]
Excellent - @X4mp, you should have just received an automated welcome email from me with next steps. Welcome to the chapter! I host office hours every Friday in case the time works for you to attend, and you have any questions. Here is the page and registration for this Friday the 16th's office hour: https://community.cncf.io/e/mmt9em/

This issue/ticket is now closed.
