### ISSUE TITLE
[Organizer Request] Add or Remove Organizer Mohamed Ibrahim Ahmad to Riyadh

### ISSUE THREAD

**Issue by RafMo20D** [cncf/communitygroups#87]
### Name of chapter inquiring about

KuberTENes Birthday Bash Riyadh

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

https://www.linkedin.com/in/mohamed-ibrahim-a-441258199/

https://github.com/RafMo20D

### Tell us why you want to be added or removed from the chapter

A confident, motivated and professional DevOps engineer with leadership experience. Skilled in several technology stacks, with an emphasis in cloud-based technologies, automation, CI/CD, network design and security. Experienced in cross-functional team structures in agile and fast-paced environments.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Hello @RafMo20D - are you just inquiring to help with one meetup, or the chapter in full? It looks like their KuberTENes party completed yesterday.

Cc @rajrahul03 (current organizer)

**Comment by rajrahul03** [comment]
Hi @RafMo20D 

We are happy to onboard you!

@AudMonte01 , could you please help add @RafMo20D  to the Bevy platform and send a Slack invite?

Thanks!

**Comment by AudMonte01** [comment]
I am happy to add @RafMo20D, but first need him to confirm if he wishes to join the chapter in full as a co-organizer, versus just wanting to have helped with the KuberTENes party.

**Comment by RafMo20D** [comment]
@AudMonte01 I would like to join the entire class as a co-organizer. I'm happy for that
