### ISSUE TITLE
[Organizer Request] Add Organizer Akanksha Srivastava to Cloud Native Riyadh Chapter

### ISSUE THREAD

**Issue by 0akanksha** [cncf/communitygroups#88]
### Name of chapter inquiring about

Cloud Native Riyadh

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Name- Akanksha Srivastava
Email- k.akanksha1@outlook.com
Company- Xebia Middle East
Github- https://github.com/0akanksha
Linkedin - https://www.linkedin.com/in/akanksha-srivastava-37804114a/
Slack- k.akanksha1@outlook.com
Community - https://community.cncf.io/u/mpn4vt/

### Tell us why you want to be added or removed from the chapter

I, Akanksha Srivastava, would like to join CNCF Riyadh as a co-organizer. I am currently based in Riyadh and working as a DevOps Consultant. Also, as a Speaker and trainer, I have contributed to many events and am keenly interested in CNCF community events. 

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you for your interest in co-organizing in this chapter. I am adding @rajrahul03 who is a current organizer of this chapter. Rahul - please let Akanksha know steps to becoming an organizer in your chapter.

**Comment by rajrahul03** [comment]
Hi @0akanksha 

We are happy to onboard you!

@AudMonte01  , could you please help add @0akanksha  to the Bevy platform and send a Slack invite?

Thanks!

**Comment by AudMonte01** [comment]
Thank you, @rajrahul03 - and welcome @0akanksha ! You should have just received a welcome email from me.

Please [message me](https://cloud-native.slack.com/archives/D03KQPHLRGC) in the CNCF Slack workspace, as I see two people with the same name, so updating your profile photo would be helpful.
