### ISSUE TITLE
[Organizer Request] Add Mehdi Pasha to Riyadh chapter

### ISSUE THREAD

**Issue by mehdidevops2030** [cncf/communitygroups#89]
### Name of chapter inquiring about

Cloud Native Riyadh

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Name : Mehdi Pasha
Email: mehdipasha20@gmail.com
Company: Atheeb Intergraph Saudi Company
Linkedln URL: https://www.linkedin.com/in/mehdi-pasha-41826827/

### Tell us why you want to be added or removed from the chapter

I Mehdi Pasha would like to join as a co-organizer, I have experience with different tools of CNCF that would be an asset to the chapter and I have been an active member of this chapter as a moderator to the event in Riyadh

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Cc @rajrahul03 - please let @mehdidevops2030 know how they can contribute to your chapter.

NOTE: I am seeing many requests to help co-organize this chapter. So an interview process or participation over time as a member, speaker, volunteer, or sponsor might be appropriate.

**Comment by rajrahul03** [comment]
Hi @AudMonte01 ,

We are planning to have total 6 organisers. Mehdi is one of the key member with us.
could you please help add @mehdidevops2030  to the Bevy platform and send a Slack invite?

Thanks!

**Comment by AudMonte01** [comment]
Thank you, @rajrahul03 - Mehdi I have added you as an organizer, you should have received an automated email from me. Please do complete your profile on community.cncf.io so you have a photo, being that your profile will be forward-facing on [the main chapter page.](https://community.cncf.io/cloud-native-riyadh/)
