### ISSUE TITLE
[Organizer Request] Add or Remove Organizers to Istanbul chapter

### ISSUE THREAD

**Issue by halil-bugol** [cncf/communitygroups#90]
### Name of chapter inquiring about

Cloud Native Istanbul

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Halil Bugol, Co-Founder at Kubezy, CNCF Ambassador, https://www.linkedin.com/in/halilbugol/, CNCF Slack: Halil

### Tell us why you want to be added or removed from the chapter

We are going through a new structure in the Istanbul organization and creating different teams. Our community has become quite crowded, now there are at least 50 people in each event and we plan two physical events every month. The organization is tiring for us. While dealing with organization work, we stay away from social media and online events. We are thinking of adding a few organizers and reviving this place. There will be a few teams inside, such as accounting, physical events, online events, social media and other channel management. With the new organizers we added, we want to turn the chapter into a completely professionally managed community.

Harun Eren Şat, SA @kubezy, CNCF Slack: Harun Eren ŞAT, https://community.cncf.io/u/mzvdnj/
Metehan Topalhan, DevOps Engineer at Turknet, CNCF Slack: Metehan Topalhan, https://community.cncf.io/u/mzn4xj/#/about
Onur Canoglu, DevOps Engineer at Hexaworks, CNCF Slack: Onur Canoğlu, https://community.cncf.io/u/mr8688/#/about
Uğur Kazdal, SA @aws, CNCF Slack: Ugur Kazdal, https://community.cncf.io/u/m85cby/#/about
Zehra Sabaz, Account Executive @Kubermatic, CNCF Slack: Zehra Sabaz, https://community.cncf.io/u/m76hkt/#/about

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you, @halil-bugol - I am glad to see the team grow.

Please have each person reply in this issue confirming they have completed the Open Source Inclusive training linked above.

**Comment by uurtech** [comment]
I have completed it @AudMonte01

**Comment by canogluonur** [comment]
I have completed training @AudMonte01

**Comment by HaruEr** [comment]
I have completed the required training and confirm my participation. @AudMonte01

**Comment by zehrasabaz** [comment]
I have just completed the training and happily confirm my participation ✨

**Comment by AudMonte01** [comment]
Thank you, everyone.

* @HaruEr and @uurtech - I have added you both as organizers but you are currently hidden from the front-end of the chapter page. Please add a profile picture to [your community.cncf.io account](https://community.cncf.io/u/mzvdnj/)
* The others have been added, but are not hidden from the front-end

You all should have received automated, welcome emails from me.

Thank you in advance for helping make cloud native ubiquitous, and [remaining vendor neutral](https://github.com/cncf/communitygroups/blob/main/best_practices.md#find-speakers) in all of your content. This ticket is now closed.
