### ISSUE TITLE
[Group Request] Create a new chapter in Egypt

### ISSUE THREAD

**Issue by ahmedshendy** [cncf/communitygroups#91]
### City or location name for your CNCG

Cloud Native Cairo

### What country do you want to start your community group in?

Egypt

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Ahmed Shendy, ahmed.shendi@gmail.com, Saudi Telecom, https://github.com/ahmedshendy, https://www.linkedin.com/in/ahmed-shendy/, https://community.cncf.io/u/m42y56/#/about, I need to be invited to slack

### What is your mission statement or objective for this new chapter?

we are excited about the CNCF projects, we want to introduce a chance for anyone to provide his experience with any of the CNCF, I want to spread the culture of CNCFprojects

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Hello @ahmedshendy - thank you for your interest in starting a chapter in Cairo.

Some months ago, I had already enabled @mohamednasser018 to lead this chapter, but he might be able to use your help, as he has yet to host a meetup. I defer to him to set up some time for you two to sync.

Also, I host weekly office hours, if you both want to attend next week's session should you have any questions: https://community.cncf.io/e/mwqwu3/

**Comment by mohamednasser018** [comment]
I have no problem with him joining me and us remaining as one team, and this will help us together. There is no problem with cooperation in this

**Comment by AudMonte01** [comment]
Excellent - thank you, @mohamednasser018 for welcoming @ahmedshendy. Please confirm you accept this co-organzation effort, and schedule some time to sync with Mohamed.

**Comment by AudMonte01** [comment]
@ahmedshendy - please confirm you accept co-organization with one another so I may add you as an organizer to the chapter. Thank you.

**Comment by ahmedshendy** [comment]
Hello,
Yes, I accept the invitation

**Comment by AudMonte01** [comment]
Excellent! I have added you as an organizer to the chapter that has been pending publishing, as the description still needs updating. You would be great for helping Mohamed with this.

You should have just received an automated welcome email from me. Please follow instructions there, as well as add a headshot picture of yourself in [your community.cncf.io account](https://community.cncf.io/u/m42y56/#/about). Once this is done, I can make you visible on the front-end as a chapter organizer.

This issue/ticket is now closed.
