### ISSUE TITLE
[Organizer Request] Add Pavel Pavlov to Heidelberg chapter

### ISSUE THREAD

**Issue by pnpavlov** [cncf/communitygroups#92]
### Name of chapter inquiring about

Heidelberg

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Pavel Pavlov, SAP, https://github.com/pnpavlov, https://linkedin.com/in/pavelnpavlov, Pavel Pavlov (SAP) in CNCF Slack, https://community.cncf.io/u/m4z5d5/#/about

### Tell us why you want to be added or removed from the chapter

I'd like to join as co-organiser. I already work closely with the co-hosts Vasu Chandrasekhara (SAP) &  Adel Zaalouk
 (Red Hat).

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Hello @pnpavlov - I have added you as "Check-in staff" (an organizer with limited permissions), that is not yet visible on the website. Adding @zanetworker so he can confirm your addition to the chapter, or next steps.

**Comment by zanetworker** [comment]
Can confirm. Thank you for the ping. LGTM!

**Comment by AudMonte01** [comment]
Excellent - thank you, @zanetworker. Pavel is now visible as an organizer on [the chapter page](https://community.cncf.io/heidelberg/).

@pnpavlov - you should have received an automated welcome email from me last week. Please follow steps there.

This ticket is now closed.
