### ISSUE TITLE
[Organizer Request] Add Yongkang as the lead organizer for Melbourne

### ISSUE THREAD

**Issue by yongkanghe** [cncf/communitygroups#93]
### Name of chapter inquiring about

Melbourne

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Yongkang He
yhe@yongkang.com.au
K8SUG
https://github.com/yongkanghe
https://linkedin.com/in/yongkanghe
yongkang
https://community.cncf.io/u/mvs8uf/#/about

### Tell us why you want to be added or removed from the chapter

Melbourne community is not active for probably 1 year. I had very strong experience to help the community. I'd love to make it actively running. 

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by yongkanghe** [comment]
@AudMonte01 @k8tgreenley

**Comment by AudMonte01** [comment]
Hello @yongkanghe - based on previous email collaboration with us, and meetings and attempted meetings with 1 or more of the past organizers, we have revived this chapter with your as the lead organizer. You should have just received an automated welcome email from me with further instructions.

This ticket is now closed.
