### ISSUE TITLE
[Group Request] Create a new chapter for China DaLian

### ISSUE THREAD

**Issue by addozhang** [cncf/communitygroups#95]
### City or location name for your CNCG

Cloud Native Dalian

### What country do you want to start your community group in?

China

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Name: Xiaohui Zhang
Email: duwasai@gmail.com
Company: Flomesh (https://flomesh.io)
Github: https://github.com/addozhang/
LinkedIn: https://www.linkedin.com/in/addozhang/
Slack：Addo Zhang (Xiaohui) duwasai@gmail.com
CNCF Community Profile： https://community.cncf.io/u/mn724h/#/about

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Name: Jinghe Ma
Email: jhma@gitlab.cn
Company: Jihu GitLab
GitHub: https://github.com/majinghe
CNCF slack workspace Name: https://community.cncf.io/u/m54uzg/

### What is your mission statement or objective for this new chapter?

Over the past few years, the organizers of the CNCF Dalian Group have collaborated with local enterprises and volunteers to host annual cloud-native summits in Dalian. Each summit attracts over 100 cloud-native technology enthusiasts, with renowned speakers invited to share their expertise across various cloud-native domains. The 2023 KCD Dalian event drew over 220 attendees and featured more than 20 themed talks, making it the most popular event to date.

We regularly organize various events such as technical seminars, lectures, and seminars. Hope also provides a platform for enthusiasts to learn, grow, and innovate from each other. Whether you are a senior expert in the field of cloud computing or a novice interested in cloud-native technology, you can find your place and value in this community.

We hope this chapter to be the community for Cloud Native technology enthusiasms in DaLina.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Thank you for this submissions, @addozhang . Are you in contact with any of the organizers from KCD Dalian? It would be great if you could collaborate with them on this chapter.

Kevin Wang (HUAWEI CLOUD)
JingHe Ma (极狐 GitLab)
Xiaohui Zhang (Flomesh)

**Comment by AudMonte01** [comment]
In the meantime, I just need @majinghe - I see you were a previous organizer of this chapter. Please agree to he above terms, and we can move forward with you and @addozhang as organizers to reactivate the chapter.

**Comment by majinghe** [comment]
Sure, i requested to create the DaLian Chapter before and also was the owner of this Chapter. There are three organizers @addozhang @kevin-wangzefeng as well as me, organized DaLian Cloud Native event.

**Comment by AudMonte01** [comment]
Excellent. We just need @kevin-wangzefeng to comment here agreeing to the above terms, and that he has taken the above-mentioned inclusive course.

@majinghe - please also comment that you agree to the above terms and that you have taken the above-mentioned inclusive course.

**Comment by majinghe** [comment]
Sure, i agree all of above the items. Thanks for @addozhang @kevin-wangzefeng supporting the DaLian Cloud Native event.

**Comment by AudMonte01** [comment]
Thank you, @majinghe - please point me to your community.cncf.io profile so I may add you as an organizer.

**Comment by addozhang** [comment]
Thanks @AudMonte01 .

**Comment by kevin-wangzefeng** [comment]
I agree the terms, thanks

**Comment by AudMonte01** [comment]
Thank you, @kevin-wangzefeng - I have added you using your account tied to your Huawei email address. You should have received an automated welcome email from me.
