### ISSUE TITLE
[Organizer Request] Remove Kevin Evans from Edmonton chapter

### ISSUE THREAD

**Issue by kevinevans1** [cncf/communitygroups#96]
### Name of chapter inquiring about

Cloud Native Edmonton

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

linkedin.com/kevinevans1

### Tell us why you want to be added or removed from the chapter

Dear CNCF Team,

I regret to inform you that due to ongoing work and personal commitments, I am no longer able to dedicate the necessary time and effort required to run the chapter effectively. My current priorities prevent me from pursuing this role, and as such, I kindly request that the Cloud Native Edmonton chapter be dissolved as soon as possible. I appreciate your understanding and support in this matter.

Sincerely,

Kevin Evans

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [ ] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [ ] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [ ] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [ ] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [ ] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [ ] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Hello @kevinevans1 - we are sorry to see you go. Thank you for your dedication to helping make cloud native ubiquitous. 

Please add Cindy Hui's GitHub handle as a Cc in here for her awareness. From there we can discuss her plan for the chapters activity if she could please email kcd@cncf.io.

**Comment by Cinders-cmd** [comment]
I am unable to also continue supporting the Edmonton chapter. Confirm dissolve.

**Comment by AudMonte01** [comment]
Thank you both for submitting and commenting on this issue. We will deactivate this chapter until another person shows future interest.
