### ISSUE TITLE
[New Chapter] Request for a chapter in Kottayam, Kerala India

### ISSUE THREAD

**Issue by rakeshadr** [cncf/communitygroups#97]
### Name of chapter inquiring about

Cloud Native Kottayam

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Rakesh Radhakrishnan,
https://people.apache.org/phonebook.html?uid=rakeshr
https://www.linkedin.com/in/rakeshadr/, 
https://github.com/rakeshadr,
rakeshr.cncf@gmail.com,
Company: Microsoft

I am an evangelist of various Apache open source projects from 2014 onwards and spent a significant amount of time in various Apache open source projects - Apache ZooKeeper, Apache BookKeeper, Apache Hadoop, Apache Ozone and a committer/PMC on these projects as well. I'm a Apache Foundation Member.

I'm promoting the benefits of open source software, encourage community collaboration, and advocate for the use of free and open-source solutions. I work with developers, organizations, and users to highlight the importance of transparency, innovation, and shared knowledge in the software industry. By fostering a culture of openness, I aim to contribute to the growth and success of open source initiatives. 

### Tell us why you want to be added or removed from the chapter

Presently, I'm working with Microsoft and user of K8s platform especially in the bigdata analytics and AI solutions. I've participated in various events of CNCF which is a great community. I would like to collaborate with the CNCF foundation and extend my vision by working with CNCF projects, engaging in the community and organizing the chapter.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by rakeshadr** [comment]
Date of my original submission was 12/18/2023 9:25:11. Thanks!

**Comment by AudMonte01** [comment]
Thank you for your submission, @rakeshadr . You are very qualified to organizer a chapter in Kottayam, Kerala.

With that, I would like to see if you would be willing to have this as a sub chapter to the [Cloud Native Kerala chapter](https://community.cncf.io/cloud-native-kerala/) and collaborate with those organizers on speakers, sponsors and more. There is also a co-host feature which makes keeping the activity up with a chapter, more manageable. Please reference [our 90-day activity standard.](https://github.com/cncf/communitygroups/blob/main/README.md#community-group-inactivity)

**Comment by AudMonte01** [comment]
Hello @rakeshadr - please pardon my delay here. I have created your Kottayam chapter and added you as an organizer. You should have received an automated welcome email from me.

I also host office hours weekly. Typically this is held on Fridays, but it will be on Thursday this week if you care to bring questions on how to get started. You can show up anytime within the house. More details and registration can be found here: 
https://community.cncf.io/e/mzrkjq/

This issue/ticket is now closed.

**Comment by rakeshadr** [comment]
Thank you @AudMonte01 for creating the chapter. I'm really excited to be part of the foundation. I hope I will give my best to the growth of CNCF community!
