### ISSUE TITLE
[Organizer Request] Add & Remove Organizers from Ottawa chapter

### ISSUE THREAD

**Issue by archyufa** [cncf/communitygroups#98]
### Name of chapter inquiring about

Ottawa

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Ayrat - CNCF Ambassador organizer of Canadian CNCF Meetups.

### Tell us why you want to be added or removed from the chapter

- Please Remove Julia Simon as she is no longer active member of community and working in new industry
- Please add Nicholas Morey from Akuity. His local Ottawa and actively contribute as speaker and organizer already

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by morey-tech** [comment]
@archyufa, thanks for creating this! In case it helps, here's [my LinkedIn](https://www.linkedin.com/in/nicholas-morey/) and GitHub handle @morey-tech.

**Comment by AudMonte01** [comment]
Hi @morey-tech - please confirm you agree to the above organizer terms, and you have take the inclusive LF course listed above. Also please list the following details:

**Comment by morey-tech** [comment]
Hey @AudMonte01!

- I have completed the Inclusive Open Source Community Orientation (LFC102) course.
- I agree to the organizer terms above.
- [This](https://community.cncf.io/u/mzpgd6) is my community.cncf.io account.
- My email address is: `nicholas@morey.tech`
- I'm already a member of the public CNCF Slack workspace.

Thank!

**Comment by AudMonte01** [comment]
Excellent - thank you, @morey-tech! I have just added you as a co-organizer to the chapter. You should have received an automated email from me with next steps. If you have any questions, I host office hours every Friday. If the time works for you, feel to join anytime within the hour this Friday the 16th: https://community.cncf.io/e/mmt9em/

This issue/ticket is now closed.
