### ISSUE TITLE
[Organizer Request] Add Aadhavan Rajasekar as co-organizer to KCD Chennai

### ISSUE THREAD

**Issue by aadir7** [cncf/communitygroups#99]
### Name of chapter inquiring about

kcd chennai

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Aadhavan Rajasekar, Viasat Inc, https://github.com/aadir7, www.linkedin.com/in/aadhavanrajasekar, https://community.cncf.io/u/mp4fed/#/about

### Tell us why you want to be added or removed from the chapter

I would like to join as co-organizer. 
I have been working with Kubernetes (Infrastructure as service and apps development) for past 6 years.
I am passionate in contributing back to the Kubernetes community and expand its universe across locations. 
I see this as an opportunity to officially introduce cloud native concepts and assets to many people both in professional and educational streams.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Hello @aadir7 - please connect with @senthilrch, as applications for 2025 KCDs are now open until September 11: https://www.cncf.io/kcds/application/.

I will now close this issue/ticket. All future requests can also come via [the KCD Repository here](https://github.com/cncf/kubernetes-community-days/issues/new/choose).
